### ISSUE TITLE
It keeps telling me to fix my config...and I fixed it twice.

### ISSUE THREAD

**Issue by IngwiePhoenix** [tomav/docker-mailserver#1075] opened 2018-11-05 22:04 UTC
## Context
I just wanted to see how far I can go with docker on my dedicated server, and wanted to install a mailserver, and came across this one. So I followed the very steps of the readme, but I just keep getting the same message... I even went as far as to use `env_file` within the `docker-compose.yml` file to explicitly point at the `.env` file...but that did not help, at all.

## Expected Behavior
I expected the mailserver to just boot and probably greet me with a nice "You now have a mailserver running" message.

## Actual Behavior
```
root@ingwie-io:~/mailserver# docker-compose up
WARNING: The POSTGREY_AUTO_WHITELIST_CLIENTS variable is not set. Defaulting to a blank string.
mail is up-to-date
Attaching to mail
mail    | 2018-11-05 21:51:44,691 CRIT Supervisor running as root (no user in config file)
mail    | 2018-11-05 21:51:44,691 INFO Included extra file "/etc/supervisor/conf.d/saslauth.conf" during parsing
mail    | 2018-11-05 21:51:44,691 INFO Included extra file "/etc/supervisor/conf.d/supervisor-app.conf" during parsing
mail    | 2018-11-05 21:51:44,698 INFO RPC interface 'supervisor' initialized
mail    | 2018-11-05 21:51:44,698 CRIT Server 'unix_http_server' running without any HTTP authentication checking
mail    | 2018-11-05 21:51:44,698 INFO supervisord started with pid 1
mail    | 2018-11-05 21:51:45,701 INFO spawned: 'mailserver' with pid 10
mail    | 
mail    | #
mail    | 2018-11-05 21:51:45,726 INFO success: mailserver entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
mail    | #
mail    | # docker-mailserver
mail    | #
mail    | #
mail    | 
mail    | Initializing setup
mail    | Checking configuration
mail    |   * Setting hostname/domainname is required
mail    | 2018-11-05 21:51:45,741 WARN received SIGTERM indicating exit request
mail    | 2018-11-05 21:51:45,742 INFO waiting for mailserver to die
mail    | Error: Please fix your configuration. Exiting...
mail    | 2018-11-05 21:51:45,742 INFO stopped: mailserver (exit status 1)
```
This actually shows up ~5 times in total before the process actually exits.

## Possible Fix
Clarify in the README the exact steps to _not_ run into this. I am very certain I did all the steps mentioned in there.

## Steps to Reproduce
Follow the very steps in the README:
1. Let docker get the image.
2. Download the tools (`setup.sh`, `.env`, `docker-compose.yml`)
3. Modify `.env`
4. Run `docker-compuse up` and see what happens.

## Your Environment
* Amount of RAM available:
```
root@ingwie-io:~/mailserver# free -m
              total        used        free      shared  buff/cache   available
Mem:           7881        4255         247         139        3379        3191
Swap:           510          74         436
```

* Mailserver version used: None?
* Docker version used:
```
root@ingwie-io:~/mailserver# docker --version
Docker version 18.06.1-ce, build e68fc7a
root@ingwie-io:~/mailserver# docker-compose --version
docker-compose version 1.8.0, build unknown
```

* Environment settings relevant to the config: None that I am aware of.
* Any relevant stack traces ("Full trace" preferred): See above.

**Comment by danielpanteleit** [comment] 2018-11-06 16:47
What are your HOSTNAME, DOMAINNAME and OVERRIDE_HOSTNAME settings?

If you did not set OVERRIDE_HOSTNAME, what is the output of:
```
docker-compose run --rm mail hostname -f
```
This should return a FQDN.

**Comment by danielpanteleit** [comment] 2018-11-07 16:34
I don't think .env files support variable resolution at all. Try

```
OVERRIDE_HOSTNAME=ingwie.io
```

in the .env file.

**Comment by IngwiePhoenix** [comment] 2018-11-07 17:12
```
root@ingwie-io:~/mailserver# docker-compose up
WARNING: The POSTGREY_AUTO_WHITELIST_CLIENTS variable is not set. Defaulting to a blank string.
Recreating mail
Attaching to mail
mail    | 2018-11-07 17:11:04,748 CRIT Supervisor running as root (no user in config file)
mail    | 2018-11-07 17:11:04,748 INFO Included extra file "/etc/supervisor/conf.d/saslauth.conf" during parsing
mail    | 2018-11-07 17:11:04,748 INFO Included extra file "/etc/supervisor/conf.d/supervisor-app.conf" during parsing
mail    | 2018-11-07 17:11:04,765 INFO RPC interface 'supervisor' initialized
mail    | 2018-11-07 17:11:04,765 CRIT Server 'unix_http_server' running without any HTTP authentication checking
mail    | 2018-11-07 17:11:04,766 INFO supervisord started with pid 1
mail    | 2018-11-07 17:11:05,768 INFO spawned: 'mailserver' with pid 10
mail    | 
mail    | 2018-11-07 17:11:05,957 INFO success: mailserver entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
mail    | #
mail    | #
mail    | # docker-mailserver
mail    | #
mail    | #
mail    | 
mail    | Initializing setup
mail    | Checking configuration
mail    | Configuring mail server
mail    | grep: /tmp/docker-mailserver/postfix-accounts.cf: No such file or directory
mail    | Error: Unless using LDAP, you need at least 1 email account to start the server.
mail    | Error: Please fix your configuration. Exiting...
mail    | 2018-11-07 17:11:06,475 INFO exited: mailserver (exit status 1; not expected)
```

Well at least it passes the first check now. I guess I use `setup.sh` to add my account now, right?

**Comment by danielpanteleit** [comment] 2018-11-07 17:16
Yes, it's not very intuitive, but that's how it works right now

**Comment by IngwiePhoenix** [comment] 2018-11-07 17:31
Also make setting up SSL more obvious. that is what I am running into now at the moment… but, should not be too hard. I’ll figure it out, somehow.

**Comment by IngwiePhoenix** [comment] 2018-11-07 17:53
Also… this is kinda odd.
I tried sending myself an email through GMail and it returned this:

550 5.1.1 <o.o@ingwie.io>: Recipient address rejected: User unknown in local recipient table

This E-Mail absolutely exists, I am logging into this from the same program from which I am sending… So, why is this address unknown?

**Comment by danielpanteleit** [comment] 2018-11-07 18:37
Are you sure you created the account "o.o@ingwie.io" and not just "o.o"?

What does the mailserver log say?

**Comment by IngwiePhoenix** [comment] 2018-11-07 18:39
I did: `./setup.sh email add o.o@ingwie.io ****`
The mail log reports the same error as the mailer daemon response I get... But, where exactly do I look for the email creation messages in the log?

**Comment by danielpanteleit** [comment] 2018-11-07 18:44
There is no output of the account creation in the log. You can check `postfix-accounts.cf` in your config directory. It should contain a line starting with `o.o@ingwie.io|`

Did you restart the container after creating the account?

**Comment by IngwiePhoenix** [comment] 2018-11-07 18:51
I did just now, and I still get the same error.

**Comment by danielpanteleit** [comment] 2018-11-07 19:02
This warnings may be the problem:

```
postfix/trivial-rewrite[1294]: warning: do not list domain ingwie.io in BOTH mydestination and virtual_mailbox_domains
```

But I don't know postifx that good. You could post your .env and docker-compose.yml file just in case, but I guess someone else needs to take over.

**Comment by IngwiePhoenix** [comment] 2018-11-07 19:05
Here you are:

https://gist.github.com/IngwiePhoenix/e7cf04275b08a5657cdaa955ea5d20ca

Hopefuly someone can help... I am pretty close to having this fixed, so I'd prefer to not having to drop this all now ^^

**Comment by danielpanteleit** [comment] 2018-11-07 20:13
I think you may have to set up a subdomain for you mail server (like mail.ingwie.io) then set HOSTNAME to mail and DOMAINNAME to ingwie.io (then you won't have to set OVERRIDE_HOSTNAME at all). Your MX record should then point to mail.ingwie.io.

At least that's how I did it. I guess postfix doesn't like that your HOSTNAME and DOMAINNAME is the same.

**Comment by evaryont** [comment] 2018-11-08 19:50
The postfix issue is a duplicate of what was experienced in #968.

@danielpanteleit I understand that it makes the setup.sh script more complicated, but please don't depend on docker-compose exclusively. I deploy the mailserver container using ansible and it works wonderfully, I'd have a harder time integrating it into my configuration management structure if it did rely on docker-compose.

**Closed** 2018-11-11 19:46 UTC
Labels: help wanted, question
