### ISSUE TITLE
Cannot start server with Postgrey on

### ISSUE THREAD

**Issue by schinkelg** [tomav/docker-mailserver#649] opened 2017-07-07 10:34 UTC
Regardless of the Postgrey environment the server runs fine (first time). However, it will only stop and start with Postgrey turned off. From the logs:

```
Starting mail server
  Starting cron  [ OK ]
  Starting rsyslog  [ OK ]
  Starting dovecot services  [ OK ]
  Starting opendkim  [ OK ]
  Starting opendmarc  [ OK ]
  Starting postgreyfalse
  *  [ FAILED ]
Error: Please fix your configuration. Exiting...
```
Any ideas?

**Comment by Sharsie** [comment] 2017-07-14 03:38
Hi there, same issue.

The problem is the postgrey PID file in /var/run/postgrey/postgrey.pid remains in the filesystem when the container is killed (not stopped gracefully) and restarted - which seems to happen almost every time a SIGTERM is sent to the startup script. That is the reason why it works the first time when the container is recreated (no PID file)

Best demonstrated on an example:
Postgrey is started with `/etc/init.d/postgrey start` and creats a pid file with process ID 447
Container is killed, the PID file remains in the file system
Container starts up again, but another process takes the ID 447
`/etc/init.d/postgrey start` checks for the PID file and finds it with an ID 447 from the previous run of the container. Checks the process and finds that 447 belongs to something else than postgrey and fails the startup

I tried debugging the version 2.3, the container should be allowed to completely start up for this to happen (and sometimes it does not need to happen if another process does not take the postgrey PID)

display_startup_daemon uses /dev/null redirection to hide the output of the startup init.d scripts, so removing the redirection reveals the following problem:

`Starting mail server
  Starting cron  [ OK ]
  Starting rsyslog * Starting enhanced syslogd rsyslogd                  [ OK ] 
  [ OK ]
  Starting dovecot services  [ OK ]
  Starting opendkimStarting OpenDKIM: opendkim.
  [ OK ]
  Starting opendmarcStarting OpenDMARC: opendmarc.
  [ OK ]
  Starting postgrey * Starting postfix greylisting daemon postgrey              Pid_file already exists for running process (447)... aborting
ERROR: Pid_file already exists for running process (447)... aborting
false
  *  [ FAILED ]
Error: Please fix your configuration. Exiting...`

@tomav  It could be a good idea to redirect the output to /dev/null on default, but allowing it to be shown when DMS_DEBUG=1 is used, just a thought


Quick solution: Remove the PID file at the beginning of the startup script

I am not writing a PR for this, because the issue could be with other processes other than postgrey when the container is killed and warrants further research on what should actually happen during startup when the container is improperly killed.

Also another issue to look into would be graceful stopping of all started services, which might also be solved using `trap` for SIGTERM and SIGINT (?).

If nobody else decides to fix this I will have a look into it after the holidays (August)

**Comment by tomav** [comment] 2017-07-20 08:14
MR #658

**Comment by tomav** [comment] 2017-07-20 09:00
Merged. Thanks guys for reporting this and suggested the fix.

**Closed** 2017-07-20 08:59 UTC
