### ISSUE TITLE
Freshclam cron job does not run, no user specified

### ISSUE THREAD

**Issue by erik-wramner** [tomav/docker-mailserver#1175] opened 2019-06-13 11:36 UTC
Syslog contains errors like:
```
Jun 13 09:38:01 mail cron[424]: Error: bad username; while reading /etc/cron.d/clamav-freshclam
Jun 13 09:38:01 mail cron[424]: (*system*clamav-freshclam) ERROR (Syntax error, this crontab file will be ignored)

```
## Context
The log files complain that the freshclam crontab in cron.d is invalid as it lacks a user. It does:
`echo "0 0,6,12,18 * * * /usr/bin/freshclam --quiet" > /etc/cron.d/clamav-freshclam`
Seems there should be a user (for example root) before /usr.

## Expected Behavior
The freshclam job should run when scheduled.

## Actual Behavior
The job does not run and there are errors in syslog.

## Possible Fix
Add the user (will create a pull request).

## Steps to Reproduce
1. Run the container.
2. Wait for freshclam to run, check logs.

## Your Environment
Latest build from master.

**Comment by erik-wramner** [comment] 2019-06-18 06:51
See pull request #1176. Ready to accept, unit tests now pass.

**Comment by tomav** [comment] 2019-07-23 16:40
Merged.

**Closed by tomav** 2019-07-23 16:40 UTC

**Comment by cybermcm** [comment] 2019-07-24 12:09
Hi,
since my latest update today I get an error message:
```
ERROR: Problem with internal logger (UpdateLogFile = /var/log/mail/freshclam.log).
ERROR: Can't open /var/log/mail/freshclam.log in append mode (check permissions!).
```
Is this related to the latest change?
I have no freshclam.log in my persistent volume, inside my container there is a file (from yesterday):
```
root@mail:/var/log/clamav# ls -la
total 16
drwxr-xr-x 1 clamav clamav 4096 Jul 23 16:59 .
drwxr-xr-x 1 root   root   4096 Jul 24 03:34 ..
-rw-r----- 1 clamav adm       0 Jul 23 16:59 clamav.log
-rw-r----- 1 clamav adm    1321 Jul 23 17:04 freshclam.log
```
any advise?

**Comment by erik-wramner** [comment] 2019-07-26 08:11
Could be, I haven't seen that though. Where do you get the error? In syslog?

**Comment by cybermcm** [comment] 2019-07-26 08:57
It's from syslog, I'm receiving it as mail.
can be triggered with
> /usr/bin/freshclam
it is located in /etc/cron.d/clamav-freshclam

**Comment by scottstensland** [comment] 2019-07-27 21:22
my setup has been running fine for months suddenly as of few days ago I also get above error 
however I am not running clam as per env var

echo $ENABLE_CLAMAV

0

Why am I suddenly getting above error ?   What is launch config change needed to avoid above ?

**Comment by erik-wramner** [comment] 2019-07-28 07:10
Ah, that might explain it. The background is that there has been a large backlog of fixes that were applied now. One was that the cron job for freshclam was broken and did not run. Fixing that works for me, but apparently the job doesn't work well when clam is disabled.

Short term you could just delete the cron job:

`docker exec yourmailcontainername rm -f /etc/cron.d/clamav-freshclam
`
It will be back when you re-create the container, but at least you can quickly get rid of the problem. Long term we should make sure that the job is disabled or at the very least works when clam has been disabled.

**Comment by cybermcm** [comment] 2019-07-28 07:38
@erik-wramner ClamAV is enabled in my case, still seeing this error.
Probably caused by my setting to write log files to a volume (although freshclam log is located in /var/log/clamav)?
> /opt/mail/log:/var/log/mail

**Comment by erik-wramner** [comment] 2019-07-28 07:46
@cybermcm it is hard to say as I'm not seeing this myself (I'm running a forked version with some changes and the tests do pass), but I'm making two changes in #1198. One is to delete the cron job when clamav is off, the other is to run the job as the clamav user when it is on. It shouldn't need to run as root.

Perhaps you could edit the job in your container and replace root with clamav and see if that helps?

I really can't see why root should fail to append to the file, but perhaps there are SELinux or AppArmor things going on that might work better with the clamav user.

**Comment by cybermcm** [comment] 2019-07-28 11:19
@erik-wramner running
> runuser -l clamav -c '/usr/bin/freshclam'

inside the container triggers no error but there is also no response.
e.g.
> runuser -l clamav -c 'whoami'

has no result? Maybe docker specific (I'm neither Linux or Docker expert).
What I missed is the fact that my error shows  /var/log/mail/freshclam.log where  /var/log/mail is the folder which is pointed to a docker volume.
So what I did is to create a blank freshclam.log file within my volume and changed the ownership, now it is working with no error!
