### ISSUE TITLE
SMTP: No AUTH option

### ISSUE THREAD

**Issue by scrwr** [tomav/docker-mailserver#838] opened 2018-02-13 01:02 UTC
In latest version (286 MB, 5 days ago, 9ef4efc51cd7...) SMTP EHLO doesn't provide 
```
250-AUTH PLAIN LOGIN
250-AUTH=PLAIN LOGIN
```
anymore. Ergo login isn't possible anymore.
In tag 2.3 (320 MB, 17 days ago, 7aaf98379b39...) its still working fine.

I checked the usual suspects:
```
# doveconf 
auth_mechanisms = plain login

# postconf
smtpd_tls_auth_only = no
smtpd_sasl_type = dovecot
```

And I also tried via STARTTLS:
```
 > openssl s_client -starttls smtp -crlf -connect mail.example.com:25
...
250 SMTPUTF8
EHLO test
250-mail.example.com <- changed
250-SIZE 10240000
250-ETRN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 SMTPUTF8
```

My docker-compose:
```
  mx:
    image: tvial/docker-mailserver
    hostname: mail
    domainname: example.com
    cap_add:
     - NET_ADMIN
    ports:
     - "25:25"
     - "143:143"
     - "587:587"
     - "993:993"
    volumes:
     - /opt/mx/config/:/tmp/docker-mailserver/
     - /opt/mx/maildir:/var/mail
     - /opt/mx/mail-state:/var/mail-state
     - /opt/mx/certs/mail.example.com:/etc/letsencrypt/live/mail.example.com
    environment:
      SSL_TYPE: letsencrypt
      ENABLE_SPAMASSASSIN: 1
      ENABLE_CLAMAV: 1
      ENABLE_FAIL2BAN: 1
      SA_TAG2: 4.0
    restart: unless-stopped
```

**Comment by 17Halbe** [comment] 2018-02-13 13:23
Can you please post the log from the container?
Preferable with [DMS_DEBUG](https://github.com/tomav/docker-mailserver/blob/master/README.md#dms_debug) enabled.
From which client are you connecting to the server? From which network?

**Comment by scrwr** [comment] 2018-02-13 21:12
[mx-clean.log](https://github.com/tomav/docker-mailserver/files/1721693/mx-clean.log)

I tried to anonymize the log as much as possible. Example.org and .net are not the real domains, the user names and IPs have been obfuscated. If you need more details on these log lines, let me know.

First time encounter was on an MacOS Mail client. But to abstract the issue from a certain client, I was showcasing the issue with openssl client above. So the issue is not related to a specific client.

The server is running on a data center and I accessed it from VDSL home network.

**Comment by 17Halbe** [comment] 2018-02-13 23:29
If the last part of the log states what happened while you attempted to login to that server we got two problems. 
Postscreen is complaining about your login attempt not behaving correctly:
`Feb 13 20:55:21 mail postfix/postscreen[1256]: PREGREET 11 after 0.01 from [x.x.x.x]:23476: EHLO User\r\n`
Means that the client at [address]:port sent 11 bytes before its turn to speak. This happened 0.01 seconds after the postscreen_greet_wait timer was started. The text is what the client sent (truncated to 100 bytes, and with non-printable characters replaced with C-style escapes such as \r for carriage-return and \n for newline). 

So I guess this was your openssl try.

The bigger issue is actually that your client IP is listed as a spam delivery address. 
```
Feb 13 20:55:21 mail postfix/dnsblog[1262]: addr x.x.x.x listed by domain zen.spamhaus.org as x.x.x.x
Feb 13 20:55:21 mail postfix/postscreen[1256]: DNSBL rank 3 for [x.x.x.x]:23476time
```

And that's definitely happing for a reason. (Might be you, someone else behind your VDSL or an IP-Address assigned to you by your ISP which was formerly used to send spam.)

So you can get around that error, if you add this config-option to your environment section in the docker-compose.yaml:
'POSTSCREEN_ACTION = ignore`
see [POSTSCREEN_ACTION](https://github.com/tomav/docker-mailserver#postscreen_action)

But I highly encourage you to figure out who is sending spam mails from your IP and remove that config option from the docker-compose.yaml file afterwords.

**Comment by scrwr** [comment] 2018-02-14 06:58
The first attempt was mine, and the complain from postscreen is correct, but is a result of the fact, that EHLO didn't offer me an AUTH mechanism (see initial bug report). So thats not the cause, but a result.

The second attempt (from 20:55:21 on) with the blacklisted IP wasn't me. So this is also correct.

My problem is, that EHLO doesn't offer AUTH mechanisms with this latest release, and I don't see any reasons why.

**Comment by johansmitsnl** [comment] 2018-02-14 07:36
You should not send email out with a client over port 25.

[postscreen readme:](http://www.postfix.org/POSTSCREEN_README.html)
> postscreen(8) should not be used on SMTP ports that receive mail from end-user clients (MUAs).

**Comment by scrwr** [comment] 2018-02-14 17:07
So. Indeed on port 587 AUTH mechanisms are advertised. On the opposite, what is the rationale behind not advertising AUTH mechanisms on port 25. Many end-user clients still use this port per default.

**Comment by mwlczk** [comment] 2018-02-14 17:14
@scrwr this is deprecated and at some point should be dropped. Most of those clients are capable of using the correct ports.

**Comment by johansmitsnl** [comment] 2018-02-14 19:46
If you use Thunderbird or Android the default port is already 587 or 465.
Port 25 is also blocked for a lot of providers to prevent personal mailservers or other malicious software spamming.

**Comment by 17Halbe** [comment] 2018-02-15 08:46
Sorry for the late reply. I overread that you were using port 25, that would have been a lot easier to solve then! ;)

For further information, why this is important:
[The importance of locking down Port 25](https://www.fusemail.com/en-gb/email-security-importance-locking-port-25-2/)
So can this be closed than?

**Comment by scrwr** [comment] 2018-02-15 09:23
Thanks guys for your quick support. 

But even with the read through your information about locking down port 25, I don't get the point behind preventing only AUTH-enticated access, which is the opposite to the complained open relay. I get of course the point, that unauthenticated access on port 25 only delivers to local recipients. But this doesn't imply preventing AUTHenticated access at all.

In any case, it is a breaking change (intentional or unintentional) and I would recommend at least to put it clearly in the README. I still don't agree with your POV, but I need to dig deeper into this topic first, before arguing further with you. :)

Feel free to close this issue. And once again, thanks for your support. Awesome quick.

**Comment by 17Halbe** [comment] 2018-02-15 16:28
Sorry, didn't want to sound rude.. 
And I changed my mind, I think we shouldn't close this, it's actually quite essential to figure out which ports we want to keep open.
IETF published RFC 821 in 1982, establishing port 25 as the default channel for email. There were some RFCs obsoleted this initial SMTP RFC. Whatever, you are still/partly right, [RFC2476](https://tools.ietf.org/html/rfc2476) states 

> While most email clients and servers can be configured to use port
   587 instead of 25, there are cases where this is not possible or
   convenient.  A site MAY choose to use port 25 for message submission,
   by designating some hosts to be MSAs and others to be MTAs.

In general the RFC defined that message relay only should be handled via port 25, Message submission on port 587.

So IMHO, we shouldn't use port 25 for anything else than relaying from MSA->MTA or MTA->MTA.

**Comment by johansmitsnl** [comment] 2018-02-15 18:29
@scrwr what @17Halbe described was what I always used to to submitting email and knew about. When you look at Office365 or Amazon they all use 587 for email submission.
But I agree a note in the README should be nice, I'll make a PR for this.
The tests that are in place for this project didn't test for email submission on port 25 so that's why the change of @17Halbe didn't ring the alarm bells of failing tests and breaking changes.

I also think introducing back the CHANGELOG for a PR would be nice to read back what has changed so it makes it easier to track changes that might broke some functionality.

**Comment by 17Halbe** [comment] 2018-02-15 19:36
@johansmitsnl Do you want me to change the postscreen implementation? We could change it to be optional. 
Though I would rather have it enabled by default. 
I could also do that README PR, since i introduced that braking change.
Sorry for not realizing that the postscreen service broke AUTH on Port 25.

**Comment by johansmitsnl** [comment] 2018-02-18 09:32
@17Halbe I think it should be default.

Could you verify: https://github.com/johansmitsnl/docker-mailserver/tree/update_readme_and_changelog#exposed-ports

**Comment by 17Halbe** [comment] 2018-02-18 10:49
Nice! :+1:

**Closed** 2018-03-02 21:34 UTC

**Comment by scrwr** [comment] 2018-03-03 10:55
Thanks guys.

Changed the setup according to your recommendations.
