### ISSUE TITLE
Verify return code: 21 (unable to verify the first certificate)

### ISSUE THREAD

**Issue by gj550472603** [tomav/docker-mailserver#1141] opened 2019-03-08 07:58 UTC
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: DB4CF6BF14F29670DFE4237EC605E533931DEB07C832516250BEB023193E261D
    Session-ID-ctx: 
    Master-Key: FF885B61ADC06B4829ED31319E0FF4BE5412E4187855CF6CB8B86A52D8A09D8EC344821A043385343062842376119F30
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 13 d9 2b aa fa 52 7f f7-a6 55 83 b6 7b de 78 5a   ..+..R...U..{.xZ
    0010 - 8f b0 fe c8 57 e4 bd dc-b2 26 62 40 3f 35 be 8f   ....W....&b@?5..
    0020 - dd 8c fc 0e ed 5a 72 70-a8 e9 d8 91 fa 82 c4 aa   .....Zrp........
    0030 - 70 d2 5d 11 08 31 d1 c9-73 c3 4c 44 a9 27 6a 4f   p.]..1..s.LD.'jO
    0040 - 03 0e 49 f0 90 1b 5c 28-5f 0c 9e 82 2a 95 43 18   ..I...\(_...*.C.
    0050 - b4 a3 0e c7 ec 6a 3a 6b-25 0b 53 90 cb b1 77 d9   .....j:k%.S...w.
    0060 - 2e 88 05 1f 5f 28 2e 67-40 0d 38 72 e2 77 b7 49   ...._(.g@.8r.w.I
    0070 - 8b 8c fb 1c 5c 53 d5 e2-2a 7b 50 2a 45 e4 ec 31   ....\S..*{P*E..1
    0080 - d4 1d ba e9 02 7b 78 7c-a0 aa 2a 72 d1 a8 62 ea   .....{x|..*r..b.
    0090 - 05 18 b6 41 2d bf 67 de-cf f6 03 56 b6 ef 0c 1d   ...A-.g....V....
    00a0 - e6 f8 0f dc 3e 31 a7 5b-1f 6d fc 75 c6 30 c7 a5   ....>1.[.m.u.0..

    Start Time: 1552031677
    Timeout   : 7200 (sec)
    Verify return code: 21 (unable to verify the first certificate)
    Extended master secret: yes
---
250 SMTPUTF8

**Comment by johansmitsnl** [comment] 2019-03-10 19:40
Duplicate of #1130

**Closed by johansmitsnl** 2019-03-10 19:40 UTC

**Comment by henrytom1703** [comment] 2019-04-02 08:12
I have same issues . Could anyone help me?
```
```
volumes:
  - /etc/ssl:/tmp/ssl:ro
environment:
- SSL_TYPE=manual
- SSL_CERT_PATH=/tmp/ssl/public.crt
- SSL_KEY_PATH=/tmp/ssl/private.key
```
```
