### ISSUE TITLE
Cannot build the Dockerfile

### ISSUE THREAD

**Issue by Kralock** [tomav/docker-mailserver#389] opened 2016-11-25 14:23 UTC
Hi there ! 
When i trie to build the Dockerfile, i've got this error :

```
Step 23 : RUN razor-admin -create && razor-admin -register && pyzor discover
 ---> Running in c4a87a8369d2
nextserver: Bootstrap discovery failed. Giving up.
```

My objective, to build Smtp with Ldap configuration, but file is COPY from directory : 

`"COPY target/postfix/ldap-users.cf target/postfix/ldap-groups.cf target/postfix/ldap-aliases.cf /etc/postfix/"`

That's why I need to re-build with the Dockerfile..

**Comment by tomav** [comment] 2016-11-29 16:21
You can't mount the folder or use `FROM tvial/docker-mailserver:v2`?
I tried to build the project from scratch on a fresh server and it works well. I can't reproduce your issue.

Let me know is you have more information to provide.

**Comment by tomav** [comment] 2016-12-17 15:32
Closing do to lack of information.
Reopen if needed.

**Closed by tomav** 2016-12-17 15:32 UTC

**Comment by spock** [comment] 2016-12-28 17:43
Have the same razor-related problem while building.
I was getting different error messages (resulting in build failure) at this step:
`Step 24 : RUN razor-admin -create && razor-admin -register && pyzor discover`

Some of the errors that I've seen are:
```
No Razor servers available at this time
register: Timed out (15 sec) while reading from n001.cloudmark.com
```

(Haven't recorded the first few, but along the same lines of having problems with sockets, timeouts, etc.)

The build did work on the 4th-5th try, so I think these are some intermittent `razor` network/server issues.
