### ISSUE TITLE
Make spamassassin work for multiple users

### ISSUE THREAD

**Issue by thiesschneider** [tomav/docker-mailserver#592] opened 2017-05-05 13:39 UTC
Hi,

in my installation I have multiple domains and it seems that spamassassin does not scan all the domains. In https://github.com/tomav/docker-mailserver/issues/496 it should be fixed.
Do I need to add some config to make it work?

Thx in advance!

**Comment by tomav** [comment] 2017-05-06 08:21
Hi @thiesschneider, could you check that you have `/etc/amavis/conf.d/60-dms_default_config` in your image?

**Comment by thiesschneider** [comment] 2017-05-06 10:42
Hi @tomav,

yes, I have this file and it looks fine:
```
use strict;

@local_domains_maps = (
   read_hash('/etc/postfix/vhost')
);

1;  # ensure a defined return
```
inside vhost there are also the correct domains.
Any ideas how to check if it really works?

**Comment by tomav** [comment] 2017-05-06 18:52
With that configuration, I have spassassin headers on all my domains:

```
X-Spam-Flag: NO
X-Spam-Score: -1.901
X-Spam-Level:
X-Spam-Status: No, score=-1.901 tagged_above=-5 required=4.9
	tests=[BAYES_00=-1.9, DKIM_SIGNED=0.1, DKIM_VALID=-0.1,
	HTML_MESSAGE=0.001, RCVD_IN_DNSWL_NONE=-0.0001,
	RCVD_IN_MSPIKE_H2=-0.001, SPF_HELO_PASS=-0.001]
	autolearn=ham autolearn_force=no
```

**Comment by thiesschneider** [comment] 2017-05-09 11:25
I do not know hot to test this and I am also confused with this part in the wiki:

> Why are Spamassassin x-headers not inserted into my sample.domain.com subdomain emails?
> 
> In the default setup, amavis only applies Spamassassin x-headers into domains matching the template listed in the config file 05-domain_id (in the amavis defaults). The default setup @local_domains_acl = ( ".$mydomain" ); does not match subdomains. To match subdomains, you can override the @local_domains_acl directive in the amavis user config file 50-user with @local_domains_maps = ("."); to match any sort of domain template.

Is it possible to clearify this section in the wiki?

**Comment by tomav** [comment] 2017-05-09 14:52
With the improvement made, this part is outdated I suppose.
Regarding "how to test it", send an email from an external account to 2 different domains hosted on your mail-server. In the logs (and in the headers regarding your configuration), you should see what I pasted above.

**Comment by radicand** [comment] 2020-01-23 20:11
I'm having this issue as well - I had to manually edit `/etc/amavis/conf.d/05-domain-id` to list out all my domains manually:

e.g.,

```
@local_domains_acl = ( ".$mydomain", ".domain1.org", ".domain2.com");
```

Would be great to understand the root cause of `/etc/amavis/conf.d/60-dms_default_config` not working as intended.

**Comment by aendeavor** [comment] 2020-09-21 13:18
@radicand Have you investigated in this? I would like to close this issue, but it seems like it is still not solved.

**Comment by radicand** [comment] 2020-09-21 13:49
@aendeavor I haven't come back to this since my original comment - the edits are built into my K8s deployment and work with the changes I noted (even if onerous).

**Comment by aendeavor** [comment] 2020-09-21 14:14
Alright. I'll label this properly and leave it open. I can't fix this, so someone else must do it.

**Comment by aendeavor** [comment] 2020-10-29 08:07
I will now close this off as (and we talked about that in another issue) this issue has become stale, there is no activity and it's 3 years old.

If, in the future, something is done here, feel free to re-open or ask me to re-open.

**Closed by aendeavor** 2020-10-29 08:07 UTC
Labels: bug, documentation, frozen due to age, kubernetes, priority 2 [MEDIUM], waiting for contributor action
