### ISSUE TITLE
generate-dkim-config fails silently

### ISSUE THREAD

**Issue by Znafon** [tomav/docker-mailserver#478] opened 2017-01-16 13:01 UTC
As of 2.1 it's impossible to generate DKIM config, using this dockerfile:

```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:2.1
    hostname: mail
    domainname: domain.com
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```

nothing happens when running:

```
docker run --rm \
>   -v "$(pwd)/config":/tmp/docker-mailserver \
>   -ti tvial/docker-mailserver:latest generate-dkim-config
```

**Comment by tomav** [comment] 2017-01-16 14:42
Hi @Znafon, I can't reproduce your issue.
Have you generate users before? If no user => no domain => no key 

```
➜  Desktop mkdir -p config
➜  Desktop touch config/postfix-accounts.cf
➜  Desktop docker run --rm \
>   -e MAIL_USER=user1@domain.tld \
>   -e MAIL_PASS=mypassword \
>   -ti tvial/docker-mailserver:latest \
>   /bin/sh -c 'echo "$MAIL_USER|$(doveadm pw -s SHA512-CRYPT -u $MAIL_USER -p $MAIL_PASS)"' >> config/postfix-accounts.cf
➜  Desktop cat config/postfix-accounts.cf
user1@domain.tld|{SHA512-CRYPT}$6$wApjP35gUVnZJFkT$YuTrJIYEpzVDvLQ8Dm4l//akCFuowi789pctUXsO3Qr85UrsVsrVJJXvpoO/oJdRrZeIFpyJg8bwKtgU0.2KM/
➜  Desktop subl .
➜  Desktop docker run --rm \
>   -v "$(pwd)/config":/tmp/docker-mailserver \
>   -ti tvial/docker-mailserver:latest generate-dkim-config
Creating DKIM private key /tmp/docker-mailserver/opendkim/keys/domain.tld/mail.private
Creating DKIM KeyTable
Creating DKIM SigningTable
Creating DKIM TrustedHosts
➜  Desktop
```

**Comment by tomav** [comment] 2017-01-18 08:55
Hi @Znafon, any update on that point?

**Comment by Znafon** [comment] 2017-01-18 09:30
Well, I just tried, it’s seems I’m not very smart. I was trying with the LDAP database and was surprised it was not working. Maybe we could make `generate-dkim-config` take a domain name as argument for when the accounts are not given in the `postfix-accounts.cfg` file ?


Le 18 janvier 2017 à 09:55:59, Thomas VIAL (notifications@github.com) a écrit:

Hi @Znafon, any update on that point?

**Comment by tomav** [comment] 2017-01-18 09:37
That may an improvement, yes.

**Comment by Znafon** [comment] 2017-01-21 22:29
I quickly looked though the script to improve it.

Is there a reason you only use bash scripts? Python is installed in the image and may be more readable in my opinion.

**Comment by tomav** [comment] 2017-01-22 08:49
Yep, `bash` is the default shell and usually known by linux users when python is not.
I don't think moving to python worth it today.

**Comment by Znafon** [comment] 2017-01-30 15:00
Hi, I'm trying to work on this issue by making `generate-dkim-config` check the LDAP server when it's enabled, but I can't get the tests to work. I attached the logs of `make` on this comment.
[tests.txt](https://github.com/tomav/docker-mailserver/files/739266/tests.txt)

**Comment by tomav** [comment] 2017-02-09 20:06
Seems to be due to server or network trouble. It happens sometimes on our builds.
Could you retry?

**Comment by remogatto** [comment] 2017-02-27 11:53
Hi @Znafon , I'm hitting the same issue: DKIM+OpenLDAP. Can you share your fix, please? I'd like to help. Thanks.

**Comment by Znafon** [comment] 2017-02-27 11:58
Hi, you can add a dummy address to config/postfix-accounts.cf, generate keys with `generate-dkim-config` and remove the address from config/postfix-accounts.cf.

Making a fix for this issue is still on my todo list, i will do it when i have a bit of time.

**Comment by johansmitsnl** [comment] 2017-09-08 18:44
#619 also has the same problem

**Comment by johansmitsnl** [comment] 2017-09-10 08:08
#690 is merged now.

**Closed by johansmitsnl** 2017-09-10 08:08 UTC
Labels: enhancement

**Comment by jcommelin** [comment] 2018-08-22 14:45
This problem also shows up when following the Installation Example on the wiki.

**Comment by Thram** [comment] 2019-04-26 11:55
Still happening

**Comment by Onetail** [comment] 2021-03-17 09:42
Still happening
