### ISSUE TITLE
HELP: Simple Setup Does not work

### ISSUE THREAD

**Issue by elcolie** [tomav/docker-mailserver#707] opened 2017-09-02 06:06 UTC
python 3.6.2
docker-compose version 1.16.1, build 6d1ac219
docker-py version: 2.5.1
CPython version: 3.6.2
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
AWS EC2

Here is my `DNS`:
elcolie.com. | A | 13.228.78.175
elcolie.com. | MX | 10 elcolie.com
elcolie.com. | SOA | ns-905.awsdns-49.net. awsdns-hostmaster.amazon.c
elcolie.com. | NS | ns-905.awsdns-49.net.  ns-1242.awsdns-27.org.  ns-1822.awsdns-35.co.uk.  ns-260.awsdns-32.com.

**Image pull on 2Sep 4:44 UTC 2017**

`docker-compose.yml`

version: '2'

```bash
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: elcolie.com
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```

My directory:
```bash
tomav-mailserver/
├── config
│   ├── opendkim
│   │   ├── keys
│   │   │   └── elcolie.com
│   │   │       ├── hosts
│   │   │       ├── mail.private
│   │   │       └── mail.txt
│   │   ├── KeyTable
│   │   ├── SigningTable
│   │   └── TrustedHosts
│   └── postfix-accounts.cf
└── docker-compose.yml

4 directories, 8 files
```

`cat tomav-mailserver/config/postfix-accounts.cf`
```
sarit@elcolie.com|{SHA512-CRYPT}$6$Q5c6Y9IRS7P/AYf1$R8vVU7BkZvdfbTq0dUUTTWGbz2FxakCDMClh4U.VSMdIxkK.1oks1OSR5..OvjuWz3In1eQHNcb9I4ayq89qT.
```

`cat tomav-mailserver/config/opendkim/keys/elcolie.com/mail.txt`
```
mail._domainkey IN      TXT     ( "v=DKIM1; k=rsa; "
          "p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDIioW92SlSn5n77F3WnYHh5aBrfSIRWYt0rCc//bcK1dhvY3OfnH4a8NljmS7ThrbxWZpdHm7wNedLr/RQ97Du7yd9gQtFNbDlWVTJz+TBTpx8bbEa+Uckgbh0r3fNiSs5duEdrfFZMEomxLBZdhe0iHkDVVeqclgCPFVhCLVLiQIDAQAB" )  ; ----- DKIM key mail for elcolie.com
```

Here is my `docker-compse -logs mail`
```bash
Attaching to mail
mail    | 2017-09-02 05:43:00,753 CRIT Supervisor running as root (no user in config file)
mail    | 2017-09-02 05:43:00,753 WARN Included extra file "/etc/supervisor/conf.d/saslauth.conf" during parsing
mail    | 2017-09-02 05:43:00,753 WARN Included extra file "/etc/supervisor/conf.d/supervisor-app.conf" during parsing
mail    | 2017-09-02 05:43:00,760 INFO RPC interface 'supervisor' initialized
mail    | 2017-09-02 05:43:00,760 CRIT Server 'unix_http_server' running without any HTTP authentication checking
mail    | 2017-09-02 05:43:00,760 INFO supervisord started with pid 5
mail    | 2017-09-02 05:43:01,776 INFO spawned: 'mailserver' with pid 8
mail    | 
mail    | 2017-09-02 05:43:01,787 INFO success: mailserver entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
mail    | #
mail    | #
mail    | # docker-mailserver
mail    | #
mail    | #
mail    | 
mail    | Initializing setup
mail    | Checking configuration
mail    | Configuring mail server
mail    | Starting Misc
mail    | Starting mail server
mail    | unix:///var/run/supervisor.sock refused connection
mail    | unix:///var/run/supervisor.sock refused connection
mail    | unix:///var/run/supervisor.sock refused connection
mail    | unix:///var/run/supervisor.sock refused connection
mail    | unix:///var/run/supervisor.sock refused connection
mail    | unix:///var/run/supervisor.sock refused connection
mail    | unix:///var/run/supervisor.sock refused connection
mail    | unix:///var/run/supervisor.sock refused connection
mail    | unix:///var/run/supervisor.sock refused connection
mail    | unix:///var/run/supervisor.sock refused connection
mail    | 
mail    | #
mail    | # mail.domain.com is up and running
mail    | #
mail    | 
mail    | 2017-09-02 05:51:29,244 CRIT Supervisor running as root (no user in config file)
mail    | 2017-09-02 05:51:29,244 WARN Included extra file "/etc/supervisor/conf.d/saslauth.conf" during parsing
mail    | 2017-09-02 05:51:29,244 WARN Included extra file "/etc/supervisor/conf.d/supervisor-app.conf" during parsing
mail    | Unlinking stale socket /var/run/supervisor.sock
mail    | 2017-09-02 05:51:29,553 INFO RPC interface 'supervisor' initialized
mail    | 2017-09-02 05:51:29,553 CRIT Server 'unix_http_server' running without any HTTP authentication checking
mail    | 2017-09-02 05:51:29,553 INFO supervisord started with pid 5
mail    | 2017-09-02 05:51:30,555 INFO spawned: 'mailserver' with pid 8
mail    | 
mail    | 2017-09-02 05:51:30,566 INFO success: mailserver entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
mail    | #
mail    | #
mail    | # docker-mailserver
mail    | #
mail    | #
mail    | 
mail    | Initializing setup
mail    | Checking configuration
mail    | Configuring mail server
mail    | Starting Misc
mail    | Starting mail server
mail    | unix:///var/run/supervisor.sock refused connection
mail    | unix:///var/run/supervisor.sock refused connection
mail    | unix:///var/run/supervisor.sock refused connection
mail    | unix:///var/run/supervisor.sock refused connection
mail    | unix:///var/run/supervisor.sock refused connection
mail    | unix:///var/run/supervisor.sock refused connection
mail    | unix:///var/run/supervisor.sock refused connection
mail    | unix:///var/run/supervisor.sock refused connection
mail    | unix:///var/run/supervisor.sock refused connection
mail    | unix:///var/run/supervisor.sock refused connection
mail    | 
mail    | #
mail    | # mail.domain.com is up and running
mail    | #
mail    | 
```

On the client side I have followed in the section `How can I configure my email client?`
But it does not work
`https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips`

Where am I wrong?

**Update:**
Correct `domain.com` to `elcolie.com`. Error still persist.

**Comment by tomav** [comment] 2017-09-06 09:46
Could you check permissions on `/var/run/supervisor.sock`?

**Comment by elcolie** [comment] 2017-09-07 10:45
Here it is
```bash
root@mail:/var/run# pwd
/var/run
root@mail:/var/run# ls -alh supervisor.sock 
srwx------ 1 root root 0 Sep  7 10:43 supervisor.sock
```

**Comment by tomav** [comment] 2017-09-07 16:13
Hmm, same permission here... I can't reproduce the issue. 
This may help: https://github.com/Supervisor/supervisor/issues/654

**Comment by elcolie** [comment] 2017-09-07 17:47
I do not understand. How do I adapt it?
Your given answer also refer the deep level of os. 
Which I have no idea on it.

https://github.com/moby/moby/issues/12080
 kung-foo

```
FWIW, I "solved" the supervisord issue above by changing the sock to /dev/shm/supervisor.sock.
```
Then Do I have to fork and build my own image?

**Comment by johansmitsnl** [comment] 2017-09-07 17:58
@elcolie when you read the issue you see that the docker storage driver is an issue.
When you run `docker info` "Storage Driver" does it say: overlayfs?
By default Ubuntu 16.04 uses `aufs` and this works ok. Also `overlayfs2` works.

Changing the storrage driver might do the trick. But is does not solve it for all users.

Making this similar [change](https://github.com/hardware/mailserver/pull/5/files) might solve the issue. Could you create a PR for this?

**Comment by elcolie** [comment] 2017-09-09 08:01
I checked out the repo and finding for `supervisor`. I found `./target/supervisor/supervisor-app.conf`
But not found `/var/run/supervisor.sock` line

**Comment by justjustin1980** [comment] 2017-09-09 09:34
Stop

**Comment by johansmitsnl** [comment] 2017-09-10 08:34
@elcolie can you paste the output of `$ docker info` of your docker host?

**Comment by elcolie** [comment] 2017-09-10 09:14
Host OS is GNU/Linux Debian stretch

```bash
# docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 1
Server Version: 17.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.6.0-1-amd64
Operating System: Debian GNU/Linux stretch/sid
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.956GiB
Name: ip-172-31-23-120
ID: 27NL:WAPF:53BV:5ZLM:AQCW:NTEO:TUH3:RG35:6CMZ:RPCC:MI5F:XEXA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
```

```bash
# docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:01:59 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 21:59:51 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```bash
# docker-compose version
docker-compose version 1.16.1, build 6d1ac219
docker-py version: 2.5.1
CPython version: 3.6.2
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Comment by johansmitsnl** [comment] 2017-09-10 13:39
Could you try to build it my fix branch?
https://github.com/johansmitsnl/docker-mailserver/tree/supervisor-sock

**Comment by elcolie** [comment] 2017-09-11 17:55
Can not build an image because `clamav` url is broken. Here is my `compose` file.

```html
Forbidden

You don't have permission to access / on this server.
Apache/2.4.7 Server at db.local.clamav.net Port 80
```

```bash
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:2.1
    build:
      context: .
      dockerfile: Dockerfile
    hostname: mail
    domainname: elcolie.com
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN
    restart: always

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```


```bash
ClamAV update process started at Mon Sep 11 17:49:53 2017
WARNING: getfile: main.cvd not found on db.local.clamav.net (IP: 130.59.113.36)
WARNING: Can't download main.cvd from db.local.clamav.net
Trying again in 5 secs...
ClamAV update process started at Mon Sep 11 17:49:59 2017
Trying host db.local.clamav.net (193.1.193.64)...
WARNING: getfile: main.cvd not found on db.local.clamav.net (IP: 193.1.193.64)
WARNING: Can't download main.cvd from db.local.clamav.net
Trying again in 5 secs...
ClamAV update process started at Mon Sep 11 17:50:06 2017
WARNING: Can't download main.cvd from db.local.clamav.net
Trying again in 5 secs...
ClamAV update process started at Mon Sep 11 17:50:11 2017
WARNING: Can't download main.cvd from db.local.clamav.net
Trying again in 5 secs...
ClamAV update process started at Mon Sep 11 17:50:16 2017
ERROR: Can't download main.cvd from db.local.clamav.net
Giving up on db.local.clamav.net...
ClamAV update process started at Mon Sep 11 17:50:16 2017
ERROR: Can't download main.cvd from database.clamav.net
Giving up on database.clamav.net...
Update failed. Your network may be down or none of the mirrors listed in /etc/clamav/freshclam.conf is working. Check http://www.clamav.net/doc/mirrors-faq.html for possible reasons.
ERROR: Service 'mail' failed to build: The command '/bin/sh -c echo "0 0,6,12,18 * * * /usr/bin/freshclam --quiet" > /etc/cron.d/freshclam &&   chmod 644 /etc/clamav/freshclam.conf &&   freshclam &&   sed -i 's/Foreground false/Foreground true/g' /etc/clamav/clamd.conf &&   sed -i 's/AllowSupplementaryGroups false/AllowSupplementaryGroups true/g' /etc/clamav/clamd.conf &&   mkdir /var/run/clamav &&   chown -R clamav:root /var/run/clamav' returned a non-zero code: 52
```

**Comment by elcolie** [comment] 2017-09-11 18:01
Without `clamav`
`- ENABLE_CLAMAV=0`

I got
```bash
Step 44/49 : COPY ./target/start-mailserver.sh ./target/fail2ban-wrapper.sh ./target/postfix-wrapper.sh ./target/docker-configomat/configomat.sh /usr/local/bin/
ERROR: Service 'mail' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder893696864/target/docker-configomat/configomat.sh: no such file or directory
```

**Comment by johansmitsnl** [comment] 2017-09-12 06:23
That will not work. Try to build it again, sometimes freshclam fails and just try it again.

**Comment by elcolie** [comment] 2017-09-15 19:13
```bash
1 [4255 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 4255 kB in 4s (887 kB/s)
Selecting previously unselected package filebeat.
(Reading database ... 14560 files and directories currently installed.)
Preparing to unpack .../filebeat_1.3.1_amd64.deb ...
Unpacking filebeat (1.3.1) ...
Processing triggers for systemd (229-4ubuntu19) ...
Setting up filebeat (1.3.1) ...
Processing triggers for systemd (229-4ubuntu19) ...
Reading package lists...
Building dependency tree...
Reading state information...
 ---> 50fd9ec90572
Removing intermediate container 01110f62f501
Step 13/49 : RUN echo "0 0,6,12,18 * * * /usr/bin/freshclam --quiet" > /etc/cron.d/freshclam &&   chmod 644 /etc/clamav/freshclam.conf &&   freshclam &&   sed -i 's/Foreground false/Foreground true/g' /etc/clamav/clamd.conf &&   sed -i 's/AllowSupplementaryGroups false/AllowSupplementaryGroups true/g' /etc/clamav/clamd.conf &&   mkdir /var/run/clamav &&   chown -R clamav:root /var/run/clamav
 ---> Running in 9ba2de182944
ClamAV update process started at Fri Sep 15 19:04:24 2017
Downloading main.cvd [100%]
main.cvd updated (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
Downloading daily.cvd [100%]
daily.cvd updated (version: 23836, sigs: 1743021, f-level: 63, builder: neo)
WARNING: getfile: bytecode.cvd not found on db.local.clamav.net (IP: 130.59.113.36)
WARNING: Can't download bytecode.cvd from db.local.clamav.net
Trying again in 5 secs...
ClamAV update process started at Fri Sep 15 19:06:39 2017
main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
daily.cvd is up to date (version: 23836, sigs: 1743021, f-level: 63, builder: neo)
Trying host db.local.clamav.net (193.1.193.64)...
WARNING: getfile: bytecode.cvd not found on db.local.clamav.net (IP: 193.1.193.64)
WARNING: Can't download bytecode.cvd from db.local.clamav.net
Trying again in 5 secs...
ClamAV update process started at Fri Sep 15 19:06:48 2017
main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
daily.cvd is up to date (version: 23836, sigs: 1743021, f-level: 63, builder: neo)
WARNING: Can't download bytecode.cvd from db.local.clamav.net
Trying again in 5 secs...
ClamAV update process started at Fri Sep 15 19:06:53 2017
main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
daily.cvd is up to date (version: 23836, sigs: 1743021, f-level: 63, builder: neo)
WARNING: Can't download bytecode.cvd from db.local.clamav.net
Trying again in 5 secs...
ClamAV update process started at Fri Sep 15 19:06:59 2017
main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
daily.cvd is up to date (version: 23836, sigs: 1743021, f-level: 63, builder: neo)
ERROR: Can't download bytecode.cvd from db.local.clamav.net
Giving up on db.local.clamav.net...
ClamAV update process started at Fri Sep 15 19:06:59 2017
main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
daily.cvd is up to date (version: 23836, sigs: 1743021, f-level: 63, builder: neo)
ERROR: Can't download bytecode.cvd from database.clamav.net
Giving up on database.clamav.net...
Update failed. Your network may be down or none of the mirrors listed in /etc/clamav/freshclam.conf is working. Check http://www.clamav.net/doc/mirrors-faq.html for possible reasons.
ERROR: Service 'mail' failed to build: The command '/bin/sh -c echo "0 0,6,12,18 * * * /usr/bin/freshclam --quiet" > /etc/cron.d/freshclam &&   chmod 644 /etc/clamav/freshclam.conf &&   freshclam &&   sed -i 's/Foreground false/Foreground true/g' /etc/clamav/clamd.conf &&   sed -i 's/AllowSupplementaryGroups false/AllowSupplementaryGroups true/g' /etc/clamav/clamd.conf &&   mkdir /var/run/clamav &&   chown -R clamav:root /var/run/clamav' returned a non-zero code: 52
```

**Comment by johansmitsnl** [comment] 2017-09-17 06:58
There is something wrong with your docker set-up. Not sure what or why.
You can see that the fix is buildable and works: https://travis-ci.org/tomav/docker-mailserver/builds/276441458?utm_source=github_status&utm_medium=notification

I have merged the change and it is building.

**Closed** 2017-09-17 06:58 UTC
Labels: bug
