### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by Rubytastic2** [tomav/docker-mailserver#407] opened 2016-12-19 11:55 UTC
Loving this project but abandoned docker to many issues on OSX 
Is there any interest in coverting this project to kubernetes or add support for it?

Im currently looking at this,
perhaps its an idea to make this project "hybrid"

**Comment by tomav** [comment] 2016-12-19 13:31
Hi, @Rubytastic2 
I think @tyranron and @keslerm are using Kubernetes.

**Comment by tomav** [comment] 2016-12-19 13:33
@iMartyn too

**Comment by iMartyn** [comment] 2016-12-19 14:25
I switched to https://github.com/Mailu/Mailu fwiw

**Comment by tyranron** [comment] 2016-12-19 20:14
@Rubytastic2 and what is the problem to use this image in Kubernetes?

Just write a `Deployment` & `ConfigMap`s you require and that's it.

**Comment by tomav** [comment] 2016-12-19 22:44
@tyranron is there a value to maintain a page in the wiki for Kubernetes users? If yes, could you do that? Thanks.

**Comment by iMartyn** [comment] 2016-12-19 22:54
[deploy.yml.txt](https://github.com/tomav/docker-mailserver/files/662351/deploy.yml.txt)
[service.yml.txt](https://github.com/tomav/docker-mailserver/files/662352/service.yml.txt)
fwiw these are what I used to set it up in a single-node cluster (so no need for shared storage).  Note that the deployment is set up to my dockerhub image because the original dev hasn't merged my pull request to add the hostname override.

**Comment by tyranron** [comment] 2016-12-20 06:27
@tomav yes, we can help people with that page, because there are some some tips which are not obvious enough. Like `v1.PodSpec.subdomain` usage, or placing `docker-mailserver` beyond reverse-proxies (which requires proxy protocol enabling).  
I can do that but cannot guarantee doing it fast.

Also, +1 for merging #390 of @iMartyn .

**Comment by tomav** [comment] 2016-12-20 07:35
@tyranron thanks, this page will be helpful.
Regarding @iMartyn PR, I'll merge as soon as he resolves the conflict. No problem.
Do not hesitate to review other's PR on topics that are important for you.

**Comment by iMartyn** [comment] 2016-12-20 10:32
Unfortunately my patch was before the script was effectively rewritten.  I'm not going to have time to refactor it so completely.  Hopefully it will serve as inspiration to someone else but as I'm not using this any more, my time is limited to work on it.

**Comment by scottstensland** [comment] 2016-12-21 17:14
I have this repo running inside Docker using kubernetes to run on Amazon AWS 
and am keen to pitch in to help others reach this possibility ... however my pressing concern
is to port onto ubuntu 16.04 ... not to jackknife this post but can someone point me to
current state of affairs on any ongoing port to 16.04 ?  If not I will share my progress on that port

**Comment by tomav** [comment] 2016-12-21 17:26
Hi @scottstensland, thanks for your help on Kubernetes. It could be usefull to have a Wiki page on that topic for docker-mailserver.
Regarding `16.04`, we can probably upgrade without major issue. Want to contribute on that point?

**Comment by tyranron** [comment] 2017-01-09 13:04
@tomav I played recently a bit more with latest (`2.1`) image version and Kubernetes and finally stuck in situation that cannot run this image version at all. The problem is in hostname detection.

If I specify in PodSpec data like:
```yaml
subdomain: server
hostname: docker
```
The result is
```
/ # hostname
docker
/ # hostname -f
docker.server.mail.svc.cluster.local
/ # hostname -d
server.mail.svc.cluster.local
```
So image does not run as it [requires dot](https://github.com/tomav/docker-mailserver/blob/2.1/target/start-mailserver.sh#L300) in results of `hostname` command.

And I am unable to specify `subdomain` or `hostname` in PodSpec too, because Kubernetes requires `[a-z0-9]([-a-z0-9]*[a-z0-9])` matching:
```
The Deployment "server" is invalid: spec.template.spec.hostname: Invalid value: "main.docker": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or '123-abc')
```

1) The simplest way to resolve this is to use `$(hostname -f)` instead of `$(hostname)` in `start-mailserver.sh`. But I don't know if it will be correct for rest part of configuration. May it be okay?

2) The longer way is to complete #390, which requires detailed testing of each service inside image and may result in configuration complication (as far as many configurations uses `hostname` command result implicitly and by default).

**Comment by tomav** [comment] 2017-01-09 13:08
Hi @tyranron, thanks for the test. The option 1 will be OK if you want to submit a patch (it won't break test I think)

**Comment by styxlab** [comment] 2017-01-18 19:41
Thanks for this project and for providing some support for Kubernetes. I'm currently running docker-mailserver on Kubernetes but had to use the image provided by @iMartyn in order to get it working. So, I'd love to see the changes of #390 incorporated into the official project.

I think that you should consider option 2. (#390) more seriously. The hostname is not well suited for Kubernetes and for a clustered environment in general. The Kubernetes way of accessing endpoints is always through a DNS routable name which is most easily done through environment variables. Using the subdomain/hostname properties are more a workaround than a clever solution. 

Going for option 2 will save you a lot of headaches in the long run. Just search some of the "hostname" discussions on Kubernetes, if you are not convinced.

**Comment by tyranron** [comment] 2017-01-18 20:25
@styxlab just use `subdomain` without `hostname`. It will make `hostname -f` command to return Pod's FQDN and that FQDN won't be static (as we don't specify `hostname`). No headache.

It's okay to have option 2 as it allows to specify domain you want (like `mail.example.com`) in mail headers, as currently Pod's FQDN is used there. But this is not something critical.

There are some major problems like placing docker-mailserver behind ingress controllers. This requires PROXY protocol usage between ingress controller and docker-mailserver to preserve real clients IPs. [Postfix works okay with HAProxy](http://www.postfix.org/postconf.5.html#smtpd_upstream_proxy_protocol), however there aren't proper HAProxy ingress controller. For Nginx ingres controller things can be more complicate.  
Currently working on it.

**Comment by styxlab** [comment] 2017-01-18 21:46
I have the standard nginx ingress controller running in front of docker-mailsever without any issues, so I do not understand the problem - at least if you have the option of setting the hostname with env variables. As stated before, I'm using @iMartyn 's image where I can use the env variable  OVERRIDE_HOSTNAME=mail.example.com.

**Comment by tomav** [comment] 2017-01-18 21:54
@tyranron could you create a Wiki page regarding Kubernetes when you have time?

@styxlab no problem to merge @iMartyn's PR if:
- really needed 
- conflicts resolved
Feel free to contribute

I just reopened https://github.com/tomav/docker-mailserver/pull/390

**Comment by tyranron** [comment] 2017-01-19 06:07
@styxlab did you check what client IPs you receive in docker-mailserver logs?

@tomav sure, it's on my TODO list. I didn't forget about it.

**Comment by styxlab** [comment] 2017-01-19 09:34
@tyranron I'm seeing only cluster IPs in docker-mailserver logs, not external IPs. I think this is a limitation of Kubernetes nginx ingress controller. Currently, external IP forwarding only works on http/https endpoints.

**Comment by iMartyn** [comment] 2017-01-19 11:31
The reason I'm not going to do this is it was a really simple pull request before the script was majorly refactored.
If it were a simple "resolve conflicts" request, I would, but I don't have the time on a project I don't use any more to understand all the changes that were made to that script.
In my not-so-humble opinion, the person who re-wrote the script should be able to trivially add this by looking at my actual change, otherwise it's gonna be a from-scratch effort by the next person.

**Comment by styxlab** [comment] 2017-01-19 11:47
Isn't #484 the solution we are looking forward to?

**Comment by tomav** [comment] 2017-01-19 12:13
@iMartyn yep, and I'm this person who rewrote the startup script but had not time/usage of that (especially to fill in a lack of kubernetes stack). moreover, the point was not clear when some users like @tyranron make it work on Kubernetes. 

Now, if there's a real need for that part of code, as I said ealier in this thread, I'm open to integrate it has soon conflict is resolved, and test added as mentioned in [contribution guidelines](https://github.com/tomav/docker-mailserver/blob/master/CONTRIBUTING.md). This was missing in your PR.

Thanks to @kcrawley, @iMartyn's PR will be merged soon (I already commented this PR this morning).

**Comment by tyranron** [comment] 2017-01-19 13:30
@styxlab 

> I'm seeing only cluster IPs in docker-mailserver logs

Yup. That's exactly the issue I was referring to. It's not limitation of Kubernetes ingress controller, it's rather lack of required options. This can happen in any environment when you place Postfix behind reverse-proxy, not only Kubernetes. It can be solved via using PROXY protocol.

**Comment by tomav** [comment] 2017-01-19 13:32
@tyranron if you have a feedback to provide regarding #484, do not hesitate

**Comment by webeindustry** [comment] 2017-04-01 00:07
I concatenated @iMartyn yaml & the deployment + service is created; however I have no clue where to go from here to test/configure this properly. Can someone help me through this? I have 5 heavy bare-metal servers on a custom pacemaker/kubernetes getup & need mail ASAP. I can drop a few bones for the efforts.

**Comment by scottstensland** [comment] 2017-04-01 13:22
@webeindustry  shoot me an email   ... I have a send email only container running on AWS using kubernetes ... scottstensland@gmail.com

**Comment by tyranron** [comment] 2017-04-01 14:13
@webeindustry 

To test it you just need to assure that following common scenarios run well:
- You can connect from local MUA (Mail User Agent) to your server via IMAP (and POP3 if you require).
- You can sent emails from local MUA via SMTP (on authorization port 587).
- Server is able to receive emails on 25 port.

To configure it you should mount into container all required configuration files using Kubernetes `ConfigMap`s and `Secret`s. And specify desired env vars in `Deployment` spec.

There is no much difference in using this image inside/outside Kubernetes. The steps you perform to get up this image with Docker Compose are just same to get up this image in Kubernetes. And instead of regular files Kubernetes abstractions are used (`ConfigMap`s, `Secrets`, etc).

The only major concept to understand is how you are [exposing your mailserver outside the cluster](https://kubernetes.io/docs/user-guide/services/#publishing-services---service-types). There are some ways, not only one.
The way provided by @iMartyn is to [bind mailserver `Service` to concrete external IP](https://kubernetes.io/docs/user-guide/services/#external-ips).
But this can be done also with:
- using [Port Proxy](https://github.com/kubernetes/contrib/tree/master/for-demos/proxy-to-service)
- direct binding `Pod` to concrete `Node` and using `hostNetwork: true`
- using `Ingress`es and Ingress Controllers (like [Nginx](https://github.com/kubernetes/ingress/tree/master/controllers/nginx))

Image configuration depends on what way for exposing you choose.

**Comment by webeindustry** [comment] 2017-04-01 17:32
Think I'm getting closer :) Thanks for the replies so far!

I am so far using @iMartyn repo, is this necessary or should I move to this main repo for improvements? I don't know much about configmaps or secrets yet, they seem to be "the kube way" but not necessary. This is my current YAML. Does this appear in order? 

[https://pastebin.com/ztfeTWWR](url)

**Comment by webeindustry** [comment] 2017-04-02 02:07
I looked through the logs it looks like there's some errors occurring. 

https://pastebin.com/aLjY0eUL

& 
`Apr  2 01:22:27 mail dovecot: master: Error: socket() failed: Address family not supported by protocol
Apr  2 01:22:27 mail dovecot: master: Error: service(imap-login): listen(::, 143) failed: Address family not supported by protocol
Apr  2 01:22:27 mail dovecot: master: Error: socket() failed: Address family not supported by protocol
Apr  2 01:22:27 mail dovecot: master: Error: service(imap-login): listen(::, 993) failed: Address family not supported by protocol
Apr  2 01:22:27 mail dovecot: master: Fatal: Failed to start listeners
Apr  2 01:31:34 mail postfix/smtpd[1327]: fatal: no SASL authentication mechanisms
Apr  2 01:32:35 mail postfix/smtpd[1330]: fatal: no SASL authentication mechanisms
Apr  2 01:33:36 mail postfix/smtpd[1331]: fatal: no SASL authentication mechanisms
Apr  2 01:53:56 mail postfix/smtpd[1474]: fatal: no SASL authentication mechanisms
Apr  2 01:54:57 mail postfix/smtpd[1477]: fatal: no SASL authentication mechanisms
Apr  2 01:55:58 mail postfix/smtpd[1478]: fatal: no SASL authentication mechanisms
Apr  2 01:56:59 mail postfix/smtpd[1479]: fatal: no SASL authentication mechanisms
Apr  2 01:58:00 mail postfix/smtpd[1514]: fatal: no SASL authentication mechanisms
Apr  2 02:03:36 mail postfix/smtpd[1586]: fatal: no SASL authentication mechanisms
Apr  2 02:04:37 mail postfix/smtpd[1589]: fatal: no SASL authentication mechanisms
Apr  2 02:05:38 mail postfix/smtpd[1591]: fatal: no SASL authentication mechanisms
Apr  2 02:06:39 mail postfix/smtpd[1592]: fatal: no SASL authentication mechanisms
`

**Comment by tomav** [comment] 2017-04-04 07:30
@webeindustry do you see something in the logs?
If yes, it will be a good lead to find the answer. Otherwise, you probably don't reach the server.

**Comment by webeindustry** [comment] 2017-04-04 15:48
@tomav Hi @tyranron Helped me sort this out. There were more than a couple of things that needed reworking, but we got it settled.

**Comment by kachkaev** [comment] 2017-05-19 11:53
Hi guys,

Just curious: would anyone be interested in summarizing their experience of using this project in a Kubernetes cluster in a form of a blog post or a wiki page? I've been enjoying using docker-mailserver for about a year now, but am looking into upgrading my environment to k8s at some point. Pretty sure I'm not alone among 1.5K github stargazers! :–)

**Comment by tomav** [comment] 2017-05-20 13:47
A Wiki page would be perfect. @tyranron @webeindustry ?

**Comment by tomav** [comment] 2017-06-26 19:24
Hi guys, anybody has 10min to explain how things work with Kubernetes? Thanks

**Comment by tyranron** [comment] 2017-06-27 19:27
@tomav I've written some wiki doc recently, but I'm unable to push it. Would you be so kind to add me to project collaborators temporary?

**Comment by tomav** [comment] 2017-06-28 11:33
Done! Thanks @tyranron

**Comment by tyranron** [comment] 2017-06-28 14:55
@tomav done! [Here it is](https://github.com/tomav/docker-mailserver/wiki/Using-in-Kubernetes). I hope that information will help someone.

It's sad, but I don't see "just deploy and use" solution for Kubernetes. Things hardly depends on concrete cluster configuration and constructing Helm chart for mailserver is a huge pain.

**Comment by tomav** [comment] 2017-06-28 14:56
Thanks @tyranron!

**Closed by tomav** 2017-06-28 14:56 UTC
Labels: documentation

**Comment by kachkaev** [comment] 2017-06-28 15:24
This is terrific, thanks @tyranron!

Would you be interested in making your recipe [an official helm chart](https://github.com/kubernetes/charts) to turn `docker-mailserve` into a one-liner on any k8s cluster? That would just rock!

I have quite little experience with help and k8s as such, but after installing wordpress and a couple of other things with helm, I can't imagine any better setup workflow!

**Comment by tyranron** [comment] 2017-06-28 18:44
@kachkaev Helm chart is a great idea, but as I referred above (and in wiki page) is non-trivial and requires decisions that come in price. 
What exact way of exposing mailserver should we use, and why?

The problem is not about Helm, but more about Kubernetes ecosystem nowadays. Exposing HTTP services in HA, manageable and scalable manner in Kubernetes is easy, while TCP/UDP services is not.

**Comment by kachkaev** [comment] 2017-06-28 19:18
I guess it's technically possible to make a chart so that it includes all options, one of which being default and others being available by tweaking the configuration. All the yamls you've nicely crafted would be included at once, just having something like `{{- if eq .Values.mode  "option_1" -}}...{{- end }}` in various places (like [in minio](https://github.com/kubernetes/charts/blob/0b1692af04f1b1d22fa1c21e42823c38e160f79b/stable/minio/templates/minio_pvc.yaml) or other charts).

Instead of following the instructions by hand, people would just be able to wave a magic wand after providing helm a couple of settings and that's it :–) The docs will not harder as [README.md for wordpress](https://github.com/kubernetes/charts/tree/master/stable/wordpress).

It's probable that k8s will implement something cool for dealing with TCP traffic in future and then it'll be just a matter of changing the default mode in the chart. Your chart might be already used by many by that time already, because a mailserver is one of the most common services that people want to have on top of the standard web stuff.

**Comment by iMartyn** [comment] 2017-06-28 20:48
Whilst I'm not active in this project, there are a couple of things to add
to this thread, that others may want to pick up :

K8SNIff is a TLS TCP SNI ingress, so it can indeed do the tcp HA is
possible.  I'd always use traefik in front of the web interfaces and I
wrote a little container to pull the certs from it into the imap server of
my setup (I like mail.mydomain not imap.mydomain and webmail.mydomain).

Another project to look at is linkerd-tcp which is also a TCP ingress from
the great folks at linkerd.

**Comment by tyranron** [comment] 2017-06-29 18:34
@iMartyn thank you for pointing to that projects. They really rock! However, looking through I didn't found mention about PROXY protocol implemented. This one is required to preserve real client IP for incoming mails SPF checks actually to work.  
Can you share how is problem with SPF checks is solved on your side?

**Comment by yuanying** [comment] 2017-09-13 08:35
Hi, Just a question.

I deployed this docker-mailserver on kubernetes behind haproxy which sends proxy-protocol.
But seems amavis failed to send email to smtpd.
Please see following log messages.

> Sep  7 05:53:59 mailserver postfix/smtpd[1062]: warning: haproxy read: unexpected EOF

I guess [127.0.0.1:10025](https://github.com/tomav/docker-mailserver/blob/master/target/postfix/master.cf#L101) expect to receive proxy protocol but amavis  didn't send.

So Is there any official way to configure master.cf file after docker-mailserver is deployed?

Thanks.

### Full Log

```
Sep  7 05:53:20 mailserver postfix/smtpd[1053]: connect from st41p57im-ztfb14240501.us.com[17.36.64.138]
Sep  7 05:53:21 mailserver postfix/smtpd[1053]: C991582EA6D697E4B6C12: client=st41p57im-ztfb14240501.us.com[17.36.64.138]
Sep  7 05:53:22 mailserver postfix/cleanup[1058]: C991582EA6D697E4B6C12: message-id=<DCEE9524-F30F-4439-B242-0092ED176612@us.com>
Sep  7 05:53:22 mailserver opendkim[184]: C991582EA6D697E4B6C12: st41p57im-ztfb14240501.us.com [17.36.64.138] not internal
Sep  7 05:53:22 mailserver opendkim[184]: C991582EA6D697E4B6C12: not authenticated
Sep  7 05:53:22 mailserver opendkim[184]: C991582EA6D697E4B6C12: DKIM verification successful
Sep  7 05:53:22 mailserver opendkim[184]: C991582EA6D697E4B6C12: s=04042017 d=us.com SSL
Sep  7 05:53:22 mailserver opendmarc[196]: implicit authentication service: mail.lazy.work
Sep  7 05:53:22 mailserver opendmarc[196]: C991582EA6D697E4B6C12: us.com pass
Sep  7 05:53:22 mailserver postfix/qmgr[1033]: C991582EA6D697E4B6C12: from=<user01@us.com>, size=2180, nrcpt=1 (queue active)
Sep  7 05:53:23 mailserver postfix/smtpd[1053]: disconnect from st41p57im-ztfb14240501.us.com[17.36.64.138] ehlo=2 starttls=1 mail=1 rcpt=1 data=1 quit=1 commands=7
Sep  7 05:53:59 mailserver amavis[1045]: (01045-01) (!)rw_loop: leaving rw loop, no progress, last event (select) 35.011 s ago
Sep  7 05:53:59 mailserver postfix/smtpd[1062]: warning: haproxy read: unexpected EOF
Sep  7 05:53:59 mailserver postfix/smtpd[1062]: connect from unknown[unknown]
Sep  7 05:53:59 mailserver postfix/smtpd[1062]: disconnect from unknown[unknown] commands=0/0
Sep  7 05:53:59 mailserver amavis[1045]: (01045-01) (!)O440fHx7_I21 FWD from <user01@us.com> -> <user02@lazy.work>,  451 4.5.0 From MTA() during fwd-connect (No greeting, dt: 35.012 s): id=01045-01
Sep  7 05:53:59 mailserver amavis[1045]: (01045-01) Blocked MTA-BLOCKED {TempFailedInbound}, [17.36.64.138]:36637 [17.36.64.138] <user01@us.com> -> <user02@lazy.work>, Queue-ID: C991582EA6D697E4B6C12, Message-ID: <DCEE9524-F30F-4439-B242-0092ED176612@us.com>, mail_id: O440fHx7_I21, Hits: -0.322, size: 2367, dkim_sd=04042017:us.com, 37021 ms
Sep  7 05:53:59 mailserver postfix/smtp[1034]: C991582EA6D697E4B6C12: to=<user02@lazy.work>, relay=127.0.0.1[127.0.0.1]:10024, delay=39, delays=1.6/0.01/0.01/37, dsn=4.5.0, status=deferred (host 127.0.0.1[127.0.0.1] said: 451 4.5.0 id=01045-01 - Temporary MTA failure on relaying, From MTA() during fwd-connect (No greeting, dt: 35.012 s): id=01045-01 (in reply to end of DATA command))
```

### ConfigMap I used

* https://github.com/yuanying/k8s-env/blob/master/charts/mailserver/templates/configmaps.yaml#L23-L35
