### ISSUE TITLE
Test email add and login randomly fails

### ISSUE THREAD

**Issue by erik-wramner** [tomav/docker-mailserver#1264] opened 2019-09-16 09:27 UTC
One test still fails randomly:

```

not ok 164 checking setup.sh: setup.sh email add and login

# (from function `assert_output' in file test/test_helper/bats-assert/src/assert.bash, line 239,
#  in test file test/tests.bats, line 1185)
#   `assert_output "passdb: setup_email_add@example.com auth succeeded"' failed
# 
# -- output differs --
# expected : passdb: setup_email_add@example.com auth succeeded
# actual   : passdb: setup_email_add@example.com auth failed
# --
# 
```

**Comment by erik-wramner** [comment] 2019-09-17 18:17
@martin-schulze-vireso if you can think of something we can add to get more details when it happens that would be great. I've already tried waiting for the change detector but sometimes it still fails.

**Comment by martin-schulze-vireso** [comment] 2019-09-17 20:45
Hm that one is really weird. I tried to reproduce it locally. However, I get another setup test that fails and this results in the mail container terminating. Unfortunately, the `--rm` discarded the container, so I don't know what is going on. Rerunning now...

**Comment by martin-schulze-vireso** [comment] 2019-09-17 21:32
Okay, for me the "checking setup.sh: setup.sh debug fetchmail" test fails. The `docker logs` output ends in:
```
Sep 17 21:07:30 mail opendkim[217]: OpenDKIM Filter: mi_stop=1
Sep 17 21:07:30 mail opendkim[217]: OpenDKIM Filter v2.11.0 terminating with status 0, errno = 0
2019-09-17 21:07:30,268 INFO exited: opendkim (exit status 0; expected)
2019-09-17 21:07:31,271 INFO spawned: 'opendkim' with pid 10569
Sep 17 21:07:31 mail opendkim[10570]: OpenDKIM Filter v2.11.0 starting (args: -f)
2019-09-17 21:07:31,292 INFO success: opendkim entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Sep 17 21:07:45 mail opendmarc[223]: OpenDMARC Filter: mi_stop=1
Sep 17 21:07:45 mail opendmarc[223]: OpenDMARC Filter v1.3.2 terminating with status 0, errno = 0
2019-09-17 21:07:45,279 INFO exited: opendmarc (exit status 0; expected)
2019-09-17 21:07:46,282 INFO spawned: 'opendmarc' with pid 10637
Sep 17 21:07:46 mail opendmarc[10637]: OpenDMARC Filter v1.3.2 starting (args: -f -p inet:8893@localhost -P /var/run/opendmarc/opendmarc.pid)
Sep 17 21:07:46 mail opendmarc[10637]: additional trusted authentication services: mail.my-domain.com
2019-09-17 21:07:46,289 INFO success: opendmarc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2019-09-17 21:08:23,735 WARN received SIGTERM indicating exit request
2019-09-17 21:08:23,735 INFO waiting for rsyslog, postfix, clamav, cron, amavis, changedetector, opendkim, opendmarc, dovecot, mailserver to die
2019-09-17 21:08:23,736 INFO stopped: mailserver (terminated by SIGTERM)
2019-09-17 21:08:24,751 INFO reaped unknown pid 477
2019-09-17 21:08:25,802 INFO stopped: dovecot (exit status 0)
2019-09-17 21:08:25,802 INFO reaped unknown pid 212
2019-09-17 21:08:26,322 INFO stopped: opendmarc (exit status 0)
2019-09-17 21:08:26,337 INFO stopped: opendkim (exit status 0)
2019-09-17 21:08:27,339 INFO waiting for rsyslog, postfix, clamav, cron, amavis, changedetector to die
2019-09-17 21:08:28,341 INFO stopped: changedetector (terminated by SIGTERM)
2019-09-17 21:08:28,391 INFO stopped: amavis (exit status 0)
2019-09-17 21:08:28,392 INFO stopped: cron (terminated by SIGTERM)
2019-09-17 21:08:28,443 INFO reaped unknown pid 10520
2019-09-17 21:08:28,469 INFO reaped unknown pid 10519
2019-09-17 21:08:29,266 INFO stopped: clamav (exit status 0)
2019-09-17 21:08:29,278 INFO reaped unknown pid 10795
2019-09-17 21:08:31,281 INFO waiting for rsyslog, postfix to die
2019-09-17 21:08:31,523 INFO reaped unknown pid 10422
2019-09-17 21:08:31,523 INFO reaped unknown pid 10424
2019-09-17 21:08:31,523 INFO reaped unknown pid 10425
2019-09-17 21:08:31,529 INFO stopped: postfix (exit status 0)
2019-09-17 21:08:31,530 INFO stopped: rsyslog (exit status 0)
```
Looks as if the service was stopped by SIGTERM which sounds like a planned stop.

**Comment by martin-schulze-vireso** [comment] 2019-10-04 21:22
I am still trying to reproduce this locally but I get about 7 errors per run, mostly on DKIM related tests. Do you see this as well?

**Comment by erik-wramner** [comment] 2019-10-06 09:21
No, most of the times the local runs are successful now. When they do fail it is typically on one of the login tests, either this one or the one with the preexisting account.

**Comment by martin-schulze-vireso** [comment] 2019-10-06 10:07
Could you give a shell script representation of your steps for local runs? Maybe I am doing something  wrong. I already noticed that I forgot `sudo` sometimes which makes test cleanup fail because some files are written via docker volumes without write rights for my user.

**Comment by erik-wramner** [comment] 2019-10-06 10:42
Nothing complex at all, I just run "make" in bash. If there are errors I "make clean" before next run. I get prompted for a password at the cleanup step to delete left-over files, which feels a bit dirty. Perhaps we could do that better.

**Comment by aendeavor** [comment] 2020-09-23 21:17
This is a duplicate of #1459

**Closed** 2020-09-23 21:17 UTC
Labels: bug, duplicate, priority 2 [MEDIUM], test related
