### ISSUE TITLE
Error: The directory named as part of the path /var/log/supervisor/supervisord.log does not exist.

### ISSUE THREAD

**Issue by Yajo** [tomav/docker-mailserver#1352] opened 2020-01-03 13:20 UTC
## Context

Just starting the server.

## Expected Behavior

Boot.

## Actual Behavior

Doesn't boot. Logs this repeatedly:

```
Error: The directory named as part of the path /var/log/supervisor/supervisord.log does not exist.
For help, use /usr/bin/supervisord -h
```

## Possible Fix

Add `-v maillogssupervisor:/var/log/supervisor:z` to `docker container run` command. Well, this is a workaround; the fix should be doing `mkdir -p /var/log/supervisor` in the entrypoint.

## Steps to Reproduce

1. Start server.

## Your Environment

* Amount of RAM available: 64GiB
* Mailserver version used: v6.1.0-204-gf69d30f
* Docker version used: 18.09.6
* Environment settings relevant to the config: 

```yaml
# docker-compose.yml, with only interesting things
  smtp:
    cap_add:
    - SYS_PTRACE
    domainname: eurosas.net
    environment:
      DEFAULT_RELAY_HOST: '[smtp.gmail.com]:587'
      DMS_DEBUG: 0
      ENABLE_SRS: 1
      ONE_DIR: 1
      PERMIT_DOCKER: connected-networks
      POSTFIX_MESSAGE_SIZE_LIMIT: 52428800
      RELAY_HOST: smtp.gmail.com
      RELAY_PASSWORD: *********
      RELAY_PORT: '587'
      RELAY_USER: **********
      SMTP_ONLY: 1
      SRS_DOMAINNAME: **********
      SRS_EXCLUDE_DOMAINS: **********
      SRS_SENDER_CLASSES: envelope_sender,header_sender
    image: tvial/docker-mailserver:latest
    networks:
      default:
        aliases:
        - smtplocal
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
    - mailconfig:/tmp/docker-mailserver:z
    - maillogs:/var/log/mail:z
    - maildata:/var/mail:z
    - mailstate:/var/mail-state:z
```

* Any relevant stack traces ("Full trace" preferred):
See above.

**Comment by erik-wramner** [comment] 2020-01-03 17:58
Hm, this should work. I'll have to see if I can reproduce it.

**Comment by erik-wramner** [comment] 2020-01-04 15:58
I think this is an old bug. You write that it is v6.1.0-204-gf69d30f and I'm pretty sure we fixed it since then. Can you reproduce with 6.2.1 or stable or latest?

**Comment by Yajo** [comment] 2020-01-07 12:53
Actually, v6.1.0-204-gf69d30f is latest: https://hub.docker.com/layers/tvial/docker-mailserver/latest/images/sha256-d03109746ae32c2a678c526b2db45e8d0f001ae60f41c2571227bc5bd566da88

Anyway, I cannot reproduce now, not even deleting and recreating the volumes... I don't know what happened :confused:

**Comment by erik-wramner** [comment] 2020-01-07 20:28
@fbartels how do we change VCS_VERSION to make it report 6.2.1 instead of 6.1.0? It is obtained with `git describe` but I don't know how to change it.

@Yajo in that case I suggest closing and feel free to reopen if it happens again?

**Closed** 2020-01-08 09:35 UTC
Labels: bug, waiting for contributor action

**Comment by fbartels** [comment] 2020-01-11 22:30
Hi @erik-wramner,

sorry just saw this now. describe only works with annotated tags, more information at https://stackoverflow.com/a/4154518.
