### ISSUE TITLE
can't send email via ssl

### ISSUE THREAD

**Issue by epubreader** [tomav/docker-mailserver#614] opened 2017-05-24 14:08 UTC
it is ok when send email with port 25,
but when I switch to the port 587, it failed, 

https://github.com/tomav/docker-mailserver/wiki/Configure-SSL

I use docker-compse
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    - ./mail/letsencrypt/etc:/etc/letsencrypt
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    - SSL_TYPE=letsencrypt
    cap_add:
    - NET_ADMIN

the log from the server 

May 24 14:03:46 mail postfix/submission/smtpd[1467]: connect from unknown[183.11.37.2]
May 24 14:03:48 mail postfix/submission/smtpd[1467]: lost connection after UNKNOWN from unknown[183.11.37.2]
May 24 14:03:48 mail postfix/submission/smtpd[1467]: disconnect from unknown[183.11.37.2] unknown=0/1 commands=0/1
May 24 14:04:02 mail postfix/submission/smtpd[1467]: warning: hostname 247.221.18.218.broad.sz.gd.dynamic.163data.com.cn does not resolve to address 218.18.221.247: Name or service not known
May 24 14:04:02 mail postfix/submission/smtpd[1467]: connect from unknown[218.18.221.247]
May 24 14:04:03 mail postfix/submission/smtpd[1467]: lost connection after UNKNOWN from unknown[218.18.221.247]
May 24 14:04:03 mail postfix/submission/smtpd[1467]: disconnect from unknown[218.18.221.247] unknown=0/1 commands=0/1

**Comment by arneke** [comment] 2017-06-09 10:29
Port 465 (deprecated) was used for SSL (SMTP with SSL wrapper), port 587 is for STARTTLS.

This docker image does not currently support port 465. The logs may be consistent with a client that only supports SSL, not STARTTLS. In that case this issue is a duplicate of #618.

https://www.fastmail.com/help/technical/ssltlsstarttls.html

**Closed** 2017-10-04 15:42 UTC
Labels: question
