### ISSUE TITLE
Docker-Image on Dockerhub should only be built when tests succeed

### ISSUE THREAD

**Issue by danielpanteleit** [tomav/docker-mailserver#666] opened 2017-07-23 11:11 UTC
To prevent mistakes, there should be a mechanism in place so that only a commit with a passed travis build should be updated on Dockerhub.

Not sure how to set this up, though. I guess there could be some kind of travis hook to push the master branch to a publish branch and configure dockerhub to build the publish branch to the tag "latest".

This is just an idea though. I just wondered why there is a new image version even though the lastest travis build failed.

**Comment by gegere** [comment] 2017-07-23 16:13
@danielpanteleit this is definitely possible. There might be another CI service to use in the build process. Many have advantages over the over.

Have a look at the following, within a .circleci folder to the 2.0 configuration there can be a specific branch used for push successful builds.

https://circleci.com/docs/2.0/custom-images/

**Comment by tomav** [comment] 2017-07-23 17:47
Hi @danielpanteleit, nothing is merged into master if tests are not green.
Tests are not 100% stable and that's the main issue.
Anyway, I'm open to discussion / ideas on that topic

**Comment by danielpanteleit** [comment] 2017-07-23 20:24
@tomav OK, I didn't know that.

Yes, the main issue are the flaky tests. Debugging those are rather hard (setup and mail sending is done in make and the results are checked in bats). I think that bats may be at it's limit there. I think we need a proper test framework that supports file/class setup and teardown, proper error messages and debug output. I would propose Python for that. I can write some sample tests if you are not totally against the idea.

**Comment by johansmitsnl** [comment] 2017-09-08 17:13
A merge request could be tested successful but it is not always forked from the master. So a merge could not have conflicts it could break tests when merged into master.
Let travis trigger the hub build on success could prevent these errors.

Anyone has knowledge on configuring these hooks?

**Comment by fbartels** [comment] 2019-08-05 19:48
Could be resolved by https://github.com/tomav/docker-mailserver/issues/1207#issuecomment-518128850

**Comment by aendeavor** [comment] 2020-09-21 13:19
This is more or less a duplicate of both #1207 and #1092 when it comes to updating the CI/CD progress.

**Closed by aendeavor** 2020-09-21 13:19 UTC
Labels: duplicate, enhancement, help wanted
