### ISSUE TITLE
dovecot keeps respawning

### ISSUE THREAD

**Issue by muesli** [tomav/docker-mailserver#1225] opened 2019-08-13 04:29 UTC
Since yesterday's commits dovecot keeps respawning infinitely, seemingly never succeeding to start up.

## Your Environment
* Amount of RAM available: 64GB
* Mailserver version used: latest from docker hub
* Docker version used: 18.03.1-ce

**Comment by fbartels** [comment] 2019-08-13 05:10
Caused by https://github.com/tomav/docker-mailserver/pull/1220

We did not take into account that existing configuration needs to be updated. Will have a look later.

**Comment by erik-wramner** [comment] 2019-08-13 05:29
Hopefully fixed in #1226, will merge as soon as the tests have passed.

**Comment by erik-wramner** [comment] 2019-08-13 05:51
This should be fixed in master now. We should add tests that ensure that all the services are working with ONE_DIR=1 as well. Apparently that is missing from the test suite.

**Closed** 2019-08-14 07:12 UTC
Labels: bug
