### ISSUE TITLE
Sudden amavis crashed

### ISSUE THREAD

**Issue by manuelgu** [tomav/docker-mailserver#697] opened 2017-08-16 20:17 UTC
Startup log: https://paste.md-5.net/koxixuruqo.coffee

After a few hours of uptime, `amavis` ends up in a never-ending restart-crash loop like shown [here](https://paste.md-5.net/wageceroti.vhdl)

**Comment by danielpanteleit** [comment] 2017-08-17 16:59
I can confirm this:

```
Aug 17 16:56:00 mail amavis[20575]: (!)Net::Server: 2017/08/17-16:56:00 Pid_file already exists for running process (259)... aborting\n\n  at line 144 in file /usr/share/perl5/Net/Server.pm
2017-08-17 16:56:00,104 INFO exited: amavis (exit status 1; not expected)
2017-08-17 16:56:00,125 INFO spawned: 'amavis' with pid 20589
2017-08-17 16:56:00,128 INFO success: amavis entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
```


This also happens to dovecot for me:

```
2017-08-17 16:55:59,701 INFO spawned: 'dovecot' with pid 20583
2017-08-17 16:55:59,731 INFO success: dovecot entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2017-08-17 16:55:59,732 INFO exited: dovecot (exit status 89; not expected)
Aug 17 16:55:59 mail dovecot: master: Fatal: Dovecot is already running with PID 188 (read from /var/run/dovecot/master.pid)
```

Both seem to use their own pid files. Both mentioned pids are not running.

**Comment by danielpanteleit** [comment] 2017-08-17 17:40
I think these are two separate problems:

amavis seems to quit on its own at one point and probably restarts itself somehow. Supervisor also starts a new amavis instance which will be killed and restarted all the time:

```
2017-08-14 07:09:28,320 INFO exited: amavis (exit status 0; expected)
2017-08-14 07:09:29,489 INFO spawned: 'amavis' with pid 18990
Aug 14 07:09:29 mail amavis[18981]: starting. /usr/sbin/amavisd-new at ... amavisd-new-2.10.1 (20141025), Unicode aware, LC_ALL="C"
2017-08-14 07:09:29,937 INFO success: amavis entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Aug 14 07:09:30 mail amavis[18990]: starting. /usr/sbin/amavisd-new at ... amavisd-new-2.10.1 (20141025), Unicode aware
...
Aug 14 07:09:30 mail amavis[18990]: (!)Net::Server: 2017/08/14-07:09:30 Pid_file already exists for running process (18997)... aborting\n\n  at line 144 in file /usr/share/perl5/Net/Server.pm
...
2017-08-14 07:09:30,942 INFO exited: amavis (exit status 1; not expected)
...
2017-08-14 07:09:30,946 INFO spawned: 'amavis' with pid 18998
```

The original amavis (18997) was still running at this point. I think we either don't use supervisor or we somehow tell amavis to stop restarting itself.

The dovecot problem arose after the host rebooted. The docker container restarted and the PID file was not cleaned which led to the restart loop. I guess removing the PID file in start-mailserver.sh should do the trick.

**Comment by johansmitsnl** [comment] 2017-08-18 18:09
I think it is the same issue as #686 
I just made a PR for amavis.
Dovecot is still unclear, you know how to reproduce it?

**Comment by johansmitsnl** [comment] 2017-08-19 08:49
PR got merged into master, can you all check if it fixes the issue?

**Comment by gutmensch** [comment] 2017-08-19 09:08
@johansmitsnl: Hmmm, pulled the new image and started but still seeing $INIT
```
root@stack /home/jazz # docker images -a
REPOSITORY                                         TAG                 IMAGE ID            CREATED             SIZE
tvial/docker-mailserver                            latest              80c05fa328b9        25 minutes ago      554.8 MB

root@stack /home/jazz # docker pull tvial/docker-mailserver
Using default tag: latest
latest: Pulling from tvial/docker-mailserver
Digest: sha256:2a88dddf8249a7e7231f38839901e0e0e89941d08ea68073c7da6a9bf18c982f
Status: Image is up to date for tvial/docker-mailserver:latest

root@mail:/# cat /etc/spamassassin/sa-update-hooks.d/amavisd-new
#!/bin/sh

#This scripts restarts amavisd-new after spamassassin
#rules got updated

NAME=amavisd-new
AMAVISPID=/var/run/amavis/amavisd.pid
INIT=/etc/init.d/amavis

# stolen from dhcpd3 initscript
# single arg is -v for messages, -q for none
check_status()
{
    if [ ! -r "$AMAVISPID" ]; then
        test "$1" != -v || echo "$NAME is not running."
        return 3
    fi
    if read pid < "$AMAVISPID" && ps -p "$pid" > /dev/null 2>&1; then
        test "$1" != -v || echo "$NAME is running."
        return 0
    else
        test "$1" != -v || echo "$NAME is not running but $AMAVISPID exists."
        return 1
    fi
}

#exit if amavis is not running
check_status || exit

$INIT restart > /dev/null
```
but maybe someone else can confirm, I'm using some automatism to upload also to my own registry and spawn from there (the image ids are however the same).

**Comment by johansmitsnl** [comment] 2017-08-19 09:16
Maybe it was still building or did you build your own from master?

**Comment by gutmensch** [comment] 2017-08-19 09:19
Ah sorry, of course - patience is a gift not all people have. ;-) Looks good now, thanks a lot @johansmitsnl!

**Comment by manuelgu** [comment] 2017-08-19 09:55
amavis appears to be fixed!

I can reproduce dovecot by stopping and starting the container again.
`docker-compose stop mail` `docker-compose start mail`

**Comment by johansmitsnl** [comment] 2017-08-19 11:14
@manuelgu Reproduced the issue to. A stop and start leaves the files inside docker in place. This causes the pid file to exist and a other process might be running on that pid number. So dovecot thinks it is already running but it isn't.
Added a PR #700 to clean stale pid files and prevent this from happening with other processes to.

**Comment by johansmitsnl** [comment] 2017-08-19 15:18
The PR is ready (builds pass) waiting for a review and merge

**Comment by tomav** [comment] 2017-08-24 16:09
Merged, `latest` is currently building.

**Comment by tomav** [comment] 2017-08-24 16:23
Image built. I let you pull it a confirm that everything is working as expected, ok?
Thank you.

**Comment by Fmstrat** [comment] 2017-08-28 15:38
Hrm, not sure this is fixing the issue. I'm seeing in this behavior:

```
mail                   | 2017-08-28 15:36:11,688 INFO success: dovecot entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
mail                   | 2017-08-28 15:36:11,690 INFO exited: dovecot (exit status 89; not expected)
mail                   | 2017-08-28 15:36:12,694 INFO spawned: 'dovecot' with pid 1274
mail                   | 2017-08-28 15:36:12,721 INFO success: dovecot entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
mail                   | 2017-08-28 15:36:12,723 INFO exited: dovecot (exit status 89; not expected)
mail                   | 2017-08-28 15:36:13,726 INFO spawned: 'dovecot' with pid 1276
mail                   | 2017-08-28 15:36:13,745 INFO success: dovecot entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
mail                   | 2017-08-28 15:36:13,747 INFO exited: dovecot (exit status 89; not expected)
mail                   | 2017-08-28 15:36:14,750 INFO spawned: 'dovecot' with pid 1280
mail                   | 2017-08-28 15:36:14,775 INFO success: dovecot entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
mail                   | 2017-08-28 15:36:14,776 INFO exited: dovecot (exit status 89; not expected)
```

But these are the existing PID files:

```
root@linode:/var/run# find . |grep .pid
./crond.pid
./rsyslogd.pid
./fail2ban/fail2ban.pid
./opendkim/opendkim.pid
./opendmarc/opendmarc.pid
./amavis/amavisd.pid
```

There is no Dovecot pid, and it just keeps repeating the dovecot error over and over. This is on a new install, with another system it's running fine.

**Comment by Fmstrat** [comment] 2017-08-29 13:58
I figured out my dovecot restart issue, it was just a dumb mistake for if this helps anyone else. I hadn't copied over the certificate files to the new server, so dovecot was crashing trying to access a file that wasn't there. So, if it helps anyone else, check that!

**Comment by johansmitsnl** [comment] 2017-09-05 20:21
This issue can be closed then?

**Comment by init-js** [comment] 2017-09-07 01:17
I don't think this issue is fixed.

I'm having a similar (or the exact same issue perhaps), where supervisord keeps trying to restart amavisd.

In my case, `/var/log/supervisor/amavis.log` is filled with the error:

> The amavisd daemon is already running, PID: [2391]

I've encountered this problem on two occasions.

In one previous occurrence of this problem, the PID mentioned in the log file was in use by another unrelated process (not amavisd, but I forget which exact one now). Amavisd wasn't running, but it refused to start because the pid file was present, and `kill -0 <pid>` succeeded (that's the simple check that amavis performs).

The most recent time it occurred, the pid (e.g. 2391) was already used by a running instance of amavisd. If amavisd is already running (i.e. if it has been started outside of supervisorctl), doing `supervisorctl stop amavis` leaves the pre-existing amavisd process running, and leaves `/var/run/amavis/amavisd.pid` running -- but `supervisorctl status` will report amavisd as stopped.

It seems to me that a process outside supervisord (re)starts/stops amavisd and it's confusing supervisorctl. The pidfile gets out of sync with what supervisorctl thinks the pid should be. I haven't tracked exactly what process does this. I suspect it's a cron job.

I get the feeling that configuring `/etc/supervisor/conf.d/supervisor-app.conf` to use the /etc/init.d/ tools, or rely on the /var/run/amavis/amavis.pid file might be more reliable than just `/usr/sbin/amavisd-new foreground`

Disclaimer: My postfix master.cf config file was slightly modified to run only one amavisd process instead of 2. I don't know whether this affects the longevity of the process in subtle ways with regards to pids lingering around longer.

**Comment by johansmitsnl** [comment] 2017-09-07 05:57
@init-js What you described is fixed in #699. Are you sure you run the latest master or did you build your own but not with these fixes?
They are all merged and I do not encounter these issues as you described.

**Comment by init-js** [comment] 2017-09-07 22:22
Ugh. I've somehow missed that issue.

My checkout is slightly behind, I've forked around 9e7959fafef48b0da620d0d04d0a547029785689 (Aug 7th 2017).

That looks exactly like it would fix the issue.

**Comment by johansmitsnl** [comment] 2017-09-08 06:39
Why did you fork it? Are there features that you miss?

**Comment by init-js** [comment] 2017-09-08 07:38
Good question. There were a few things I was missing, yes. Mostly because the image in master is very memory hungry for a 1GB VM (e.g. pi, or ec2 t2.micro), I wanted to experiment running the image with different tooling to keep memory usage down.

- minor: I needed to run tls_wrapper_mode on a different socket. that's been fixed in #709, recently.

- major: getting rid of clamav (>500M resident size) and replacing it with sophos antivirus for linux (~ 219M resident size). that change is a bit tricky to package in a docker image, because it requires registration to sophos, license agreements need to be read and accepted, and needs to be configured with a unique username/password.

- minor: changed the number of amavisd-new max-processes from 2 to 1 to reduce memory footprint. each daemon consumes about 125M of resident memory. tough to tell whether the virtmem is shared between amavis processes or not. so this may not help.

I'd like to remove amavisd altogether and run a postprox content filter instead ([ubuntuwiki article])(http://ubuntuwiki.net/index.php/Postfix,_Virtual_Domain_Setup#Installing_Content_Filtering_with_Postprox) milter that calls into spamassassin and the AV. I think that will clear an extra 100M.

**Comment by johansmitsnl** [comment] 2017-09-08 08:18
Do you have a fork available for review?
I think some are interesting in implementing.

**Comment by init-js** [comment] 2017-09-08 16:21
Not yet, I have to clean a few things up first, and then I can make pull requests.

**Comment by johansmitsnl** [comment] 2017-09-08 16:44
I'll close this issue for now. I'll loved to see you or later.

**Closed by johansmitsnl** 2017-09-08 16:44 UTC
