### ISSUE TITLE
How to move Spam messages into Spam folder?

### ISSUE THREAD

**Issue by modInfo** [tomav/docker-mailserver#795] opened 2018-01-16 21:46 UTC
```
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=0
    - ENABLE_FAIL2BAN=0
    - ENABLE_POSTGREY=0
    - SA_KILL=1000
    - ONE_DIR=1
    - DMS_DEBUG=0
    - SSL_TYPE=manual
    - SSL_CERT_PATH=/etc/letsencrypt/live/mail./fullchain.pem
    - SSL_KEY_PATH=/etc/letsencrypt/live/mail./privkey.pem
```

## My solution:

File: /var/lib/dovecot/sieve/default.sieve
```
require "fileinto";
if header :contains "X-Spam-Flag" "YES" {
        fileinto "Spam";
}
```

File: /etc/dovecot/conf.d/90-sieve.conf
```
  sieve_default = /var/lib/dovecot/sieve/default.sieve
```

Compile this file by sieve compiler
```
cd /var/lib/dovecot/sieve/
sievec default.sieve
```

do not forget to commit changes
`docker commit <container-id> tvial/docker-mailserver:latest`

**Comment by 17Halbe** [comment] 2018-01-19 23:19
It‘s the default and configurable implementation: 
See also #768

**Comment by modInfo** [comment] 2018-01-19 23:21
How do it automatically move to Junk?
What settings have I forgotten to add to docker-compose?

**Comment by 17Halbe** [comment] 2018-01-19 23:27
From the link, I provided: 

> It it gets over the kill level it deletes the email. If it is below but also spam it gets in je Junk folder.
This is default.

So if you set the kill level to something high(or low(?)) even the worst spam won‘t be deleted but also be moved to your Junk folder

**Comment by modInfo** [comment] 2018-01-21 11:27
Junk folder doesn't exist for new users how to create it?

**Comment by 17Halbe** [comment] 2018-01-24 09:32
Are you sure? It should have gotten created by dovecot at creation time. But one is not "subscribed" to it. To see if had been created:
`./setup.sh debug login
ls -al /var/mail/<DOMAIN>/<USERNAME>`
Where you replace <DOMAIN> with your domain (like domain.net) and <USERNAME> with the address portion of the email-address in question ( user in case of user@domain.net)
You should then see a folder `.Junk` (besides the rest of the mailbox)

You could subscribe to it using your Mail-client. I guess..

**Comment by modInfo** [comment] 2018-01-24 14:44
```bash
root@mail:/var/mail/my.eu/test# ls -al
total 64
drwx------ 10 docker docker 4096 Jan 16 22:42 .
drwxr-xr-x  6 docker docker 4096 Jan 21 13:21 ..
drwx------  5 docker docker 4096 Jan 14 18:02 .Archive
drwx------  5 docker docker 4096 Jan 14 17:55 .Drafts
drwx------  5 docker docker 4096 Jan 15 18:46 .Sent
drwx------  5 docker docker 4096 Jan 14 18:02 .Spam
drwx------  5 docker docker 4096 Jan 14 17:55 .Trash
drwx------  2 docker docker 4096 Jan 14 18:04 cur
```

**Comment by H4R0** [comment] 2018-01-26 21:13
@17Halbe @modInfo
I think the Problem is in docker-mailserver/target/dovecot/15-mailboxes.conf
The Folder Trash is missing either "auto = create" or "auto = subscribe" therefore the Junk folder is not created for the users.
As mentioned in my issue i use a sed replacement to fix the file:

(Warning: this renames the Junk folder to "Spam" keep this in mind for the sieve filter "fileinto" option)
docker exec -it mail sed -i 's/mailbox Junk {/mailbox Spam {\n    auto = subscribe/g' /etc/dovecot/conf.d/15-mailboxes.conf
docker restart mail

This will add "auto = subscribe" to the Trash folder which will create and subscribe the folder.
After running both commands the Trash folder should exist for every User automatically. You may have to refresh the folders on your mail client.

IMHO subscribing Junk should be the default even if it is not used.

@modInfo could you try the fix ? You can simply run the two commands without changing them.

**Comment by modInfo** [comment] 2018-01-26 21:35
Now works.

```
drwx------  5 docker docker 4096 Jan 26 21:33 .Archive
drwx------  5 docker docker 4096 Jan 26 21:33 .Drafts
drwx------  5 docker docker 4096 Jan 26 21:33 .Sent
drwx------  5 docker docker 4096 Jan 26 21:33 .Spam
drwx------  5 docker docker 4096 Jan 26 21:33 .Trash
```

> /etc/dovecot/conf.d/15-mailboxes.conf
> 
>   mailbox Spam {
>     auto = subscribe
>     special_use = \Junk
>   }

**Comment by johansmitsnl** [comment] 2018-02-06 19:22
#806 is merged.

**Closed by johansmitsnl** 2018-02-06 19:22 UTC

**Comment by jonaseberle** [comment] 2018-07-16 10:11
First of all thank you all contributors for this nice package! 

For me it did not globally move spam out-of-the-box. 

Just to reiterate the simple steps to get all recognized spam moved into Junk/:
<pre>
environment:
  ENABLE_SPAMASSASSIN=1
  # this is the threshold
  SA_TAG2=6.31 
  # never delete spam
  SA_KILL= 
</pre>

Create file `config/after.dovecot.sieve`:
<pre>
require "fileinto";
if header :contains "X-Spam-Flag" "YES" {
  fileinto "Junk";
}
</pre>


You can test it by lowering the SA_TAG2 threshold 

KNOWN PROBLEMS: 
mail with the SPAMASSASSIN special testing body `XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X`
gets deleted although I would expect it to be moved, too
