### ISSUE TITLE
greylist entries in mail.log cropped

### ISSUE THREAD

**Issue by teecee1** [tomav/docker-mailserver#1276] opened 2019-09-26 10:41 UTC
For all entries in mail.log from greylist the date-time-identification is missing  at the beginning of each greylist-line. See 2nd line in this snippet:

mail.log:
>Sep 26 12:16:55 nyx postfix/smtpd[2334]: warning: 181...
>action=greylist, reason=new, client_name=marry.xxx.com, client_address=134....
>Sep 26 12:16:55 nyx postfix/smtpd[2334]: NOQUEUE: reject: RCPT from marry...

this always and for all messages from greylist.
All  entries from other modules are OK.

Edit:
I cannot see any option to format the postgrey log-output. So I have no idea where to search for or change this bug.

**Comment by erik-wramner** [comment] 2019-10-06 10:54
I can't find a way to fix it either. It appears https://github.com/schweikert/postgrey/blob/master/postgrey does next to no formatting. Possibly we could configure rsyslogd to handle it, but as the other mail logs look good I'm not sure that would work.

**Comment by teecee1** [comment] 2019-10-06 18:20
Do you have the same short log-entries from postgrey without date/time ?
Do all users of this container have it?

**Comment by erik-wramner** [comment] 2019-10-07 06:35
I have the same entries that you reported.

**Comment by mindrunner** [comment] 2020-02-13 15:03
I cannot find any log output of postgrey in my log. Is there anything I can activate or configure?

**Comment by teecee1** [comment] 2020-02-14 15:09
I switched greylisting off with "ENABLE_POSTGREY=0".

- log is there, but not OK. so tools do not work. (I say logs with "greylisted" in the message)
- nearly 100% of spam goes thru greylisting. it is useless for me.

**Comment by mindrunner** [comment] 2020-02-14 17:33
> I cannot find any log output of postgrey in my log. Is there anything I can activate or configure?

I can confirm having the greylist log in my logfiles, but without timestamps. I assume, because of the malformed format, they are not being stashed into my logstash? How can we approach this problem to get that fixed?

**Comment by erik-wramner** [comment] 2020-02-16 13:27
> How can we approach this problem to get that fixed?

Perhaps an issue or question to upstream ( https://github.com/schweikert/postgrey)?

**Comment by aendeavor** [comment] 2020-10-02 11:23
Postgres upstream on master has stalled and is one year old. What should we do about that @erik-wramner ?

**Comment by mindrunner** [comment] 2020-10-02 11:27
`s/Postgres/Postgrey/` ;)

**Comment by aendeavor** [comment] 2020-10-02 11:31
> `s/Postgres/Postgrey/` ;)

I was a little bit confused at first.

PS: Sorry for editing your comment, was on accident.

**Comment by mindrunner** [comment] 2020-10-02 11:38
Now worries. Confusion was on my side, too.

On topic. I wonder why/how this project became stale. I think many people rely on it. At least, it is used by big mail-hosters and probably lot's of folks hosting their own email shit (as we do).

I am not aware of any other postgrey implementations and schweikert has been my reference for ever. Anyways, I did not get an answer, nor do I have much time to look into this by myself. Actually, it does not bug me enough to do so. Also, since this is an upstream issue, I suppose we can close this bug here in favor of https://github.com/schweikert/postgrey/issues/81

**Comment by mindrunner** [comment] 2020-10-02 11:38
Thanks for cleaning the issue tracker lately, btw @aendeavor

**Comment by aendeavor** [comment] 2020-10-02 11:40
Yeah, I agree. I'll close this in favour of the postgrey entry.

PS: Thanks for noticing:)

**Closed by aendeavor** 2020-10-02 11:40 UTC
Labels: bug, help wanted, priority 2 [MEDIUM]
