### ISSUE TITLE
Dovecot with Full Text Search

### ISSUE THREAD

**Issue by bityoda** [tomav/docker-mailserver#905] opened 2018-03-17 14:36 UTC
How about adding FullTextSearch support to dovecot?

## Context

I'm currently trying out your great project. Beside from the fact, that i have it already running, i'm thinking about to improve it using a better fulltextsearch support.
To be more detailed, i would like to enable this within your container:
https://www.howtoforge.com/community/threads/dovecot-with-fts-lucene.76812/

My first experiences to directly modify the container has failed, which is for sure a lack of knowledge how about the thinks work together there.

Perhaps it are small and fast enhancements for you, from which everyone could improve afterwards.

## Expected Behavior

Searching mails within bigger mailboxes should be fast.

**Comment by johansmitsnl** [comment] 2018-03-17 17:10
This sounds good, what about the impact on disk and CPU when adding this?

**Comment by 17Halbe** [comment] 2018-03-20 08:56
What about [fts-solar](https://wiki2.dovecot.org/Plugins/FTS/Solr)? Lucene is a bit discouraged by the dovecot team. See this [note](https://wiki2.dovecot.org/Plugins/FTS/Lucene)

**Comment by bityoda** [comment] 2018-03-20 09:02
Solar uses more resources, lucene is based on c and smaller in comparison to solr. But also with solr i would be happy;-)

**Comment by 17Halbe** [comment] 2018-03-20 17:13
I haven't used either. But if we implement something, we should choose something which is still maintained, what is your experience/suggestion?

**Comment by bityoda** [comment] 2018-03-21 07:45
My impression is that both have their right to exist within dovecot and for both someone could find use cases that makes sense together with dovecot.

Targeting this project, supporting lucence would have less impact on resource usage and changes within the docker containers. Solr runs within his own jvm, with web frontend and so on. It is probably better yes, but also much bigger.

If you ask about the future of dovecot and lucene, i'm the wrong person to ask. I also saw this remarks from the dovecot team, but i also saw still many persons using lucene.

**Comment by johansmitsnl** [comment] 2018-03-21 18:30
I think after reading the post Solr is the way to go.
You can use https://hub.docker.com/_/solr/ for a server and make configuration to use the docker (like ldap).

**Comment by 17Halbe** [comment] 2018-03-22 16:38
What about a wiki entry if/when you got it running?

**Comment by cyrinux** [comment] 2018-05-02 20:14
Hi, Must adapt this one, https://extremeshok.com/6622/enabling-apache-solr-4-10-using-jetty-with-dovecot-2-2-for-fulltext-search-results-on-centos-6-iredmail-compatible/

Allready tried by the past on another mail server, try well

**Comment by Thamster** [comment] 2018-05-06 06:11
I got solr working manually with dovecot from this docker image, maybe someone can put together a pull request to incorporate into this project. 

Just run a separate container to host the solr db. This one is preconfigured for dovecot-solr
`docker run --name my_solr -d -p 8983:8983 -t lmmdock/dovecot-solr:latest`

Then on the mail docker container simply run:
```
apt update && apt install dovecot-solr
cd /etc/dovecot/conf.d/

vi 10-mail.conf 
mail_plugins = fts fts_solr

vi 90-plugin.conf 
plugin {
  #setting_name = value
  fts = solr
  fts_autoindex = yes
  fts_solr = url=http://localhost:8983/solr/dovecot/ break-imap-search debug
}

/etc/init.d/dovecot restart
doveadm -v index -u username Inbox
curl http://localhost:8983/solr/dovecot/update?optimize=true
curl http://localhost:8983/solr/dovecot/update?commit=true
doveadm fts rescan -u username
```
That's it

**Comment by cyrinux** [comment] 2018-05-06 17:47
Thx @Thamster, works very well. Should be added as a offcial feature :)

**Comment by Thamster** [comment] 2018-05-07 08:07
Glad it worked for you too @cyrinux . 

I created a fork with the required changes:
https://github.com/Thamster/docker-mailserver/commit/9e08cb45e4eac6350dbce7a9efd868800d96289e

Though I am not sure if it is the best way to fit this into the existing code,
maybe someone can suggest a better way, before I make a pull request.

**Comment by time4tea** [comment] 2019-08-18 15:59
This worked for me:

docker-compose.yaml *changes*
```yaml
version: '2'

services:
  mail:
    build: .
    volumes:
    - ${PWD}/dovecot-conf.d/10-mail.conf:/etc/dovecot/conf.d/10-mail.conf
    - ${PWD}/dovecot-conf.d/90-plugin.conf:/etc/dovecot/conf.d/90-plugin.conf
    links:
    - solr

  solr:
    image: solr:8.1.1
    volumes:
      - /data/solr/dovecot:/var/solr/data/dovecot
    ports:
      - "8983:8983"
```

Adding docker-solr is a non-destructive change - it could be added into the base image - it just adds a shared library.
https://packages.debian.org/en/stretch-backports/amd64/dovecot-solr/filelist

Dockerfile
```
FROM tvial/docker-mailserver@sha256:26403a49ed8a22135baaf8d4c326ffe21033fd8b69c2dcaf959b71ffab5ecabd

RUN apt-get update && \
	apt-get -t stretch-backports -y install --no-install-recommends dovecot-solr && \
	apt-get autoclean && \
	rm -rf /var/lib/apt/lists/* && \
	rm -rf /usr/share/locale/* && \
	rm -rf /usr/share/man/* && \
	rm -rf /usr/share/doc/*
```

Then you can clone the repo above, and put the files into your host machine in the right place. You'll need to delete the "data" directory, as this changes between solr versions, however will be created on demand.

**Comment by erik-wramner** [comment] 2019-08-18 16:44
Looks promising! We could add dovecot-solr to the Dockerfile for sure. Then I think we should use an environment variable for enabling the feature and fix start-mailserver.sh so that it patches the configuration files on startup when the feature is on. That is consistent with how other features work.

I'm not sure about the doveadm and curl commands as I would guess that both the mail directory and the sol database are on persistent volumes? They probably don't hurt, but they sound expensive so it may be better to run them on demand.

The documentation needs to be updated and yaml files for docker compose added. Finally it is always nice with tests.

**Comment by lukecyca** [comment] 2019-11-09 17:18
As a first step lets put `dovecot-solr` into the base image so this can be done without modifying the container. The config files can be adjusted as @time4tea has done.

Personally I have just gone into my container and made the appropriate changes, but I feel dirty for doing so. I know I'll have to redo it each time I rebuild the container.

**Comment by erik-wramner** [comment] 2019-11-10 09:16
See #1319.

**Comment by lukecyca** [comment] 2019-11-10 17:49
Thanks @erik-wramner!

With the new image, here is the necessary configuration that I am using:

1. docker-compose.yml:

```
  solr:
    image: lmmdock/dovecot-solr:latest
    restart: always

  mailserver:
    image: tvial/docker-mailserver:latest
    ...
    volumes:
      ...
      - ./etc/dovecot/conf.d/10-plugin.conf:/etc/dovecot/conf.d/10-plugin.conf:ro
    ...
```

2. `etc/dovecot/conf.d/10-plugin.conf`:
```
mail_plugins = fts fts_solr

plugin {
  fts = solr
  fts_autoindex = yes
  fts_solr = url=http://solr:8983/solr/dovecot/ 
}
```

3. Restart the mailserver container: `docker-compose restart mailserver`

4. And then run some commands inside `docker-compose exec mailserver /bin/bash`:
```
doveadm -v index -u username Inbox
curl http://solr:8983/solr/dovecot/update?optimize=true
curl http://solr:8983/solr/dovecot/update?commit=true
doveadm fts rescan -u username
```

**Comment by erik-wramner** [comment] 2019-11-11 12:38
The previous example has a persistent volume in the solr container plus a link. You don't have either? Surely we need the volume at least or everything has to be re-indexed after down/up?

**Comment by lukecyca** [comment] 2019-11-11 15:16
I've based it mostly on @Thamster's example above which uses [lmmdock/dovecot-solr](https://github.com/lmm-git/docker-dovecot-solr).

I'm not sure which directory within the solr container should be made a volume. I suspect `/opt/solr/server/solr/dovecot/` or one of its subdirectories but I'm not 100% sure where solr keeps its state. The problem is that this directory comes pre-populated in the image, so we can't just mount a blank directory over top of it.

The link and port mapping are not necessary because I changed the url to `http://solr:8983/...`, although the link is probably still a good idea so that solr is started before the mailserver container.

**Comment by erik-wramner** [comment] 2019-11-11 15:50
A blank directory won't work, but a docker volume will be initialized with whatever files are in the image when it is created and would persist between restarts.

The lmmdock image (and associated Github repo) has not changed since 2017, so perhaps it would be better to use the official image for this? It changed 23 days ago.

**Comment by aendeavor** [comment] 2020-09-27 09:16
This seems to have stalled, which is a shame. Anyone up to this?

**Comment by lukecyca** [comment] 2020-09-27 16:27
@aendeavor I've been running it with no issues using the steps I posted a few messages up. There is not really any further modification required to docker-mailserver to make this work.

That said, there is still an improvement that could be made by confirming which solr directory holds the necessary state, and make that a docker volume. Otherwise you must run the commands (my step 4 above) anytime you recreate the solr container.

**Comment by aendeavor** [comment] 2020-09-27 16:43
Thanks for the update. Is there already a wiki entr for this? If not, could you create one @lukecyca?

> That said, there is still an improvement that could be made by confirming which solr directory holds the necessary state, and make that a docker volume. Otherwise you must run the commands (my step 4 above) anytime you recreate the solr container.

Is a PR necessary for this? Could you provide one if so?

**Comment by lukecyca** [comment] 2020-09-29 03:31
New and improved.....

## Setup Steps

1. docker-compose.yml:

```
  solr:
    image: lmmdock/dovecot-solr:latest
    volumes:
     - solr-dovecot:/opt/solr/server/solr/dovecot
    restart: always

  mailserver:
    image: tvial/docker-mailserver:latest
    ...
    volumes:
      ...
      - ./etc/dovecot/conf.d/10-plugin.conf:/etc/dovecot/conf.d/10-plugin.conf:ro
    ...

volumes:
  solr-dovecot:
    driver: local

```

2. `etc/dovecot/conf.d/10-plugin.conf`:
```
mail_plugins = fts fts_solr

plugin {
  fts = solr
  fts_autoindex = yes
  fts_solr = url=http://solr:8983/solr/dovecot/ 
}
```

3. Start the solr container: `docker-compose up -d --remove-orphans solr`

4. Restart the mailserver container: `docker-compose restart mailserver`

5. Flag all user mailbox FTS indexes as invalid, so they are rescanned on demand when they are next searched
```
docker-compose exec mailserver doveadm fts rescan -A
```

## Discussion

I'm pretty happy with the above. I've blown it away and recreated it several times to test, and these instructions seem stable. The solr index persists even when bouncing the solr container.

> The previous example has a persistent volume in the solr container plus a link. 

Persistence is fixed. I decided not to use a link, as Solr is not strictly required for docker-mailserver to start. Nor does it need to be started first.

> The lmmdock image (and associated Github repo) has not changed since 2017, so perhaps it would be better to use the official image for this? It changed 23 days ago.

I looked into upgrading, however the latest official Solr 8 docker image doesn't have the dovecot schema, so I would have to build a new image (based off the official solr one) or some other non-trivial preconfiguration steps. The [dovecot solr instructions](https://wiki2.dovecot.org/Plugins/FTS/Solr) still reference Solr 7, so it's not even clear what would need to be done to make use of the newer Solr 8 versions (the schema seems version-dependent, judging by its filename). I think it's best that we stick with Solr 7.3.0.

> Is a PR necessary for this? Could you provide one if so?

I don't think so. If everyone is happy with these instructions, I'll move them onto a wiki page and we can close this issue.

**Comment by erik-wramner** [comment] 2020-09-29 05:30
It sounds simple enough to me. Please create a wiki page, and we can close this.

**Comment by aendeavor** [comment] 2020-10-06 07:02
@lukecyca have you already had time?:)

**Comment by lukecyca** [comment] 2020-10-08 22:38
Sorry for the delay! How's this?

https://github.com/tomav/docker-mailserver/wiki/Full-text-search

**Comment by aendeavor** [comment] 2020-10-09 08:30
> Sorry for the delay! How's this?
> 
> 
> 
> https://github.com/tomav/docker-mailserver/wiki/Full-text-search

That's great! I'll close this since this should be resolved with this wiki entry.

**Closed** 2020-10-09 08:31 UTC
Labels: enhancement, feature request, priority 2 [MEDIUM], waiting for contributor action

**Comment by micbase** [comment] 2021-02-01 05:00
I can't get this to work, I think there is one command missing according to https://wiki2.dovecot.org/Plugins/FTS/Solr, which is
```
/opt/solr/bin/solr create -c dovecot
```

Also dovecot throws this error `Error: fts_solr: received invalid uid '` when I search. Have you guys seen this before?

**Comment by lukecyca** [comment] 2021-02-01 05:13
@micbase did you use the `lmmdock/dovecot-solr` image like the instructions said? Or did you use the official `solr` image? The former is a bit older, but has the dovecot-specific stuff already set up.

**Comment by micbase** [comment] 2021-02-01 05:32
@lukecyca I'm using `lmmdock/dovecot-solr`. Pretty much the same as your instruction in the wiki page, except I use docker run command instead of docker-compose. 
What's your dovecot version? It seems there was a bug in parsing the XML http://dovecot.2317879.n4.nabble.com/fts-solr-Error-fts-solr-received-invalid-uid-0-td68934.html

**Comment by dclift** [comment] 2021-02-05 23:33
Thanks @lukecyca. Experiencing the same issue as @micbase unfortunately though. Following the instructions per the wiki, using docker-compose and the lmmdock/dovecot-solr image. Initially I got `Error: fts_solr: Indexing failed: 404 Not Found`

Until I ran `docker-compose exec solr /opt/solr/bin/solr create -c dovecot` per the suggestion from @micbase.

After that the solr server was able to be found, but now getting the same `Error: fts_solr: received invalid uid` when searching. 

Perhaps @aendeavor can reopen this issue?

**Comment by aendeavor** [comment] 2021-02-06 10:12
I can - but I'd like to know whether the wiki maybe just needs updating. Can the one who wrote the page tell whether there is something wrong as of now in the wiki?

**Comment by lukecyca** [comment] 2021-02-15 19:06
I'm using Solr version 7.3.0 (`lmmdock/dovecot-solr:latest`)

And Dovecot version 2.3.4.1 (f79e8e7e4)

I'm not positive that I first created the solr database with this dovecot version though. I did it a while back and have since updated my docker-mailserver image a few times.

I'm not sure what to suggest. I'm certainly no expert in Solr or even in dovecot. I just documented the process that worked for me at the time based on what @Thamster posted up thread.

There may be clues in the documentation at https://github.com/lmm-git/docker-dovecot-solr.

There is also another one at https://github.com/MrRaph/Docker-Solr_Dovecot but it's even older.

**Comment by micbase** [comment] 2021-02-21 21:38
My guess why `lmmdock/dovecot-solr` doesn't work is it's using the latest upstream solr, which is 8.8.x, but the [official doc](https://doc.dovecot.org/configuration_manual/fts/solr/) only mentions solr 7.7, and the schema definition from the official doc is newer than the lmmdock image.

I created a docker image based on the official doc, and it's working now.
You can follow the same instruction on [this page](https://github.com/docker-mailserver/docker-mailserver/wiki/Full-text-search), just replace the solr image with `micbase/solr-dovecot`
You don't need to run extra command to create a core, as this step is covered in the image.

**Comment by armouredking** [comment] 2021-03-06 07:32
I can confirm this. Using `9.0.1` docker-mailserver and the current `latest` tag lmmdock/dovecot-solr image does not work on a fresh install. I had to run the command from @micbase above to get the uid message but it followed:

```
Mar  6 07:09:19 025d34c9bc8c dovecot: imap(_personalemail_)<2529><7B57nti8UP3AqIzL>: Error: fts_solr: received invalid uid ',
Mar  6 07:09:18 025d34c9bc8c dovecot: indexer-worker(_personalemail_)<5824><_longstring_>: Indexed 11 messages in Junk (UIDs 3..15)
```

I noticed that lmmdock was updated around 3 months ago on the `latest` tag, so I went back to the previous tag `solr-v7.1` (not changed for 3 years) since that seems to jive with people having issues (thread above closed in October).

```
Mar  6 07:25:07 025d34c9bc8c dovecot: imap(_personalemail_)<2784><vVOfGdm84KrAqIyD>: Logged out in=158 out=52144 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=2 body_bytes=50829,
Mar  6 07:25:16 025d34c9bc8c dovecot: indexer-worker(_personalemail_)<2826><_longstring_>: Indexed 11 messages in Junk (UIDs 3..15),
Mar  6 07:25:20 025d34c9bc8c dovecot: imap-login: Login: user=<_personalemail_>, method=PLAIN, rip=_privateip_, lip=172.19.0.4, mpid=2848, TLS, session=<+VloGtm8vP3AqIzL>
```

And in solr:
```
2021-03-06 07:25:16.464 INFO  (qtp257895351-14) [   x:dovecot] o.a.s.u.p.LogUpdateProcessorFactory [dovecot]  webapp=/solr path=/update params={}{add=[_redacted stuff_, ... (11 adds)]} 0 274
```

I didn't try @micbase version above, though I did notice it does not have a volume for data storage configured. Is your image setup the same way for the persistent data? Is there a need to use it (newer, more feature support?) over the `solr-v7.1` tag of `lmmdock/dovecot-solr`?

**Comment by micbase** [comment] 2021-03-07 02:14
@armouredking It's the same way from the wiki page, if you mount a docker volume, you will get persistent data, otherwise it will be lost once you restart the container. I don't know if there is any new features with that.

**Comment by lmm-git** [comment] 2021-03-10 00:20
> My guess why `lmmdock/dovecot-solr` doesn't work is it's using the latest upstream solr, which is 8.8.x, but the [official doc](https://doc.dovecot.org/configuration_manual/fts/solr/) only mentions solr 7.7, and the schema definition from the official doc is newer than the lmmdock image.

Good catch! Didn't check this unfortunately when rebuilding the images (to get newer software/security updates). Or more exactly: I didn't check the updated version..

Also, I updated the images now to use Solr 7 again (and the schemes according to current official docs).

**Comment by Jip-Hop** [comment] 2021-03-23 17:37
I can't get FTS working, at least not with a persistent volume.

I'm using the `lmmdock/dovecot-solr` container. From the logs on this container I can't tell if it's working. It shows many of these errors:
```
2021-03-23 14:49:25,stdout,2021-03-23 14:49:25.282 INFO  (qtp1690716179-15) [   ] o.a.s.s.SolrDispatchFilter Could not consume full client request
2021-03-23 14:49:25,stdout,java.io.IOException: Committed before 100 Continues
at org.eclipse.jetty.server.HttpChannelOverHttp.continue100(HttpChannelOverHttp.java:210)
at org.eclipse.jetty.server.Request.getInputStream(Request.java:848)
at org.apache.solr.servlet.SolrDispatchFilter.consumeInputFully(SolrDispatchFilter.java:408)
at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:399)
at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:326)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1751)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
at org.eclipse.jetty.server.Server.handle(Server.java:534)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
at java.lang.Thread.run(Thread.java:748)
```

This is how my `docker-compose` config looks like for `lmmdock/dovecot-solr`.
```yml
  solr:
    container_name: mailserver_solr
    image: lmmdock/dovecot-solr:solr-v7.1
    ports:
      # - 127.0.0.1:8983:8983
      # Make web gui available on LAN
      - 8983:8983
    volumes:
      - /path/to/solr-dovecot:/opt/solr/server/solr/dovecot
      - /etc/localtime:/etc/localtime:ro
    restart: always
```

The folder at `/path/to/solr-dovecot` is chowned to 8983:8983 but it stays empty when running the container... I can create files inside the container with `sudo docker exec -it mailserver_solr touch /opt/solr/server/solr/dovecot/test` so permissions seem good.

I followed the wiki and the contents of `/etc/dovecot/conf.d/10-plugin.conf` (via mount) is:
```
mail_plugins = $mail_plugins fts fts_solr

plugin {
  fts = solr
  fts_autoindex = yes
  fts_solr = url=http://solr:8983/solr/dovecot/
}
```

To test, I run the following:
```
sudo docker-compose up -d --force-recreate solr && sudo docker-compose restart mailserver && sleep 10 && sudo docker-compose exec mailserver doveadm fts rescan -A
```
Then I log into Roundcube and search inside my mailbox. I think this triggers indexing.

My docker compose file does look a bit different than on the wiki, because I didn't do this:
```
volumes:
  solr-dovecot:
    driver: local
```
Could that be the problem? How would I specify the path to the persistent `dovecot` folder on the host in this case?

Note: I'm running Docker on a Synology DS918+ NAS.

Would really appreciate the help 🙂

**Comment by Jip-Hop** [comment] 2021-03-23 18:18
I should have just followed the wiki exactly 😂 
I was so used to using bind mounts and didn't understand where the persistent data would go when using volumes.
On my Synology NAS it's at /volume1/@docker/volumes.
All good now 🙂
