### ISSUE TITLE
Using example setup: "authentication error: Input/output error"

### ISSUE THREAD

**Issue by NitroPye** [tomav/docker-mailserver#82] opened 2016-02-18 22:50 UTC
I'm trying to use this container and starting with the example setup in the README but I am running into a snag.

When I try to auth for either imap or pop I get the same output. I've turned on authdaemon debug output to see whats going on.

accounts.cf:
```
test@myhidden.domain.com|mypassword
```

imap auth test
```
telnet myhidden.domain.com 143
a1 LOGIN test@myhidden.domain.com mypassword
```

pop3 auth test
```
telnet myhidden.domain.com 110
user test@myhidden.domain.com
pass mypassword
```

Both telnet auth tests will immediately disconnect and the courier-imap or courier-pop will say "Input/output error"

log output
```
Feb 18 22:04:45 myhidden imapd: Connection, ip=[::ffff:10.51.212.84]
Feb 18 22:04:55 myhidden authdaemond: received auth request, service=imap, authtype=login
Feb 18 22:04:55 myhidden authdaemond: authuserdb: trying this module
Feb 18 22:04:55 myhidden authdaemond: userdb: opened /etc/courier/userdb.dat
Feb 18 22:04:55 myhidden authdaemond: userdb: looking up 'test@myhidden.domain.com'
Feb 18 22:04:55 myhidden authdaemond: userdb: home=/var/mail/myhidden.domain.com/test, uid=5000, gid=5000, shell=<unset>, mail=/var/mail/myhidden.domain.com/test, quota=<unset>, gecos=<unset>, options=<unset>
Feb 18 22:04:55 myhidden authdaemond: found systempw in userdbshadow
Feb 18 22:04:55 myhidden authdaemond: authuserdb: sysusername=<null>, sysuserid=5000, sysgroupid=5000, homedir=/var/mail/myhidden.domain.com/test, address=test@myhidden.domain.com, fullname=<null>, maildir=/var/mail/myhidden.domain.com/test, quota=<null>, options=<null>
Feb 18 22:04:55 myhidden authdaemond: authuserdb: clearpasswd=<null>, passwd=$1$.VbT2WbF$Go.pwwu85lQMcqBUCYkIS0
Feb 18 22:04:55 myhidden authdaemond: password matches successfully
Feb 18 22:04:55 myhidden authdaemond: Authenticated: sysusername=<null>, sysuserid=5000, sysgroupid=5000, homedir=/var/mail/myhidden.domain.com/test, address=test@myhidden.domain.com, fullname=<null>, maildir=/var/mail/myhidden.domain.com/test, quota=<null>, options=<null>
Feb 18 22:04:55 myhidden imapd: LOGIN FAILED, user=test@myhidden.domain.com, ip=[::ffff:10.51.212.84]
Feb 18 22:04:55 myhidden imapd: authentication error: Input/output error
```

**Comment by tomav** [comment] 2016-02-18 22:58
Could you start the container in foreground and paste the logs from start to end of postfix boot?
I'll have a look tomorrow. Please copy your docker command line or compose file.

**Comment by NitroPye** [comment] 2016-02-18 23:25
Sure.

Docker command:

```
docker run --rm -h myhidden.mydomain.com -p 25:25 -p 110:110 -p 143:143 -p 587:587 -p 993:993 -p 995:995 -v /spamassassin:/tmp/spamassassin/ -v /postfix:/tmp/postfix/ -e ENABLE_POP3=1 tvial/docker-mailserver:latest
```

Foreground log output:

```
Digest: sha256:83ab8846e023ca6311a53ccb49dc9e8d785708313aace21a85b69ee779ccfb34
Status: Downloaded newer image for tvial/docker-mailserver:latest
Regenerating postfix 'vmailbox' and 'virtual' for given users
user 'test' for domain 'myhidden.mydomain.com' with password '********'
==> Warning: '/tmp/postfix/virtual' is not provided. No mail alias created.
Postfix configurations
Creating DKIM private key /etc/opendkim/keys/myhidden.mydomain.com/mail.private
/etc/opendkim/keys/myhidden.mydomain.com /
/

DKIM PUBLIC KEY ################################################################
mail._domainkey  IN  TXT  ( "v=DKIM1; k=rsa; "
    "p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCujE+L0G8bOxujEQ7+RlakaZwuG4U24iZNNBRYOMd+VevcQq0ZbX96fv0eyVf8RiVnXTk4u1HAL6PPzDvri38O8sw9/vEFKuioni6xw5xbWTFkfnVHiB8Jhjj7H/dXrGeY1jj7AiMz+wkh2CuNJJd1PUnTyNZXMRyABdmzvhGWIQIDAQAB" )  ; ----- DKIM key mail for myhidden.mydomain.com
################################################################################
Creating DKIM KeyTable
Creating DKIM SigningTable
Changing permissions on /etc/opendkim
Fixing permissions
Creating /etc/mailname
Configuring Spamassassin
cp: cannot stat '/tmp/spamassassin/rules.cf': No such file or directory
Configuring fail2ban
Starting daemons
 * Starting enhanced syslogd rsyslogd
   ...done.
 * Starting  saslauthd
   ...done.
 * Starting Courier authentication services authdaemond
   ...done.
 * Starting Courier IMAP server imapd
   ...done.
 * Starting Courier IMAP-SSL server imapd-ssl
   ...done.
Starting POP3 services
 * Starting Courier POP3 server...
   ...done.
 * Starting Courier POP3-SSL server...
   ...done.
Starting SpamAssassin Mail Filter Daemon: spamd.
 * Starting ClamAV daemon clamd 
   ...done.
Starting amavisd: amavisd-new.
Starting OpenDKIM: opendkim.
Starting OpenDMARC: opendmarc.
 * Starting Postfix Mail Transport Agent postfix
   ...done.
 * Starting authentication failure monitor fail2ban
   ...done.
Listing SASL users
test@myhidden.mydomain.com: userPassword
Starting...
Feb 18 23:14:39 myhidden amavis[567]: Internal decoder for .tnef
Feb 18 23:14:39 myhidden amavis[567]: Found decoder for    .exe  at /usr/bin/arj
Feb 18 23:14:39 myhidden amavis[567]: Using primary internal av scanner code for ClamAV-clamd
Feb 18 23:14:39 myhidden amavis[567]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
Feb 18 23:14:39 myhidden amavis[567]: Deleting db files  in /var/lib/amavis/db
Feb 18 23:14:39 myhidden amavis[567]: Creating db in /var/lib/amavis/db/; BerkeleyDB 0.54, libdb 5.3
Feb 18 23:14:39 myhidden opendkim[579]: OpenDKIM Filter v2.9.1 starting (args: -x /etc/opendkim.conf -u opendkim -P /var/run/opendkim/opendkim.pid)
Feb 18 23:14:39 myhidden opendmarc[580]: OpenDMARC Filter v1.2.0 starting (args: -c /etc/opendmarc.conf -u opendmarc -P /var/run/opendmarc/opendmarc.pid -p inet:54321@localhost)
Feb 18 23:14:39 myhidden opendmarc[580]: trusted authentication services: myhidden.mydomain.com
Feb 18 23:14:39 myhidden postfix/master[684]: daemon started -- version 2.11.0, configuration /etc/postfix
Feb 18 23:15:49 myhidden imapd: Connection, ip=[::ffff:172.17.0.1]
Feb 18 23:16:02 myhidden imapd: LOGIN FAILED, user=test@myhidden.mydomain.com, ip=[::ffff:172.17.0.1]
Feb 18 23:16:02 myhidden imapd: authentication error: Input/output error
```

Then on a different shell I run this

```
developer@myhidden:~$ telnet localhost 143
Trying ::1...
Connected to localhost.
Escape character is '^]'.
* OK [CAPABILITY IMAP4rev1 UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE ACL ACL2=UNION STARTTLS] Courier-IMAP ready. Copyright 1998-2011 Double Precision, Inc.  See COPYING for distribution information.
a1 LOGIN test@myhidden.mydomain.com mypassword
* BYE Temporary problem, please try again later
Connection closed by foreign host.
```

I set authdaemon debug log to 2 (show all debug and passwords). Docker output looks like this after performing the same above action:
```
Feb 18 23:18:21 myhidden authdaemond: stopping authdaemond children
Feb 18 23:18:21 myhidden authdaemond: modules="authuserdb", daemons=1
Feb 18 23:18:21 myhidden authdaemond: Installing libauthuserdb
Feb 18 23:18:21 myhidden authdaemond: Installation complete: authuserdb
Feb 18 23:18:34 myhidden imapd: Connection, ip=[::ffff:172.17.0.1]
Feb 18 23:18:44 myhidden authdaemond: received auth request, service=imap, authtype=login
Feb 18 23:18:44 myhidden imapd: LOGIN FAILED, user=test@myhidden.mydomain.com, ip=[::ffff:172.17.0.1]
Feb 18 23:18:44 myhidden imapd: authentication error: Input/output error
Feb 18 23:18:44 myhidden authdaemond: authuserdb: trying this module
Feb 18 23:18:44 myhidden authdaemond: userdb: opened /etc/courier/userdb.dat
Feb 18 23:18:44 myhidden authdaemond: userdb: looking up 'test@myhidden.mydomain.com'
Feb 18 23:18:44 myhidden authdaemond: userdb: home=/var/mail/myhidden.mydomain.com/test, uid=5000, gid=5000, shell=<unset>, mail=/var/mail/myhidden.mydomain.com/test, quota=<unset>, gecos=<unset>, options=<unset>
Feb 18 23:18:44 myhidden authdaemond: found systempw in userdbshadow
Feb 18 23:18:44 myhidden authdaemond: authuserdb: sysusername=<null>, sysuserid=5000, sysgroupid=5000, homedir=/var/mail/myhidden.mydomain.com/test, address=test@myhidden.mydomain.com, fullname=<null>, maildir=/var/mail/myhidden.mydomain.com/test, quota=<null>, options=<null>
Feb 18 23:18:44 myhidden authdaemond: authuserdb: clearpasswd=<null>, passwd=$1$74SWQARX$xNzlrgaGSCbAaImj4/O.g1
Feb 18 23:18:44 myhidden authdaemond: password matches successfully
Feb 18 23:18:44 myhidden authdaemond: Authenticated: sysusername=<null>, sysuserid=5000, sysgroupid=5000, homedir=/var/mail/myhidden.mydomain.com/test, address=test@myhidden.mydomain.com, fullname=<null>, maildir=/var/mail/myhidden.mydomain.com/test, quota=<null>, options=<null>
Feb 18 23:18:44 myhidden authdaemond: Authenticated: clearpasswd=mypassword, passwd=$1$74SWQARX$xNzlrgaGSCbAaImj4/O.g1
Feb 18 23:24:00 myhidden imapd: Connection, ip=[::ffff:172.17.0.1]
Feb 18 23:24:03 myhidden authdaemond: received auth request, service=imap, authtype=login
Feb 18 23:24:03 myhidden authdaemond: authuserdb: trying this module
Feb 18 23:24:03 myhidden authdaemond: userdb: opened /etc/courier/userdb.dat
Feb 18 23:24:03 myhidden authdaemond: userdb: looking up 'test@myhidden.mydomain.com'
Feb 18 23:24:03 myhidden authdaemond: userdb: home=/var/mail/myhidden.mydomain.com/test, uid=5000, gid=5000, shell=<unset>, mail=/var/mail/myhidden.mydomain.com/test, quota=<unset>, gecos=<unset>, options=<unset>
Feb 18 23:24:03 myhidden authdaemond: found systempw in userdbshadow
Feb 18 23:24:03 myhidden authdaemond: authuserdb: sysusername=<null>, sysuserid=5000, sysgroupid=5000, homedir=/var/mail/myhidden.mydomain.com/test, address=test@myhidden.mydomain.com, fullname=<null>, maildir=/var/mail/myhidden.mydomain.com/test, quota=<null>, options=<null>
Feb 18 23:24:03 myhidden authdaemond: authuserdb: clearpasswd=<null>, passwd=$1$74SWQARX$xNzlrgaGSCbAaImj4/O.g1
Feb 18 23:24:03 myhidden authdaemond: password matches successfully
Feb 18 23:24:03 myhidden authdaemond: Authenticated: sysusername=<null>, sysuserid=5000, sysgroupid=5000, homedir=/var/mail/myhidden.mydomain.com/test, address=test@myhidden.mydomain.com, fullname=<null>, maildir=/var/mail/myhidden.mydomain.com/test, quota=<null>, options=<null>
Feb 18 23:24:03 myhidden authdaemond: Authenticated: clearpasswd=mypassword, passwd=$1$74SWQARX$xNzlrgaGSCbAaImj4/O.g1
Feb 18 23:24:03 myhidden imapd: LOGIN FAILED, user=test@myhidden.mydomain.com, ip=[::ffff:172.17.0.1]
Feb 18 23:24:03 myhidden imapd: authentication error: Input/output error
```

Note: I scrubbed any FQDN bits from the logs and turned it into myhidden.mydomain.com.

**Comment by tomav** [comment] 2016-02-19 07:47
I can't try right now, but try to provide a `postfix/virtual` file with an alias:
`somethingelse@myhidden.mydomain.com test@myhidden.mydomain.com``

Then start the container and test login again.
I'm not sure but if it's the problem, there's a bug to fix.

**Comment by NitroPye** [comment] 2016-02-19 17:45
Okay I gave that a try. Same issue it seems. Logs don't say its skipping postfix/virtual now but other than that no change.

```
Regenerating postfix 'vmailbox' and 'virtual' for given users
user 'test' for domain 'myhidden.mydomain.com' with password '********'
Postfix configurations
Creating DKIM private key /etc/opendkim/keys/myhidden.mydomain.com/mail.private
/etc/opendkim/keys/myhidden.mydomain.com /
/

DKIM PUBLIC KEY ################################################################
mail._domainkey  IN  TXT  ( "v=DKIM1; k=rsa; "
    "p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCkBgagfc4VsVXVBqpLbDJyHgYImk7C195kWWnYf3H5HgnMkk9PFzc8pSKYpg8Pa2aW97Rz+2u8Ocs7ORie94bunyuEkND0spduPwc5uzO3IFFwJXB1qJn8PAGHgEmAqg9Gdnn5mN8DWaQ0CKmkfHPQ/wpntiYv6NrWClwI0S52IQIDAQAB" )  ; ----- DKIM key mail for myhidden.mydomain.com
################################################################################
Creating DKIM KeyTable
Creating DKIM SigningTable
Changing permissions on /etc/opendkim
Fixing permissions
Creating /etc/mailname
Configuring Spamassassin
cp: cannot stat '/tmp/spamassassin/rules.cf': No such file or directory
Configuring fail2ban
Starting daemons
 * Starting enhanced syslogd rsyslogd
   ...done.
 * Starting  saslauthd
   ...done.
 * Starting Courier authentication services authdaemond
   ...done.
 * Starting Courier IMAP server imapd
   ...done.
 * Starting Courier IMAP-SSL server imapd-ssl
   ...done.
Starting POP3 services
 * Starting Courier POP3 server...
   ...done.
 * Starting Courier POP3-SSL server...
   ...done.
Starting SpamAssassin Mail Filter Daemon: spamd.
 * Starting ClamAV daemon clamd 
   ...done.
Starting amavisd: amavisd-new.
Starting OpenDKIM: opendkim.
Starting OpenDMARC: opendmarc.
 * Starting Postfix Mail Transport Agent postfix
   ...done.
 * Starting authentication failure monitor fail2ban
   ...done.
Listing SASL users
test@myhidden.mydomain.com: userPassword
Starting...
Feb 19 17:41:12 myhidden amavis[570]: Internal decoder for .tnef
Feb 19 17:41:12 myhidden amavis[570]: Found decoder for    .exe  at /usr/bin/arj
Feb 19 17:41:12 myhidden amavis[570]: Using primary internal av scanner code for ClamAV-clamd
Feb 19 17:41:12 myhidden amavis[570]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
Feb 19 17:41:12 myhidden amavis[570]: Deleting db files  in /var/lib/amavis/db
Feb 19 17:41:12 myhidden amavis[570]: Creating db in /var/lib/amavis/db/; BerkeleyDB 0.54, libdb 5.3
Feb 19 17:41:12 myhidden opendkim[578]: OpenDKIM Filter v2.9.1 starting (args: -x /etc/opendkim.conf -u opendkim -P /var/run/opendkim/opendkim.pid)
Feb 19 17:41:12 myhidden opendmarc[588]: OpenDMARC Filter v1.2.0 starting (args: -c /etc/opendmarc.conf -u opendmarc -P /var/run/opendmarc/opendmarc.pid -p inet:54321@localhost)
Feb 19 17:41:12 myhidden opendmarc[588]: trusted authentication services: myhidden.mydomain.com
Feb 19 17:41:12 myhidden postfix/master[687]: daemon started -- version 2.11.0, configuration /etc/postfix
Feb 19 17:41:28 myhidden imapd: Connection, ip=[::ffff:10.51.212.94]
Feb 19 17:41:39 myhidden imapd: LOGIN FAILED, user=test@myhidden.mydomain.com, ip=[::ffff:10.51.212.94]
Feb 19 17:41:39 myhidden imapd: authentication error: Input/output error
```

Not sure if this matters but I've included the output of `docker info`:

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.10.1
Storage Driver: aufs
 Root Dir: /mnt/data/docker/aufs
 Backing Filesystem: extfs
 Dirs: 60
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.16.0-30-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: myhidden.mydomain.com
ID: 5JMN:4ITT:XR6G:ILFN:OUVU:MM6H:FBEM:Q3S6:ATMI:QZCK:XIWC:DRE5
WARNING: No swap limit support
```

**Comment by tomav** [comment] 2016-02-19 18:06
I can't reproduce your problem, and without that, it's hard to investigate.

Be sure to use the latest image event if I think that **the problem is related to the a file provided, a mount issue or a permission issue.**

We have integration tests on each build and they're green, and production servers work fine. You can send me a download link with your config file and I'll have a look.

**Comment by NitroPye** [comment] 2016-02-19 20:50
Totally understand how tough it is to work with someone you cannot reproduce. We are having a tough time getting a stable case to show.

Using this:
https://github.com/NitroPye/docker-mailserver-test

On some hosts, sometimes the container does not work (error from above) and in some cases it does work. Unable to isolate whats causing it. I've tried fresh docker-machine instances. Fresh Vagrant VMs. Fresh VMs in our vSphere cluster, bare metal, on different networks in the office and out. Most fail, but sometimes we've spun up a new container from the same compose file and it will work. Incredibly confusing.

**Comment by tomav** [comment] 2016-02-19 20:52
Checking...

**Comment by tomav** [comment] 2016-02-19 20:57
➜  Desktop  git clone git@github.com:NitroPye/docker-mailserver-test.git
    Cloning into 'docker-mailserver-test'...
    remote: Counting objects: 8, done.
    remote: Compressing objects: 100% (4/4), done.
    remote: Total 8 (delta 0), reused 8 (delta 0), pack-reused 0
    Receiving objects: 100% (8/8), done.
    Checking connectivity... done.

    ➜  Desktop  cd docker-mailserver-test

    ➜  docker-mailserver-test git:(master) docker-compose up -d mail
    Creating dockermailservertest_mail_1...

    ➜  docker-mailserver-test git:(master) telnet 192.168.99.100 143
    Trying 192.168.99.100...
    Connected to 192.168.99.100.
    Escape character is '^]'.
    * OK [CAPABILITY IMAP4rev1 UIDPLUS CHILDREN NAMESPACE THREAD=ORDEREDSUBJECT THREAD=REFERENCES SORT QUOTA IDLE ACL ACL2=UNION STARTTLS] Courier-IMAP ready. Copyright 1998-2011 Double Precision, Inc.  See COPYING for distribution information.
    A1 LOGIN test@localhost test
    A1 OK LOGIN Ok.
    A2 LOGOUT
    * BYE Courier-IMAP server shutting down
    A2 OK LOGOUT completed
    Connection closed by foreign host.
    ➜  docker-mailserver-test git:(master)

Really strange if it doesn't work on most of your setups.
I tried on my MacMini and on a Linux server.
Config is fine.

**Comment by cigzigwon** [comment] 2016-02-20 20:20
Sounds like ur facing a networking or DNS issue. The box seems to work fine but for me digital ocean bars port 25 for SMTP. I also would avoid telnet as a debug or test tool because itself is another attack vector.

**Comment by NitroPye** [comment] 2016-02-20 20:37
Telnet is only being used as a client to test not as a server component. I've experienced the same results using `nc` from inside the container (`docker exec -ti mailcontainer bash`) ruling out network.

**Comment by cigzigwon** [comment] 2016-02-20 22:02
When I actually try with telnet as a test in from my host box via telnet localhost 110 I can connect but upon authenticating I get a TLS error. I ran this in a beta env and was able to grab mail through it via 110.

**Comment by NitroPye** [comment] 2016-02-20 22:13
>When I actually try with telnet as a test in from my host box via telnet localhost 110 I can connect but upon authenticating I get a TLS error.

I can't even get that far. Any auth commands via IMAP or POP3 protocols will cause the same error.

> Is ur hosts file pointing to 127.0.0.1 when you do the test?

You mean is 127.0.0.1 pointing to localhost in my hosts file? Of course.

**Comment by cigzigwon** [comment] 2016-02-20 22:25
See that error with spam assassin you have? You mounted off of root.

**Comment by NitroPye** [comment] 2016-02-20 22:37
Are you referring to this?

> cp: cannot stat '/tmp/spamassassin/rules.cf': No such file or directory

I know I mounted off root. There was no rules file in that particular run. Whether or not that is there doesn't seem to make a difference.

**Comment by cigzigwon** [comment] 2016-02-20 23:08
Yes, so if /postfix/accounts.cf doesn't exist you won't have a login there. Just saying but other than that I don't see a problem running this container and using it in beta works. I can send and receive mail and one of my webapps uses it as a relay.

**Comment by NitroPye** [comment] 2016-02-20 23:30
I'm sorry I don't think you are following. /postfix/accounts.cf is definitely there. You can see from the logs. I'm really glad you can send and receive mail using this container. I think I'm looking at a deeper issue than just setup. Thats been ruled out long ago.

> Regenerating postfix 'vmailbox' and 'virtual' for given users
> user 'test' for domain 'myhidden.mydomain.com' with password '********'

and later in the log

> Listing SASL users
> test@myhidden.mydomain.com: userPassword

**Comment by tomav** [comment] 2016-02-27 17:53
Hi @NitroPye, any update on this issue? Still exists?

**Comment by minderrd** [comment] 2016-03-01 09:45
Hi, I also have the same issue. And here is what I did

1. set DEBUG_LOGING to 3 in /etc/courier/authdaemonrc
2. stop courier-authdaemon
```
/etc/init.d/courier-authdaemon stop
```
3. check the daemon is gone
```
 ps -ef | grep authdaemond
```
4. start courier-authdaemon
```
/etc/init.d/courier-authdaemon start
```
5. check the daemon is back
```
 ps -ef | grep authdaemond
```

and login with this
```
telnet example.com 143
a1 LOGIN test@example.com P@ssword
```

and here is the debug message in /var/log/mail.log
```
Mar  1 09:32:19 mail imapd: Connection, ip=[::ffff:172.17.0.1]
Mar  1 09:32:25 mail authdaemond: received auth request, service=imap, authtype=login
Mar  1 09:32:25 mail authdaemond: authuserdb: trying this module
Mar  1 09:32:25 mail authdaemond: userdb: looking up 'test@example.com'
Mar  1 09:32:25 mail authdaemond: userdb: home=/var/mail/example.com/test, uid=5000, gid=5000, shell=<unset>, mail=/var/mail/example.com/test, quota=<unset>, gecos=<unset>, options=<unset>
Mar  1 09:32:25 mail authdaemond: found systempw in userdbshadow
Mar  1 09:32:25 mail authdaemond: authuserdb: sysusername=<null>, sysuserid=5000, sysgroupid=5000, homedir=/var/mail/example.com/test, address=test@example.com, fullname=<null>, maildir=/var/mail/example.com/test, quota=<null>, options=<null>
Mar  1 09:32:25 mail authdaemond: authuserdb: clearpasswd=<null>, passwd=$1$o688CyVJ$2TO9oK3xWRyp5fmeBla3z/ Mar  1 09:32:25 mail authdaemond: supplied password 'P@ssword' does not match encrypted password '$1$o688CyVJ$2TO9oK3xWRyp5fmeBla3z/'
Mar  1 09:32:25 mail authdaemond: authuserdb: REJECT - try next module
Mar  1 09:32:25 mail authdaemond: FAIL, all modules rejected
Mar  1 09:32:25 mail imapd: LOGIN FAILED, user=test@example.com, ip=[::ffff:172.17.0.1]
Mar  1 09:32:25 mail imapd: authentication error: Input/output error
```

And if I login with password, it works

```
telnet example.com 143
a1 LOGIN test@example.com
```
```
Mar  1 09:33:15 mail imapd: Connection, ip=[::ffff:172.17.0.1]
```

**Comment by tomav** [comment] 2016-03-01 09:55
@NitroPye and @minderrd, do you have a volume linked to the host for `/var/mail`?

**Comment by tomav** [comment] 2016-03-01 09:57
And regarding to your last comment on `saslpasswd2` password, could you try to change it in your `account.cf`? If the password remains the same, then the password is probably not read correctly from the file.

**Comment by NitroPye** [comment] 2016-03-01 18:57
@tomav I do not have a volume linked to the host for `/var/mail` should I give that a try?

**Comment by minderrd** [comment] 2016-03-02 01:03
@tomav that's what I guess. I don't have a volume link, too, but I checked `/var/mail`, I think it works fine.

I change my `account.cf`, and the password is changed, but the result is the same

here is the log

```
Mar  2 00:59:20 mail authdaemond: received auth request, service=imap, authtype=login
Mar  2 00:59:20 mail authdaemond: authuserdb: trying this module
Mar  2 00:59:20 mail authdaemond: userdb: opened /etc/courier/userdb.dat
Mar  2 00:59:20 mail authdaemond: userdb: looking up 'test@example.com'
Mar  2 00:59:20 mail authdaemond: userdb: home=/var/mail/example.com/test, uid=5000, gid=5000, shell=<unset>, mail=/var/mail/example.com/test, quota=<unset>, gecos=<unset>, options=<unset>
Mar  2 00:59:20 mail authdaemond: found systempw in userdbshadow
Mar  2 00:59:20 mail authdaemond: authuserdb: sysusername=<null>, sysuserid=5000, sysgroupid=5000, homedir=/var/mail/example.com/test, address=test@example.com, fullname=<null>, maildir=/var/mail/example.com/test, quota=<null>, options=<null>
Mar  2 00:59:20 mail authdaemond: authuserdb: clearpasswd=<null>, passwd=$1$csDPNoUB$Rz2SzE8Zln6.7EkZv8/.L1
Mar  2 00:59:20 mail authdaemond: password matches successfully
Mar  2 00:59:20 mail authdaemond: Authenticated: sysusername=<null>, sysuserid=5000, sysgroupid=5000, homedir=/var/mail/example.com/test, address=test@example.com, fullname=<null>, maildir=/var/mail/example.com/test, quota=<null>, options=<null>
Mar  2 00:59:20 mail authdaemond: Authenticated: clearpasswd=qazwsx, passwd=$1$csDPNoUB$Rz2SzE8Zln6.7EkZv8/.L1
Mar  2 00:59:20 mail imapd: LOGIN FAILED, user=test@example.com, ip=[::ffff:172.17.0.1]
Mar  2 00:59:20 mail imapd: authentication error: Input/output error
```

**Comment by tomav** [comment] 2016-03-02 09:27
Really strange... so accounts are created correctly. 
Sorry, we'll have to try few things to find the issue.
Could you check that:
* folders in `/var/mail` are owned by `docker`
* folders have 755 mode
* `docker` user exists in `/etc/passwd` with uid/gid 5000

Another test will be to use a docker data container volume. Here's my `docker-config.yml`

    maildata:
      image: ubuntu
      volumes:
        - /var/mail
      command: /bin/true

    mail:
      image: "tvial/docker-mailserver"
      hostname: "mail"
      domainname: "domain.com"
      volumes_from:
       - maildata
      ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      volumes:
      - ./spamassassin:/tmp/spamassassin/
      - ./postfix:/tmp/postfix/
      - ./opendkim/keys:/etc/opendkim/keys
      - ./letsencrypt/etc:/etc/letsencrypt
      environment:
      - DMS_SSL=letsencrypt
      - SA_TAG=1.0
      - SA_TAG2=5.0
      - SA_KILL=6.0

**Comment by minderrd** [comment] 2016-03-03 03:11
@tomav 

* folders in `/var/mail` are owned by `docker` -> correct
* folders have 755 mode -> they are 700 mode
* `docker` user exists in `/etc/passwd` with uid/gid 5000 -> correct

**Comment by tomav** [comment] 2016-03-03 08:36
Try moving `/var/mail` and `/var/mail/domain.com` to 755. Mine is 755.

**Comment by minderrd** [comment] 2016-03-04 00:51
@tomav I tried, I still can't login.

I did another test by using `testsaslauthd`
```
testsaslauthd -u test -p mypassword -r example.com
```
and it returns
```
0: OK "Success."
```
But I can't change the password using `saslpasswd2`, it remain the same. Weird.

**Comment by tomav** [comment] 2016-03-22 10:57
Password have to be changed in config files and restart server.

**Comment by tomav** [comment] 2016-03-22 10:58
Note that password changing (event with restart) is not tested yet.
I'll try to test it and we have to write a functional test on it.

**Comment by tomav** [comment] 2016-03-31 08:51
Close due to inactivity. Reopen if necessary.

**Closed by tomav** 2016-03-31 08:51 UTC
Labels: question
