### ISSUE TITLE
ELK build no longer possible due to GeoIP license changes

### ISSUE THREAD

**Issue by sischnei** [tomav/docker-mailserver#1348] opened 2019-12-31 08:55 UTC
The ELK image can no longer be built because it fails to download the GeoIP database:

    Step 10/15 : RUN mkdir  -p /usr/share/GeoIP &&  curl -L http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz | gunzip -c - > /usr/share/GeoIP/GeoLiteCity.dat
     ---> Running in 7e24279257b6
    curl: (6) Could not resolve host: geolite.maxmind.com                                                         

    gzip: stdin: unexpected end of file                                                                                                                                                         
    ERROR: Service 'elk' failed to build: The command '/bin/bash -o pipefail -c mkdir  -p /usr/share/GeoIP &&  curl -L http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz | gunzip -c - > /usr/share/GeoIP/GeoLiteCity.dat' returned a non-zero code: 1

## Context
The issue exists due GDPR and CCPA forcing maxmind to limit the public downloads. Details are explained in their blog: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

## Possible Fix
The database can still be downloaded when one registers with maxmind - see https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

## Steps to Reproduce
1. Use the docker-compose.elk.yml.dist
2. Provide the elk folder containing the Dockerfile
3. docker-compose up -d mail

**Comment by erik-wramner** [comment] 2019-12-31 14:29
Starting with the next major release (7.0 with Debian Buster) ELK will be more off an add-on with filebeat running in another container mounting the logs. Perhaps the best way to deal with this is to document the manual approach (with registration)?

**Comment by denji** [comment] 2020-01-01 03:43
https://download.ip2location.com/lite/
https://lite.ip2location.com/database/ip-country

**Comment by shoeper** [comment] 2020-01-13 14:30
It looks like redistribution is still allowed. Maybe it would be enough to update the GeoIP db only when the image is build. They also have instructions on how to automatically download the db: https://dev.maxmind.com/geoip/geoipupdate/#Direct_Downloads

**Comment by erik-wramner** [comment] 2020-01-13 19:54
The direct download still requires a key and if they are afraid to allow public downloads then this project would run the same risk if we get a license and then release the files publicly. It feels shaky. We could create parameters that make it possible to use the download with a custom key, though. If the license is passed in as a parameter then the end users will have to register, but after that things should work as before.

**Comment by gmasse** [comment] 2020-03-19 14:32
Let's check this attempt (using environment variable) #1433

**Comment by gmasse** [comment] 2020-03-19 18:20
> Let's check this attempt (using environment variable) #1433

ELK is running well. But I am concerned with the grok filters. I feel dovecot (at least) log format has changed. However I am pretty sure it is not a regression from this PR.

**Comment by aendeavor** [comment] 2020-09-12 22:05
Looking at #1606 I'll close this.

**Closed by aendeavor** 2020-09-12 22:05 UTC
Labels: build broken, frozen due to age, help wanted
