### ISSUE TITLE
Learning spam from all users

### ISSUE THREAD

**Issue by s0ftcorn** [tomav/docker-mailserver#1125] opened 2019-02-05 12:23 UTC
As stated in the FAQ spam from .Junk/ can be used to train spamassassin. But this is on a per user basis. Is it possible to use .Junk/ from all users?

**Comment by johansmitsnl** [comment] 2019-02-06 07:11
Duplicate of #592 closing this issue.

**Closed by johansmitsnl** 2019-02-06 07:11 UTC
Labels: duplicate
