### ISSUE TITLE
ManageSieve causes phantom folder to show up

### ISSUE THREAD

**Issue by evilstiefel** [tomav/docker-mailserver#651] opened 2017-07-08 23:58 UTC
Enabling ManageSieve creates the ".sieve" directory under /var/mail/%d/%u, which causes the folder to also show up for clients to be able to subscribe to. Of  course, this isn't a valid mail directory and the subscription fails:

`mail dovecot: imap(<user>@<domain>): Error: stat(/var/mail/<domain>/<user>/.dovecot.sieve/tmp) failed: Not a directory`

The issue stems from the fact that by default, **maildir_stat_dirs** is set to **no** (which it should be, because otherwise performance is degraded, see: [https://wiki2.dovecot.org/MailLocation/Maildir](https://wiki2.dovecot.org/MailLocation/Maildir))

I'm assuming this is because the user's home location is also the mail location (maildir == home). Could this be changed in the future? I'm assuming that would be difficult, since it would break the existing storage paths for anybody upgrading.

Edit: for reference, I found the topic discussing this problem here: https://dovecot.org/list/dovecot/2016-June/104400.html

Also, from the dovecot guide on why setting the mail-dir to home-dir is a bad idea: https://wiki2.dovecot.org/VirtualUsers/Home

**Comment by theomega** [comment] 2017-07-25 21:04
What I did to fix this is add a dovecot.cf overwrite:

```
plugin {
  sieve = /var/mail/sieve/%d/%n/.dovecot.sieve
  sieve_dir = /var/mail/sieve/%d/%n/sieve
}
````

**Comment by evilstiefel** [comment] 2017-07-25 21:23
Same thing, except you modified the sieve directory and not the mail directory.

**Comment by theomega** [comment] 2017-07-25 21:24
This is a duplicate of #508

**Comment by evilstiefel** [comment] 2017-07-25 21:26
Again, sort of, I don't want to spam the issue tracker, but this is more about not having the **home directory be the same as the mail directory**. Having the .sieve.dovecot link show up is just one of the side effects that might occur.

**Comment by theomega** [comment] 2017-07-25 21:28
Actually, I think you are wrong: The users in the docker mailserver are not real system users, so they in fact don't even have a home directory. This is in fact a configuration issue which can be solved with the lines I propose.

**Comment by evilstiefel** [comment] 2017-07-25 21:38
Please read the link I've provided to the official dovecot documentation. Even virtual users have a home directory. And this is exactly the thing: for regular "system" accounts, nobody would put the mail directory in the root, since it would clutter your home with lots of maildir-related files.
For virtual users in dovecot, this isn't the same and you could easily have home- and mail-directories be the same. Like it was setup in this image.

I quote: 

> Home directory shouldn't be the same as mail directory with mbox or Maildir formats (but with dbox/obox it's fine). It's possible to do that, but you might run into trouble with it sooner or later.

More information here: [Dovecot Wiki](https://wiki2.dovecot.org/VirtualUsers/Home)

**Comment by aendeavor** [comment] 2020-09-21 13:16
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.

**Closed by aendeavor** 2020-09-21 13:16 UTC
Labels: bug, enhancement, frozen due to age, postfix / dovecot related
