### ISSUE TITLE
Cert Hostname DOES NOT VERIFY

### ISSUE THREAD

**Issue by softshipper** [tomav/docker-mailserver#1439] opened 2020-03-29 14:09 UTC
Hi all   

I've created a mail server with https://github.com/tomav/docker-mailserver. Everything works, except the certificate.
I have tested the TLS on CheckTLS.com and I've got the following output messages:

![mFVNr](https://user-images.githubusercontent.com/56756949/77851129-96cac580-71d7-11ea-8df8-466785859299.png)

As you can see on the image, it says, that Cert Hostname DOES NOT VERIFY (dataxu.io != email.dataxu.io | DNS:email.dataxu.io), do I miss any DNS entry?

The DNS records are setting up as follows:

enter image description here
![image](https://user-images.githubusercontent.com/56756949/77851134-a0ecc400-71d7-11ea-9112-92dfa3a08fc4.png)

What am I doing wrong?  

Thanks

**Comment by erik-wramner** [comment] 2020-03-30 09:44
Is this an error or a warning? The problem is that the certificate is issued to dataxu.io, but the fully qualified name of the server is email.dataxu.io, so the names do not match. If it is a warning you can probably ignore it. If it is an error you need to fix it one way or another (i.e. change the certificate or how you do host names).

Or alternatively but less likely, if the certificate is for email.dataxu.io then you need to make that an A record rather than a CNAME.

**Comment by erik-wramner** [comment] 2020-04-10 06:13
No update for 11 days, can we close?

**Comment by erik-wramner** [comment] 2020-05-03 11:09
And no answer in 23 days, closing.

**Closed by erik-wramner** 2020-05-03 11:09 UTC
Labels: question, ssl/tls, waiting for contributor action
