### ISSUE TITLE
message_size_limit override no longer works in :stable

### ISSUE THREAD

**Issue by dmcgrandle** [tomav/docker-mailserver#1289] opened 2019-10-11 06:04 UTC
Finally upgraded to the latest stable image a few days ago after almost 14 months of solid and stable use.  All seemed to work well, until a message over 11MB in size attempted to be delivered.  Saw this in the logs:

`Oct 10 22:25:28 mail postfix/smtpd[1057]: NOQUEUE: reject: MAIL from localhost[::1]: 552 5.3.4 Message size exceeds fixed limit; proto=ESMTP helo=<mail.domain.com>
Oct 10 22:25:28 mail fetchmail[302]: SMTP> MAIL FROM:<name+bncbcvzbqxj6eirbnnm7xwakgqedll3zni@domain2.com> SIZE=11847352
Oct 10 22:25:28 mail fetchmail[302]: SMTP< 552 5.3.4 Message size exceeds fixed limit
Oct 10 22:25:28 mail fetchmail[302]: SMTP error: 552 5.3.4 Message size exceeds fixed limit`

I have a config directory with a postfix-main.cf file that contains this line:
` message_size_limit = 52428800`

As suggested in the [Wiki](https://github.com/tomav/docker-mailserver/wiki/Override-Default-Postfix-Configuration).

But if I do a `docker exec mail cat /etc/postfix/main.cf | grep message_size`, I see:
`message_size_limit = 10240000`

That was strange, so I reverted back to the image from 14 months ago, and voila - the message size limit has been restored.  I now do the grep and see the correct message_size_limit.  

This should be trivial to reproduce.  What has changed?

Thanks,
-D

**Comment by erik-wramner** [comment] 2019-10-11 07:25
14 months is an eternity, did we have writing back then? Seriously this sounds like a bug. However, there is an environment option for the limit: `POSTFIX_MESSAGE_SIZE_LIMIT`. What happens if you set that instead?

Your method with `postfix-main.cf` should also work, but I if it doesn't the environment option does the job for me.

**Comment by dmcgrandle** [comment] 2019-10-11 14:49
The `POSTFIX_MESSAGE_SIZE_LIMIT` env variable does work, but it leaves me a little nervous about what other overrides are no longer working from a custom `postfix-main.cf` ...

**Comment by erik-wramner** [comment] 2019-10-12 06:48
The Wiki is updated:

> That specific example is now supported and can be handled by setting POSTFIX_MESSAGE_SIZE_LIMIT.

Perhaps we should find another example to override that doesn't have a configuration option. Feel free to improve it if you like. And don't get me wrong, the overrides should work, including the one for message size.

**Comment by erik-wramner** [comment] 2019-10-27 07:43
I finally got time to look into this. It seems it is already fixed in master/latest. I fixed it for #1143 (which incidentally is the first commit after stable - bad luck). Please double-check that it works (in a test environment) and close this issue if you agree that the problem has been solved. We'll release a new stable version soon to get this and some other things in.

**Comment by erik-wramner** [comment] 2020-01-12 07:57
The new stable has been out for a while. As I've heard nothing on this since October I'll close the issue.

**Closed by erik-wramner** 2020-01-12 07:57 UTC
Labels: bug, waiting for contributor action

**Comment by mirisbowring** [comment] 2021-11-02 09:56
@erik-wramner  I can confirm this Issue as of now.
I am running the latest version (`:edge`) and am having the same issue.

I notices a strange behaviour:

When I add the `message_size_limit` var in the postifx-main.cf file, it get's written into the `/etc/postfix/main.cf` file inside the container. But somehow is not beeing applied.

When I set the value via a environment variable, it is applied.

**Comment by casperklein** [comment] 2021-11-02 10:44
> When I set the value via a environment variable, it is applied.

So what's the problem then?

**Comment by mirisbowring** [comment] 2021-11-02 10:47
> > When I set the value via a environment variable, it is applied.
> 
> So what's the problem then?
The Problem is, that it is mandatory to use the environment Variables, though there is the option to use configuration files (that are not working obviously).

**Comment by casperklein** [comment] 2021-11-02 13:39
Options in configuration files, that have corresponding ENVs, will be overwritten on container start. That's how it works.

**Comment by mirisbowring** [comment] 2021-11-02 13:44
Then, the current config flow is not good.

I have to touch the files in the config folder to do specifc things like adding / removing `reject_rbl_client`, but for increasing e.x. the message size limit (that could be configured here too), i mus provide a ENV to the container.

If I don't specify the ENV (in this case the size limit) for the container, my Value from the config file is applied in the files, but therefore is not active.

**Comment by casperklein** [comment] 2021-11-02 14:42
I think I was wrong. After looking in the code, a custom main.cf should overwrite ENV settings. Please open a new issue and provide the necessary information.

**Comment by ohuish** [comment] 2022-01-03 18:41
I know this is closed, but I ran across this today and I think it happens because `POSTFIX_MESSAGE_SIZE_LIMIT` is used to set up the quota limits in dovecot too: https://github.com/docker-mailserver/docker-mailserver/blob/f7465a50888eef909dbfc01aff4202b9c7d8bc00/target/scripts/startup/setup-stack.sh#L301

If just `message_size_limit` is set in `docker-data/dms/config/postfix-main.cf` the dovecot quota isn't updated
