### ISSUE TITLE
DKIM not working anymore after restart?

### ISSUE THREAD

**Issue by theoneandonly-vector** [tomav/docker-mailserver#1404] opened 2020-02-20 23:55 UTC
## Context
I setup DKIM and it was working correctly (tested with:
https://www.mail-tester.com
after a few days now, rechecking it's not working anymore.
The key is there but it somehow just doesn't send DKIM-mails anmyore.
I can re-run the DKIM-setup but this won't help.

## Expected Behavior
DKIM still working

## Actual Behavior
DKIM isn't working anymore.

## Your Environment
Didn't update my environment.

Anybody has an idea on how to debug?

**Comment by erik-wramner** [comment] 2020-02-21 19:11
You can set `DMS_DEBUG=1` and check your logs for warnings or errors.

**Comment by theoneandonly-vector** [comment] 2020-02-22 01:09
I just removed the private and public key, re-run the DKIM-setup and started docker-compose again now with DMS_DEBUG=1.

This resulted in an e-mail signed with DKIM but it's signature could not be verified.

is maybe my DKIM-DNS entry wrong?:
v=DKIM1;h=sha256;k=rsa;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0nTdVAp6LXV0gaXV74j33Ze4aNCl3FV75n8WOkBljsbWiOHJR9HGtr75tCNhHU2QgIiMSJ9y0rm42R4Vj1W5uqMWHRbcfilrHR2TjEsE21ubJ3x8yALbxM5uOtXWHhbVJAnbq/LNXsY/0REaH+z+ZJPPtZjLPVEBFRosy0MWeoS7GSoT4pSrH/ohy2kXGN8li7S6UkBZxRM8hcAg/dKvM3ezgjSRJ63G7PTsuaMQSRG+ETO6pMvbfya7qt7eko61wdZNbPPhTLaWSGBJPDhyl6Q9NfJrBUDxd0bKzjEg50+HG14Cbjd5R3Ev/3pLgxaAnJ1vdCpUZzONcD5sZuaSfQIDAQAB

**Comment by erik-wramner** [comment] 2020-02-22 13:08
Every time you re-run the DKIM setup you get a new key that must be updated in the DNS. Did you do that, or is the DNS entry for your old DKIM key?

**Comment by theoneandonly-vector** [comment] 2020-02-22 21:48
hey there, somehow I don't have this issue anymore, BUT:

I can remove and re-run the DKIM-setup a few times even with restarts (docker-compose) inbetween and still get the exact same private and public key!

**Comment by hanscees** [comment] 2020-02-24 21:25
A docker container will not erase volumes if you do docker-compose down. 
Opendkim saves your keys inthe ./config volume.
So opendkim will simply find the first keys you produced and use these again.

And perhaps  the setup script will skip making new keys if it finds previously produced keys as well? Would be a smart thing to do. 

The mystery why it suddenly did not work remains. To find that out you must retrace HOW you restarted exactly and so on.

**Comment by erik-wramner** [comment] 2020-02-29 09:53
I'm closing this as the issue is gone, please reopen or log another issue if you get it again.

**Closed by erik-wramner** 2020-02-29 09:53 UTC
Labels: help wanted, question
