### ISSUE TITLE
alert bad certificate: SSL alert number 42

### ISSUE THREAD

**Issue by tamueller** [tomav/docker-mailserver#1645] opened 2020-10-10 18:52 UTC
Since two days ago, I cannot retrieve my mails from the mailserver with thunderbird. Whenever I check mails, thunderbird is stuck at "Checking Mail server Capabilities", and in the log of the mailserver I get something like this:
`Oct 10 19:20:34 mail dovecot: imap-login: Disconnected (no auth attempts in 1 secs): user=<>, rip=...., lip=172.18.0.2, TLS: SSL_read failed: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate: SSL alert number 42, session=<....+2Mtt>`

I'm using Thunderbird 78.3, and I suspect the problems started with a thunderbird upgrade. An old version of thunderbird (68.12) still works. 

What I don't understand is, that my .env contains 
'SSL_TYPE='
but when I connect with my cellphone or an old thunderbird I get presented with a self-signed-certificate.

Is there anything I can do on the server-side, to solve this? or do you have any ideas on how to solve this in thunderbird?
I already tried switching to "Connection Security - None" in Thunderbird, and then I can retrieve my emails - but that's not really a valid option.

**Comment by aendeavor** [comment] 2020-10-11 16:10
Hey @tamueller. This seems to be related to an issue on your side (i.e. Thunderbird) and not `docker-mailserver`.

SSL `alert 42` [means the server demands you authenticate with a certificate, and you did not do so](https://serverfault.com/questions/806141/is-the-alert-ssl3-read-bytessslv3-alert-bad-certificate-indicating-that-the-s/806175).

> I suspect the problems started with a thunderbird upgrade

I think so too. It's always best to do a **clean** upgrade of Thunderbird, especially when going from 68 to 78. That means, removing all your data and starting fresh.

> What I don't understand is, that my .env contains
> 'SSL_TYPE='
> but when I connect with my cellphone or an old thunderbird I get presented with a self-signed-certificate.

This leads me to believe, like you said, that you misconfigured something! the `README` indicates: ***Note: Variables in .env are expanded in the docker-compose.yml file only and not in the container. The file env-mailserver serves this case where environment variables are used in the container.*** Please read the `README` and the wiki pages thoroughly. They explain the SSL setup properly.

I will close this as this is not a bug but very likely a configuration issue.

**Closed by aendeavor** 2020-10-11 16:10 UTC
Labels: wontfix

**Comment by tamueller** [comment] 2020-10-11 16:41
Ok, I also tried to install Thunderbird 68 again, and it works there. Even with a fresh install of 78 it does not work, so it looks like a thunderbird bug to me now. I also filed it there: https://bugzilla.mozilla.org/show_bug.cgi?id=1670430

**Comment by aendeavor** [comment] 2020-10-11 17:47
Alright. I'm currently on `Thunderbird 78.3.2 (64-Bit)` (because I updated recently too) :D
This works, but I'm not using self-signed certs though. Good look with fixing this:)

**Comment by gjelsas** [comment] 2021-04-18 14:06
I just had to delete and readd my account in Thunderbird. Then this Thunderbird-Bug is avoided. Not nice but okay I guess...
