### ISSUE TITLE
Move /tmp/vhost.tmp to /tmp/docker-mailserver/vhost

### ISSUE THREAD

**Issue by alinmear** [tomav/docker-mailserver#494] opened 2017-01-26 19:22 UTC
Maybe i am missing something, but from my point it would be much easier, when the vhost config ist also located at /tmp/docker-mailserver.

To make this work we only have to change _setup_postfix_vhost().

@tomav if wanted i can make a pull request for this.

**Comment by tomav** [comment] 2017-01-29 19:54
Yes, you're right, this will be better.

**Comment by tomav** [comment] 2017-06-26 19:26
@alinmear I can't reproduce this point. It has been fixed?

**Comment by johansmitsnl** [comment] 2017-09-08 18:38
@alinmear is it still an issue?

**Comment by alinmear** [comment] 2017-09-15 06:45
@tomav , @johansmitsnl  i think we first should discuss what we wanna accomplish with this.

**Point of View**
As far as i can see, the `/tmp/vhost.tmp´ is now nothing more than as already suggested by the file ending, a tmp file. We are threading it like a tmp file:

* https://github.com/tomav/docker-mailserver/blob/a3aa8b2befe2febd4ba89c8a99fe4d67b1146e6c/target/start-mailserver.sh#L509
* https://github.com/tomav/docker-mailserver/blob/a3aa8b2befe2febd4ba89c8a99fe4d67b1146e6c/target/start-mailserver.sh#L565

When i opened the issue a while ago (my shame i never provided the mentioned pr :/ ) i had the use case to host several domains and the only option was to make a volume linking an external file to the `vhost.tmp`, because this file will be parsed at every container startup (linking directly to `/etc/postfix/vhost` was not an option, because you need to make this `read only` and that would break the logic of `/tmp/vhost.tmp`:

```
if [ -f /tmp/vhost.tmp ]; then
		cat /tmp/vhost.tmp | sort | uniq > /etc/postfix/vhost && rm /tmp/vhost.tmp
fi
```

I am using the ldap logics to provide the vhost details (thx to @johansmitsnl)

**Problem/Goal**

If you are not using a ldap setup how can you provide details about mutliple vhosts?
If you are restarting the container, how can you check that there are no duplicated values within `/etc/postfix/vhost` (we are only checking `/tmp/vhost.tmp` with the uniq statement/app)?

Should we implement logics to provide multimple vhosts and the checks for this or maybe am i missing something here?

**Comment by alinmear** [comment] 2017-09-27 11:30
Any thoughts on this so far?

**Comment by johansmitsnl** [comment] 2017-09-27 18:51
@alinmear Could you suggest a PR with your solution, I guess you have a good idea how to solve it in your case.
I use ldap personally and I'm not that familiar with the non ldap solution yet.

**Comment by erik-wramner** [comment] 2019-08-13 09:43
I fail to see the problem (I have multiple vhosts working without ldap) and nothing has happened since 2017, so I'll close this. Please reopen or file a new issue if it remains an issue.

**Closed by erik-wramner** 2019-08-13 09:43 UTC
Labels: bug, waiting for contributor action
