### ISSUE TITLE
virtual_alias_domains

### ISSUE THREAD

**Issue by dashohoxha** [tomav/docker-mailserver#1694] opened 2020-11-23 08:41 UTC
## Subject

* [ ] I would like to configure a not documented mail server use case
* [ ] I would like some feedback concerning a use case

## Description

Maybe it is explained somewhere on the docs, but I couldn't find it out.

I'd like to use the mailserver for multiple mail domains.
What is the recommended way for adding `virtual_alias_domains`?

**Comment by aendeavor** [comment] 2020-11-23 11:30
Hey there @dashohoxha.

Although I do not know the answer to your question, I will mark @erik-wramner / @casperklein. They know better than I do :)

If this use case really is not documented, we will add this to the documentation.

**Comment by dashohoxha** [comment] 2020-11-23 15:21
By testing I found out that **mailserver** supports multiple email domains out of the box. So, no need to add `virtual_alias_domains` or anything else on the configuration. All that is need is to use `./setup.sh` to add email accounts or aliases (forwarders). For example:

```
./setup.sh email add user1@test1.example.org pass123
./setup.sh email add user1@test2.example.org pass123
./setup.sh alias add user2@test1.example.org xyz@gmail.com
./setup.sh alias add user2@test2.example.org xyz@gmail.com
```

Everything works as expected. I am sorry for opening this issue without proper testing.

However, maybe it is worth to mention somewhere on the docs that **mailserver** supports multiple email domains out of the box.

**Comment by aendeavor** [comment] 2020-11-23 15:24
Oh, then I misread your question. I thought there were some other difficulties involved. Sorry, I could've told you that earlier:) But your suggestion is good, I will make sure this note ends up somewhere in the `README`.

**Comment by aendeavor** [comment] 2020-11-25 12:33
Done with ec290acd1f92e1e44773085df8d8872f6f13cb25.

**Comment by williamdes** [comment] 2021-01-02 12:43
I think `virtual_alias_domains` is needed for ldap setups.

**Comment by williamdes** [comment] 2021-01-02 12:55
Currently investigating with another test, will let you know soon

**Comment by williamdes** [comment] 2021-01-02 13:48
Test added as https://github.com/desportes/infrastructure/commit/1ae727a49f808115ad489a2ad10a1e44d387c17a
Reproduced ([log](https://github.com/desportes/infrastructure/runs/1636654139?check_suite_focus=true#step:9:20)) !
```
run-tests_1  | PHPUnit 9.5.0 by Sebastian Bergmann and contributors.
run-tests_1  | 
run-tests_1  | ........sendmail: RCPT TO:<contact@another-domain.com> (554 5.7.1 <contact@another-domain.com>: Relay access denied)
run-tests_1  | F                                                           9 / 9 (100%)
run-tests_1  | 
run-tests_1  | Time: 00:14.819, Memory: 18.00 MB
run-tests_1  | 
run-tests_1  | There was 1 failure:
run-tests_1  | 
run-tests_1  | 1) Desportes\Infrastructure\tests\SendAndReceiveTest::testFromExternalToInternalAlias
run-tests_1  | Message could not be sent. Mailer Error: Could not instantiate mail function.
run-tests_1  | 
run-tests_1  | FAILURES!
run-tests_1  | Tests: 9, Assertions: 17, Failures: 1.
```


I am working on a fix.

**Comment by dashohoxha** [comment] 2021-01-02 13:50
I have tried a LDAP setup, as described here: https://github.com/tomav/docker-mailserver/wiki/Forward-Only-mailserver-with-LDAP-authentication
In this case I didn't have to use `virtual_alias_domains`. I even delete `/etc/postfix/ldap-domains.cf` on the customization script (`config/user-patches.sh`).

**Comment by williamdes** [comment] 2021-01-02 14:01
But my edge case is
Domain: a.tld
User1: email@a.tld,email@bbb.tld

Send from email@z.tld to email@bbb.tld does not work

Send email from @a.ltd to @bbb.tld works (internal server agrees with itself)

Are you in the same edge case?

**Comment by williamdes** [comment] 2021-01-03 14:50
`sendmail: RCPT TO:<contact@another-domain.com> (450 4.2.0 <contact@another-domain.com>: Recipient address rejected: Delayed by postgrey)` is my new error but this is for me a success :rocket: 


To conclude: the fix https://github.com/desportes/infrastructure/commit/b7df3264105b16dad78cff0b418fc2fed8edbfb8 is needed to add `virtual_alias_domains` for ldap setups

@aendeavor Do I create a PR to add this config value?

**Comment by aendeavor** [comment] 2021-01-03 15:18
> `sendmail: RCPT TO:<contact@another-domain.com> (450 4.2.0 <contact@another-domain.com>: Recipient address rejected: Delayed by postgrey)` is my new error but this is for me a success :rocket: 
> 
> 
> 
> 
> 
> To conclude: the fix https://github.com/desportes/infrastructure/commit/b7df3264105b16dad78cff0b418fc2fed8edbfb8 is needed to add `virtual_alias_domains` for ldap setups
> 
> 
> 
> @aendeavor Do I create a PR to add this config value? 

What you're seeing is not an error, but the default action taken by Postgrey - i.e. this is a success.

Sure, a PR is the way to go. Just keep in mind that the image-pull-policy of Docker may cause problems in the next 6 hours.

**Comment by dashohoxha** [comment] 2021-01-03 17:04
> is needed to add `virtual_alias_domains` for ldap setups

I just want to point out that LDAP setups are highly dependent on the layout of the LDAP data structures and how you want to use it. So, maybe you should also specify which LDAP setup are you talking about. As far as I know this is not explained anywhere in the docs of this project (I searched for it and couldn't find anything).

**Comment by williamdes** [comment] 2021-01-03 17:20
> > is needed to add `virtual_alias_domains` for ldap setups
> 
> I just want to point out that LDAP setups are highly dependent on the layout of the LDAP data structures and how you want to use it. So, maybe you should also specify which LDAP setup are you talking about. As far as I know this is not explained anywhere in the docs of this project (I searched for it and couldn't find anything).

I agree and this is why I just want to have the option to fill the domain list myself by hand or in a file
See my pull-request in https://github.com/tomav/docker-mailserver/pull/1739

**Comment by williamdes** [comment] 2021-01-04 23:18
Just to update everyone, after some more debug in production I found out that my LDAP filters where not correct.
So the alias/domains where never returned to postfix ldap maps.
Fixed by: https://github.com/desportes/infrastructure/commit/5678ceb6275c5932d428a52cdd8e6ca563cdbced

No more [virtual_alias_domains](http://www.postfix.org/postconf.5.html#virtual_alias_domains) needed, because they default to virtual_alias_maps that are filled with the ldap seach config (that is itself wired to an ENV passed filter)

**Comment by aendeavor** [comment] 2021-01-16 09:49
Closed due to migration to [docker-mailserver/docker-mailserver](https://github.com/docker-mailserver/docker-mailserver). Please re-open over there :D

**Closed by aendeavor** 2021-01-16 09:49 UTC
Labels: documentation, help wanted, priority 3 [LOW], question
