### ISSUE TITLE
Allow for a Postgrey whitelist

### ISSUE THREAD

**Issue by Ventajou** [tomav/docker-mailserver#711] opened 2017-09-08 01:08 UTC
With Postgrey enabled, I cannot register to alibaba.com because they cycle through a number of boxes to send their emails. This is apparently sorted using a whitelist like this: https://github.com/schweikert/postgrey/blob/master/postgrey_whitelist_clients but I couldn't figure out how to enable it...

**Comment by johansmitsnl** [comment] 2017-09-08 07:02
Duplicate of #616

**Closed** 2017-09-08 16:52 UTC
Labels: duplicate
