### ISSUE TITLE
ECC certificate support?

### ISSUE THREAD

**Issue by tearfulDalvik** [tomav/docker-mailserver#1094] opened 2018-12-25 12:08 UTC
I've got an error message `warning: TLS library problem: error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher` when I tried to use an ECC certificate. :-)

I think the problem may be located at the [cipherlist in main.cf](https://github.com/tomav/docker-mailserver/blob/0fe86e796be614af511900caa72a800b02499576/target/postfix/main.cf#L30).

Thanks 👍

**Comment by mwlczk** [comment] 2018-12-26 00:43
I am on holiday now, not sure how fast I can look into it. But its an interesting thing...
What TLS-level did you set?

**Comment by erik-wramner** [comment] 2019-08-14 07:17
Please see TLS_LEVEL in the readme. If you don't specify TLS_LEVEL it will default to TLS 1.2 and then there is a clear risk for "no shared cipher" error as many clients are too old to support it. It is secure though.

I'll close this as I assume you have solved the problem one way or another since 2018. If you still need help, please re-open or log a new issue and include your configuration (in particular TLS_LEVEL) and any other relevant details for reproducing and fixing this.

**Closed by erik-wramner** 2019-08-14 07:17 UTC
Labels: help wanted
