### ISSUE TITLE
Server doesn't work anymore

### ISSUE THREAD

**Issue by Talanor** [tomav/docker-mailserver#1034] opened 2018-09-14 11:19 UTC
## Context
Hey, I recently upgraded the image to the latest version and can no longer receive e-mails, I get those errors everytime a mail arrives on the server:
```
mail    | Sep 14 11:13:01 mail postfix/master[1021]: daemon started -- version 3.1.8, configuration /etc/postfix
mail    | Sep 14 11:13:40 mail postfix/postscreen[1173]: fatal: error reading /var/lib/postfix/postscreen_cache.db: Unknown error -30986
mail    | Sep 14 11:13:41 mail postfix/master[1021]: warning: process /usr/lib/postfix/sbin/postscreen pid 1173 exit status 1
mail    | Sep 14 11:13:41 mail postfix/master[1021]: warning: /usr/lib/postfix/sbin/postscreen: bad command startup -- throttling
```

## Expected Behavior
Well, it shouldn't crash

## Actual Behavior
It crashes

## Steps to Reproduce
I really don't do anything that special, I just start my container with ```docker-compose up -d```

## Your Environment

4G RAM
Docker version 17.05.0-ce, build 89658be
Currently on tvial/docker-mailserver:latest (103bb0a14f97fc445a42252dcbd891a6f39e4e0e6562220c12f7a8d4297c6f3b)

Please find my docker-compose.yml below:

```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: XXXX.fr
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - ./data/maildata:/var/mail
    - ./data/mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    - ./certs/:/tmp/ssl
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - SSL_TYPE=letsencrypt
    - ONE_DIR=1
    - DMS_DEBUG=1
    - SSL_TYPE=manual
    - SSL_CERT_PATH=/tmp/ssl/public.crt
    - SSL_KEY_PATH=/tmp/ssl/private.key
    - SPOOF_PROTECTION=1
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```

Thank you for your time.
Best regards

**Comment by johansmitsnl** [comment] 2018-09-14 19:38
No idea what might caused the issue. Maybe an unclean exit while writing to the db?
Will close it while it is solved.

**Closed by johansmitsnl** 2018-09-14 19:38 UTC

**Comment by alex-pl** [comment] 2019-10-06 12:14
@Talanor Thanks for sharing your solution!

The solution has fixed this issue in my case as well.
I had this issue after having a full disc… 😇 

Commands I've used:
```sh
docker exec -it mail /bin/sh
rm /var/lib/postfix/postscreen_cache.db
```

**Comment by hdznrrd** [comment] 2020-11-03 15:27
I've encountered the same issue and fixed it using @alex-pl 's workaround of deleting postscreen_cache.db.
The root cause in my case was the host system running out of storage space which must have corrupted the database.

**Comment by nrgsizadi** [comment] 2024-09-09 11:20
@Talanor thanks, my issue solved with this reply.
