### ISSUE TITLE
dir owned by 5000:5000

### ISSUE THREAD

**Issue by kbeaugrand** [tomav/docker-mailserver#405] opened 2016-12-18 13:02 UTC
Hi, 

I've got an issue when using your container. 
The mail directory has always it's owner changed to 5000:5000 at startup. 
With this kind of error message : 

> mail dovecot: lmtp(1851, kbeaugrand@ntic-infos.net): Error: stat(/var/mail/ntic-infos.net/kbeaugrand/tmp) failed: Permission denied (euid=1004(<unknown>) egid=1003(<unknown>) missing +x perm: /var/mail/ntic-infos.net/kbeaugrand, dir owned by 5000:5000_

In my configuration, I would have the /var/mail directory owned by dovecot (103:107). 
How could that done ?

Thank you for your awnser.

**Comment by tomav** [comment] 2016-12-18 20:54
Are you mounting `/var/mail` from the host? This may be the cause.

**Comment by kbeaugrand** [comment] 2016-12-18 21:03
Yes I'm, 

What do you recommend ?

**Comment by tomav** [comment] 2016-12-18 21:07
You should not have depend on your host, and may use backups.

Docker data volumes or data volume containers will do the trick.
Documentation is not perfect currently. If you dig into this topic, feel free to submit an doc. update.

There's an issue related to that.
https://github.com/tomav/docker-mailserver/issues/395

I use data volume container (data volume did not exist when I started the project).
It works great, not permission issue. Data is stored in another container, and kept when I upgrade my main image.

**Comment by tomav** [comment] 2016-12-18 21:08
I close this issue because it duplicates #395.
Do not hesitate to share idea there.

**Comment by kbeaugrand** [comment] 2016-12-18 21:08
Are you sure that this could be the cause ? 
Because Regading to the setup file (line 759) you've got a function that changes the owner of /var/mail : 

```
function _fix_var_mail_permissions() {
	notify 'task' 'Fixing /var/mail permissions'

	# Fix permissions, but skip this if 3 levels deep the user id is already set
	if [ `find /var/mail -maxdepth 3 -a \( \! -user 5000 -o \! -group 5000 \) | grep -c .` != 0 ]; then
		chown -R 5000:5000 /var/mail
		echo "/var/mail permissions fixed"
	else
		echo "Permissions in /var/mail look OK"
	fi
}
```

**Closed by tomav** 2016-12-18 21:08 UTC
Labels: documentation, question

**Comment by tomav** [comment] 2016-12-18 21:10
Sure? Absolutly not.
But persistant data should be managed carefully and you're not the first person having problem with mounted folders.

**Comment by tomav** [comment] 2016-12-18 21:12
BTW, I just edited your comment to anonymize your email / domain.

**Comment by kbeaugrand** [comment] 2016-12-18 21:12
Please take a look at target/start-mailserver.sh line 759 ... 

Ok thx for the anonymizing

**Comment by tomav** [comment] 2016-12-18 21:18
https://github.com/tomav/docker-mailserver/blob/master/target/dovecot/10-mail.conf#L109-L112

`docker` user is `5000:5000`

**Comment by kbeaugrand** [comment] 2016-12-18 21:21
Hoo Ok I will try with your solution. 

thank you

**Comment by konradreiche** [comment] 2019-03-08 18:22
I've had the same issue and I have been debugging this now for a couple of hours. There's not a connection to docket volumes. Configuring a privileged mail group in dovecot has no effect whatsoever because the `start-mailserver.sh` and `check-for-changes.sh` override the permissions hardcoded to UID/GID 5000.

**Comment by polarathene** [comment] 2023-09-30 07:16
This has been resolved for v13 release by: https://github.com/docker-mailserver/docker-mailserver/pull/3550

You can use ENV to change the default UID and/or GID (`5000:5000`) for the static Dovecot vmail user (`/var/mail` ownership).
