### ISSUE TITLE
Authentication failes

### ISSUE THREAD

**Issue by antonio-petricca** [tomav/docker-mailserver#1436] opened 2020-03-25 17:55 UTC
Hi, I have installed docker-mail server with the following settings:

> DMS_DEBUG=0
ENABLE_SASLAUTHD=1
ONE_DIR=1
OVERRIDE_HOSTNAME=mydomain.com
PERMIT_DOCKER=connected-networks
SSL_TYPE=
SMTP_ONLY=1

My goal is to use it to send email from my docker applications platform.

I have added a user by the provided setup script.

When I try to send any email to any address I get `535 5.7.8 Error: authentication failed: generic failure`.

The log reports:

> Mar 25 17:58:06 smtp postfix/smtpd[1002]: warning: SASL authentication failure: cannot connect to saslauthd server: No such file or directory
Mar 25 17:58:06 smtp postfix/smtpd[1002]: warning: SASL authentication failure: Password verification failed
Mar 25 17:58:06 smtp postfix/smtpd[1002]: warning: 172-1-0-1.lightspeed.hstntx.sbcglobal.net[172.1.0.1]: SASL PLAIN authentication failed: generic failure

Could somebody help me?

Thank you so much in advance!
Antonio

**Comment by casperklein** [comment] 2020-03-25 18:13
I don't know, if that is the root cause of your problem, however `PERMIT_DOCKER` should be _empty_, `host` or `network`, but not `connected networks`.

https://github.com/tomav/docker-mailserver/blob/b435c3866cd2cd55437901ecbb7544301c1de91f/env-mailserver.dist#L22-L29

**Comment by erik-wramner** [comment] 2020-03-25 19:19
I think you need to read up on `ENABLE_SASLAUTHD` and the related options in the readme. You have it on, but with `SASLAUTHD_MECHANISMS` empty which means authentication is with pam. Your added user will not be used; presumably only operating system users can send mail. If you want to use the added user you probably want `ENABLE_SASLAUTHD=0` which will use Dovecot for authentication. In that case you cannot use `SMTP_ONLY=1` as that prevents Dovecot from starting.

Please read through the docs carefully and plan your installation. This is a bit complex and when you stray off the beaten path to do something a little bit different you need to know how to set things up. Good luck!

**Comment by erik-wramner** [comment] 2020-04-10 06:14
No update for 15 days, does that mean this can be closed?

**Comment by erik-wramner** [comment] 2020-05-21 07:12
Closing due to inaction.

**Closed by erik-wramner** 2020-05-21 07:12 UTC
Labels: question, waiting for contributor action
