### ISSUE TITLE
addmailuser should restart mailserver if it exited due to 0 accounts

### ISSUE THREAD

**Issue by alichry** [tomav/docker-mailserver#1724] opened 2020-12-20 09:18 UTC
If no accounts were found in `config/postfix-accounts.cf`, and LDAP is disabled, the dovecot daemon would complain that no accounts were found, and in turn, the mailserver would exit.

## Context

I am adding email users programmatically. When doing so, I've added a workaround to restart the postfix if it exited.

### *What* is affected by this bug?
Services that extends docker-mailserver, not CLI users.

### *When* does this occur?
When docker-mailserver is deployed with no postfix accounts.

## *How* do we replicate the issue?

1. Deploy docker-mailserver without postfix accounts. From the logs, notice that Dovecot complained about lack of email accounts.
2. Add an email account using addmailuser. Notice how `/tmp/docker-mailserver/postfix-accounts.cf` gets updated, but not `/etc/postfix/vmailbox`

## Actual Behavior
SMTP server still down, despite adding an account.

## Expected behavior (i.e. solution)
SMTP server should be up.

**Comment by aendeavor** [comment] 2020-12-20 10:32
I see what you're up to. This is, technically speaking, expected behavior, not a bug - but of course, with what you're doing, it is a problem. I too think this could and should be handled. Please provide an implementation for the file `target/bin/addmailuser` and a PR so we can review it. I think this should then be merged quickly.

**Comment by erik-wramner** [comment] 2021-01-03 10:07
Note that there are some difficulties here. For SMTP only, there may never be any users and the server should start. For LDAP there may not be any users in the file and the server should start. There may be other cases that I have missed. Finally, how long did you wait? In theory the change detector script should detect that a user was added and restart Postfix. If it doesn't then that should be fixed!

**Comment by alichry** [comment] 2021-01-04 16:18
I did not use SMTP only, I waited for at least a minute or two -- at some point I've waited for some amount of time after realizing that the script did not start postfix. 

Please give me some time to recheck, and submit a PR if need be.

**Comment by aendeavor** [comment] 2021-01-16 09:57
We migrated to [docker-mailserver/docker-mailserver](https://github.com/docker-mailserver/docker-mailserver). Please see if your issue persists and check whether `check-for-changes.sh` restarts your server or maybe any other script. For PRs, if you've found something wrong, please open the PR in the new repository too.

**Closed by aendeavor** 2021-01-16 09:57 UTC
Labels: enhancement, postfix / dovecot related, priority 3 [LOW], script related, waiting for contributor action
