### ISSUE TITLE
PERMIT_DOCKER & Rancher

### ISSUE THREAD

**Issue by CrystalMethod** [tomav/docker-mailserver#306] opened 2016-09-03 10:50 UTC
I'm using the ``docker-mailserver`` in an Rancher [1] environment. Since some days I'm unable to use SMTP anymore. IMAP still works pretty well. In the logs I can find something like:

```
Adding container ip in my networks
postconf: fatal: -e, -X, or -# accepts no multi-line input
bash: line 1: <official ip>/32: No such file or directory
bash: line 1: <official ip>/32: No such file or directory
172.17.0.3
...
```

Since I'm on vacation I was not able to dig into details.

[1] http://rancher.com/rancher/

**Comment by Josef-Friedrich** [comment] 2016-09-04 17:27
@Zehir can you please look at this problem?

**Comment by Zehir** [comment] 2016-09-04 17:42
Hello, I dont Know Rancher.  Can you send me the result of this 2 commands from inside the container?
ip addr show eth0
Ifconfig
Thank

**Comment by CrystalMethod** [comment] 2016-09-04 19:13
Here comes the result:

```
root@mail:/# ip addr show eth0
67: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP grou
p default
    link/ether 02:54:63:e3:29:b2 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.3/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.42.15.210/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::54:63ff:fee3:29b2/64 scope link
       valid_lft forever preferred_lft forever
```
```
root@mail:/# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:54:63:e3:29:b2
          inet addr:172.17.0.3  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::54:63ff:fee3:29b2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:211590 errors:0 dropped:0 overruns:0 frame:0
          TX packets:278808 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:29632186 (29.6 MB)  TX bytes:399099187 (399.0 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:98524 errors:0 dropped:0 overruns:0 frame:0
          TX packets:98524 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:38511030 (38.5 MB)  TX bytes:38511030 (38.5 MB)
```

**Comment by Zehir** [comment] 2016-09-04 20:21
Ok so the problem is because you have 2 ipv4 address on the same network card. I will create a fix for this.

**Comment by Zehir** [comment] 2016-09-04 21:36
For 10.42.15.210/16 network, my rapid correction ignore it. I'll add a `PERMIT_EXTRA` option which will allow the addition of IP addresses, or network (comma separated).
For example:
`PERMIT_EXTRA = 10.42.15.210/16,A.B.C.D/32,E.F.G.H/30`

**Comment by tomav** [comment] 2016-09-05 10:32
Are you overriding postfix configuration? Avoid comments in this file.

**Comment by Zehir** [comment] 2016-09-05 11:13
I received an email about a comment concerning the postfix configuration but I do not find this comment. Who posted?

> Are you overriding postfix configuration? Avoid comments in this file.

**Comment by tomav** [comment] 2016-09-05 13:31
That was me. I think that comments in postfix override file break the script because it tries to `postconf -e # my comment`.

**Comment by Zehir** [comment] 2016-09-05 13:33
Here? 
https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L265

**Comment by tomav** [comment] 2016-09-05 14:40
Yep.

**Comment by Zehir** [comment] 2016-09-05 15:48
@tomav See #313

**Comment by keslerm** [comment] 2016-09-08 23:26
Just had this break my kubernetes deployment.

IP addresses are 10.24.x.x but can vary.

End up with a lot of log messages like this:

```19:06:54.000
Sep 8 23:06:53 server-179893900-si3g6 postfix/smtpd[1358]: warning: non-existent:/32 is unavailable. open file /32: No such file or directory
19:06:54.000
Sep 8 23:06:53 server-179893900-si3g6 postfix/smtpd[1358]: warning: non-existent:/32: table lookup problem```

**Comment by tomav** [comment] 2016-09-09 05:57
All test cases haven't been fulfilled using `bats`.

**Comment by CrystalMethod** [comment] 2016-09-09 20:36
I have to admit that the problem with a faulty SMTP service was caused by an incorrectly set up WLAN router here at my holiday location (the router simply blocks SMTP ports). As soon as I use my mobile phone to set up a mobile hotspot, everything works.

But the error message "No such file or directory" continuous to appear. I haven't tried other (neither PERMIT_DOCKER: host/network nor PERMIT_EXTRA) options.

**Comment by mathuin** [comment] 2016-09-16 21:48
For what it's worth, I'm using this image in a Rancher environment with `PERMIT_DOCKER: network` and I am not having any problems.  I would request that no new functionality in this area be added to the default configuration, lest it break things for others.

**Comment by keslerm** [comment] 2016-09-18 14:11
I think that maybe the issue I've run into is not specifically a Rancher issue, but warrants a separate about PR #310 that breaks any containers that use an IP that does not begin with 172. The PR may fix the multiple ip issue in situations where the default IP range is used for Docker, but breaks anything else.

**Comment by mathuin** [comment] 2016-09-18 18:11
Wow, that fix is horrible.  

https://tools.ietf.org/html/rfc1918 is the RFC which refers to private addressing space.

Here's the bit which identifies those ranges:

```
3. Private Address Space

   The Internet Assigned Numbers Authority (IANA) has reserved the
   following three blocks of the IP address space for private internets:

     10.0.0.0        -   10.255.255.255  (10/8 prefix)
     172.16.0.0      -   172.31.255.255  (172.16/12 prefix)
     192.168.0.0     -   192.168.255.255 (192.168/16 prefix)

```

Please note that 172.0.0.0-172.15.255.255 and 172.32.0.0-172.255.255.255 are valid external IP addresses administered by ARIN, the registry responsible for distributing addresses throughout much of North America.  With that PR in place, systems at those perfectly legitimate IP addresses are unable to use this container.

I'll be reposting this message to that PR as well.

**Comment by Josef-Friedrich** [comment] 2016-09-18 19:04
@mathuin @Zehir Any ideas for a better fix?

**Comment by mathuin** [comment] 2016-09-18 19:43
First, let's demonstrate there's actually a problem to fix.

https://github.com/tomav/docker-mailserver/issues/306#issuecomment-246032470 says that the original report was unrelated to any actual problem with the container, but was instead related to the router's configuration.  I can recommend to @CrystalMethod that they try `PERMIT_DOCKER: network` as it does work for my Rancher setup.  If **that** does not make the error messages go away, then something might need to be fixed.  If it does, then the documentation and/or wiki should be updated to recommend that setting for Rancher users.

For what it's worth, I have one IPv4 address on my container, and it's in RFC 1918 space.  It handles sending and receiving mail for a handful of real users on four domains.

**Comment by tomav** [comment] 2016-10-21 10:03
@Josef-Friedrich, do you know if this has been resolved? Thanks.

**Comment by Josef-Friedrich** [comment] 2016-10-21 11:32
A paragraph how to configure the mail-server in a rancher environment should be added to the documentation. The issue was never a issue. Any volunteers?

**Comment by tomav** [comment] 2016-10-21 11:37
@CrystalMethod perhaps?

**Comment by Josef-Friedrich** [comment] 2016-10-27 15:02
I volunteered [here](https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips#is-docker-mailserver-running-in-a-rancher-environment) ...

**Closed by Josef-Friedrich** 2016-10-27 15:02 UTC

**Comment by tomav** [comment] 2016-10-27 17:24
Thank you!
