### ISSUE TITLE
Mailserver suddenly stopped responding for hours

### ISSUE THREAD

**Issue by ghnp5** [tomav/docker-mailserver#1508] opened 2020-05-11 07:36 UTC
Installed this mailserver a few days ago, and has been working well enough.

At an apparently "random" time last night (3:24 am GMT), the mailserver stopped working for no apparent reason.
By "stopped working", I mean that IMAP connections were all timing out and no emails were being received (and possibly not sent too).

For sure, IMAP stopped working:

> Can't connect to 192.168.0.10,993: Connection timed out (errflg=2)

The problem got fixed when I restarted Docker service, when I woke up...

--

After that, I tried to look at the logs. The fail2ban.log seems to be cleared on restart, so I can't see it it was an IP ban. Do you think this could have been an IP ban? The cron that connects has all correct passwords.

"mail.err" only had loads of errors of "60-spam.sieve" not being able to create the "Junk" folder. I've just fixed that.
Looking at the "mail.log" / "mail.warn", I don't see any obvious error at the time it stopped responding, but I do see loads of these since:

> May 11 04:22:06 server postfix/lmtp[2603]: 864FA4800150: to=<email@host.com>, relay=mail.host.com[/var/run/dovecot/lmtp], delay=42483, delays=42483/0.03/0/0.02, dsn=4.2.0, status=deferred (host mail.host.com[/var/run/dovecot/lmtp] said: 451 4.2.0 <email@host.com> Internal error occurred. Refer to server log for more information. [2020-05-11 04:22:06] (in reply to end of DATA command))

Does this mean no one could send emails and were getting bounces?
It's very bad if this was happening :/

Why would we be returning 451 4.2.0 ?

I'm glad a simple restart accommodated this, but unfortunately my hands are tied as I cannot know what exactly HAPPENED...

And I'm not seeing any very useful logs.

> Internal error occurred. Refer to server log for more information.

What server log should I look at?!

Thank you.

**Comment by youtous** [comment] 2020-05-11 07:48
> "mail.err" only had loads of errors of "60-spam.sieve" not being able to create the "Junk" folder. I've just fixed that.

Interesting, what why dovecot wasn't able to create the  `Junk` folder? How did you fixed that?

It could be the root of the `Internal error occurred. Refer to server log for more information`.

**Comment by ghnp5** [comment] 2020-05-11 07:59
> Interesting, what why dovecot wasn't able to create the Junk folder? How did you fixed that?

By adding to the user-patches.sh:

`rm -f /usr/lib/dovecot/sieve-global/before/60-spam.sieve`

I never wanted spam emails to be sent to Junk anyway. They should go to INBOX, with ***SPAM*** in prefix.

--

I'm currently checking "mailq", and I see several of emails that I was supposed to have received, but bounced with that 451 4.2.0...

Hopefully the senders will try to send again, as I can't really afford to be losing emails for hours, like this.

What's really strange is that IMAP stopped working and the Receiving of emails stopped working.
I'm sure that "Junk" folder problem would not be THE source for this, as I see it was happening in the past days too, while everything was working fine...

**Comment by youtous** [comment] 2020-05-11 08:18
> I never wanted spam emails to be sent to Junk anyway. They should go to INBOX, with SPAM in prefix.

You could use: `MOVE_SPAM_TO_JUNK=0` https://github.com/tomav/docker-mailserver#move_spam_to_junk
Sieve filters are compiled, removing `*.sieve` files is not sufficient; see https://github.com/tomav/docker-mailserver/blob/f0defda2a19f69eed44297df0836f331c4a306c3/target/start-mailserver.sh#L642

The `unable to create Junk folder` bug could affect other people, that's why I'm asking you how to reproduce it.
---

Timeout could be caused by several things:
- amavis not able to use the socket
- dovecot not able to proceed an operation (such as moving to Junk folder or something else)
- max ip connections quota reached

**Comment by ghnp5** [comment] 2020-05-11 08:24
Thank you for your replies.

I actually had SPAMASSASSIN_SPAM_TO_INBOX=1,
but I'm adding MOVE_SPAM_TO_JUNK=0 now too. Thanks for the tip.

This mailserver is purely for one Business/Purpose, so making "global" changes like these "should be ok" (doesn't affect other people) -- but really appreciate your tips. Thanks for that.

> max ip connections quota reached

Where can I see/change this configuration?

I do see sometimes this info:

> May 11 03:30:27 server postfix/scache[22427]: statistics: start interval May 11 03:27:06
> May 11 03:30:27 server postfix/scache[22427]: statistics: domain lookup hits=3 miss=8 success=27%
> May 11 03:30:27 server postfix/scache[22427]: statistics: max simultaneous domains=1 addresses=1 connection=8

or this:

> May 10 09:50:41 server postfix/anvil[21844]: statistics: max connection rate 1/60s for (smtpd:[some IP]) at May 10 09:42:21
> May 10 09:50:41 server postfix/anvil[21844]: statistics: max connection count 1 for (smtpd:[some IP]) at May 10 09:42:21
> May 10 09:50:41 server postfix/anvil[21844]: statistics: max cache size 2 at May 10 09:42:21

**Comment by youtous** [comment] 2020-05-11 08:41
> (doesn't affect other people)

I was talking about other people using this image, not from your perspective ;)

> I do see sometimes this info: 

These messages are just statistics, nothing to worry about.

I'm suspecting dovecot-quota to be unable to process (maybe the same cause root as Junk folder).
Could you provide your `env` configuration?

Are you using the latest version (pulled after this commit : https://github.com/tomav/docker-mailserver/commit/e8581be2d352798220063f6f8040d1c127b36960)?

**Comment by ghnp5** [comment] 2020-05-11 09:12
Thank you. I believe I have the latest version, yes. I checked and I have that option:

> root@server:/var/log/mail# cat /etc/dovecot/conf.d/10-mail.conf  | grep stat_dirs
> # Seen dovecot-sieve is always enabled, setting `maildir_stat_dirs = yes` permits
> maildir_stat_dirs = yes

Here's my environment:

> OVERRIDE_HOSTNAME=mail.host.com
> DMS_DEBUG=0
> ONE_DIR=1
> POSTMASTER_ADDRESS=email@host.com
> PERMIT_DOCKER=
> TLS_LEVEL=
> SPOOF_PROTECTION=1
> ENABLE_SRS=0
> ENABLE_POP3=
> ENABLE_CLAMAV=0
> ENABLE_FAIL2BAN=1
> ENABLE_MANAGESIEVE=1
> POSTSCREEN_ACTION=enforce
> SMTP_ONLY=
> SSL_TYPE=letsencrypt
> VIRUSMAILS_DELETE_DELAY=
> ENABLE_POSTFIX_VIRTUAL_TRANSPORT=
> POSTFIX_DAGENT=
> POSTFIX_MAILBOX_SIZE_LIMIT=
> POSTFIX_MESSAGE_SIZE_LIMIT=51200000
> PFLOGSUMM_TRIGGER=daily_cron
> PFLOGSUMM_RECIPIENT=
> PFLOGSUMM_SENDER=
> LOGWATCH_INTERVAL=daily
> LOGWATCH_RECIPIENT=
> REPORT_RECIPIENT=0
> REPORT_SENDER=
> REPORT_INTERVAL=daily
> POSTFIX_INET_PROTOCOLS=ipv4
> ENABLE_SPAMASSASSIN=1
> SPAMASSASSIN_SPAM_TO_INBOX=1
> MOVE_SPAM_TO_JUNK=0
> SA_TAG=-999.0
> SA_TAG2=5.0
> SA_KILL=999.0
> SA_SPAM_SUBJECT=
> SA_SHORTCIRCUIT_BAYES_SPAM=0
> SA_SHORTCIRCUIT_BAYES_HAM=0
> ENABLE_FETCHMAIL=0
> FETCHMAIL_POLL=300
> ENABLE_LDAP=
> LDAP_START_TLS=
> LDAP_SERVER_HOST=
> LDAP_SEARCH_BASE=
> LDAP_BIND_DN=
> LDAP_BIND_PW=
> LDAP_QUERY_FILTER_USER=
> LDAP_QUERY_FILTER_GROUP=
> LDAP_QUERY_FILTER_ALIAS=
> LDAP_QUERY_FILTER_DOMAIN=
> DOVECOT_TLS=yes
> DOVECOT_USER_FILTER=
> DOVECOT_PASS_FILTER=
> DOVECOT_MAILBOX_FORMAT=maildir
> ENABLE_POSTGREY=0
> POSTGREY_DELAY=300
> POSTGREY_MAX_AGE=35
> POSTGREY_TEXT=Delayed by postgrey
> POSTGREY_AUTO_WHITELIST_CLIENTS=5
> ENABLE_SASLAUTHD=0
> SASLAUTHD_MECHANISMS=
> SASLAUTHD_MECH_OPTIONS=
> SASLAUTHD_LDAP_SERVER=
> SASLAUTHD_LDAP_SSL=
> SASLAUTHD_LDAP_BIND_DN=
> SASLAUTHD_LDAP_PASSWORD=
> SASLAUTHD_LDAP_SEARCH_BASE=
> SASLAUTHD_LDAP_FILTER=
> SASLAUTHD_LDAP_START_TLS=
> SASLAUTHD_LDAP_TLS_CHECK_PEER=
> SASL_PASSWD=
> SRS_SENDER_CLASSES=envelope_sender
> SRS_EXCLUDE_DOMAINS=
> SRS_SECRET=
> DEFAULT_RELAY_HOST=
> RELAY_HOST=
> RELAY_PORT=25
> RELAY_USER=
> RELAY_PASSWORD=

Any suggestions, please let me know!

**Comment by erik-wramner** [comment] 2020-05-11 09:51
Please see #1370 do you have similar errors in your logs? That would indicate that you need to allow more Dovecot connections. If not it is something else, perhaps fail2ban or a crash of some sort.

Have you checked the host logs? Was there any activity on the host when the error started? Automatic upgrade or whatever?

By the way, I can recommend using a volume for the log directory so that you can keep the logs when you restart the container (if that is how you lost the fail2ban log?).

**Comment by erik-wramner** [comment] 2020-05-11 09:55
Oh, and to change the limit see https://github.com/tomav/docker-mailserver/wiki/Override-Default-Dovecot-Configuration.

**Comment by ghnp5** [comment] 2020-05-11 10:56
Thank you very much.

mail_max_userip_connections was already 50.

I did not get any "Maximum number of connections from user+IP exceeded" errors, though.

> if that is how you lost the fail2ban log?

Yeah, I do have for /var/log/mail, but the "fail2ban" log was in /var/log.
I made a change today in the fail2ban config so it goes to /var/log/mail

Thank you.

**Comment by ghnp5** [comment] 2020-05-11 11:05
Wanted to say also - /var/log/messages in the Host has absolutely no messages around that time.

> amavis not able to use the socket

How can I have a look at this? What logs, etc.
Thanks!

**Comment by erik-wramner** [comment] 2020-05-11 11:12
Amavis logs to `/var/log/mail/mail.log`, just grep for amavis.

@youtous could it be a quota issue? Junk folder not created and mail rejected as user is over quota? That is also a fairly recent addition.

**Comment by ghnp5** [comment] 2020-05-11 11:33
Ah ok - that's one of the logs I was looking at anyway. Couldn't see any problems with amavis.
Definitely no logs around that time anyway.

As for quotas, I only have 1 quota for one mailbox, which wasn't affected anyway (no one sends emails to it, and it doesn't send emails either).

Thank you.

**Comment by youtous** [comment] 2020-05-11 11:55
> @youtous could it be a quota issue? Junk folder not created and mail rejected as user is over quota? That is also a fairly recent addition.

I did the following test: sending a spam message to a fullmailbox,  result:
```log
May 11 11:35:36 mail dovecot: lmtp(quotauser@otherdomain.tld)<1522><2E+aO4c4uV7yBQAAUIhAew>: sieve: msgid=<20200511113535.889CA28724D@mail.my-domain.com>: failed to store into mailbox 'Junk': Quota exceeded (mailbox for user is full)

May 11 11:35:36 mail dovecot: lmtp(quotauser@otherdomain.tld)<1522><2E+aO4c4uV7yBQAAUIhAew>: sieve: msgid=<20200511113535.889CA28724D@mail.my-domain.com>: failed to store into mailbox 'INBOX': Quota exceeded (mailbox for user is full)

May 11 11:33:24 mail postfix/lmtp[1050]: A23D128724C: to=<quotauser@otherdomain.tld>, relay=mail.my-domain.com[/var/run/dovecot/lmtp], delay=0.01, delays=0.01/0/0/0, dsn=5.2.2, status=bounced (host mail.my-domain.com[/var/run/dovecot/lmtp] said: 552 5.2.2 <quotauser@otherdomain.tld> Quota exceeded (mailbox for user is full) (in reply to end of DATA command))
```

The `.Junk` folder is created (even if the quota is full) but not populated with spam messages.
```
$ ls /var/mail/otherdomain.tld/quotauser/.Junk/
> cur		 dovecot.index.cache  maildirfolder  tmp
```
### Conclusion: Spam move when quota is full is working and does not result in an Internal error.

---

Concerning:
> not being able to create the "Junk" folder. I've just fixed that.

I did a dirty test for seeing what happens when dovecot is not able to create the `Junk` folder: 
```
; ensure quotauser mail dir exists
# ls -alh var/mail/otherdomain.tld/quotauser
> total 0K

; delete any existing Junk folder
# rm -Rf /var/mail/otherdomain.tld/quotauser/.Junk/

; prevent dovecot to create Junk folder
# chown 0:0 /var/mail/otherdomain.tld/quotauser/

; send a spam message to the user
# nc 0.0.0.0 25 <
HELO mail.external.tld
MAIL FROM: user@external.tld
RCPT TO: quotauser@otherdomain.tld
DATA
From: Docker Mail Server <user@external.tld>
To: Existing Local User <quotauser@otherdomain.tld>
Date: Sat, 22 May 2010 07:43:25 -0400
Subject: Test Message amavis-spam.txt
This is a test mail.
XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X

.
QUIT
```

Log results:
```
May 11 11:47:49 mail dovecot: lmtp(quotauser@otherdomain.tld)<4018><noZUE2U7uV6yDwAAUIhAew>: Error: Couldn't create mailbox list lock /var/mail/otherdomain.tld/quotauser/mailboxes.lock: file_create_locked(/var/mail/otherdomain.tld/quotauser/mailboxes.lock) failed: safe_mkstemp(/var/mail/otherdomain.tld/quotauser/mailboxes.lock) failed: Permission denied

May 11 11:47:49 mail dovecot: lmtp(quotauser@otherdomain.tld)<4018><noZUE2U7uV6yDwAAUIhAew>: Error: Mailbox Junk: Failed to autocreate mailbox: Internal error occurred. Refer to server log for more information. [2020-05-11 11:47:49]
May 11 11:47:49 mail dovecot: lmtp(quotauser@otherdomain.tld)<4018><noZUE2U7uV6yDwAAUIhAew>: Error: sieve: msgid=<20200511114102.89E83287244@mail.my-domain.com>: **failed to store into mailbox 'Junk': Internal error occurred.** Refer to server log for more information. [2020-05-11 11:47:49]

May 11 11:47:49 mail dovecot: lmtp(quotauser@otherdomain.tld)<4018><noZUE2U7uV6yDwAAUIhAew>: Error: sieve: Execution of script /usr/lib/dovecot/sieve-global/before/60-spam.sieve was aborted due to temporary failure

May 11 11:47:49 mail postfix/lmtp[1050]: 8E524287252: to=<quotauser@otherdomain.tld>, relay=mail.my-domain.com[/var/run/dovecot/lmtp], delay=406, delays=406/0/0.02/0.01, dsn=4.2.0, status=deferred (host mail.my-domain.com[/var/run/dovecot/lmtp] said: **451 4.2.0 <quotauser@otherdomain.tld> Internal error occurred.** Refer to server log for more information. [2020-05-11 11:47:49] (in reply to end of DATA command))
```

### Conclusion: When dovecot is not able to create the `Junk` folder, mail is bounced with **451 4.2.0**

## Further investigations 

In order to identify the root of this bug, @ghnp5 could you give the following informations:

1. output of `df -h` _in mail container_
2. output of `ls -alh /var/mail/<your domain>/<your bounced target user>/`

If you have any idea which could explain why your dovecot wasn't able to create the `Junk` directory, please let me know.

**Comment by ghnp5** [comment] 2020-05-13 10:58
Hey!

Thanks very much. I didn't receive an email with your comments above... Just saw it now by accident. Apologies for the delay.

> Conclusion: When dovecot is not able to create the Junk folder, mail is bounced with 451 4.2.0

That's not very nice of Dovecot, is it?? Worst case scenario it should just deliver to Inbox and possibly an extra email explaining that the Junk folder could not be created...

And the thing is that the Junk folder DOES exist... it's been there even before the migration to this mailserver. I wonder if it's related to me adding the prefixes "INBOX.Junk", to keep compatibility with cronjobs and other stuff.

Yeah, possibly because of that. The default Sieve script sends to "Junk" and maybe should be "INBOX.Junk", if the "INBOX" prefix is enabled. I don't think this is an easy fix for you to make, since the "INBOX" prefix is a custom setting in my own custom Dovecot config, but maybe adding some small warning to the documentation would do it.

I have another custom Sieve script that sends stuff to INBOX.Trash and it works well.

--

```
[root@server mail]# docker exec -it mailserver bash

root@server:/# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         5.5T   68G  5.1T   2% /
tmpfs            64M     0   64M   0% /dev
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/md3        5.5T   68G  5.1T   2% /var/mail
/dev/md1        101G   68G   29G  71% /usr/share/zoneinfo/UCT
shm              64M     0   64M   0% /dev/shm
tmpfs            16G     0   16G   0% /proc/acpi
tmpfs            16G     0   16G   0% /proc/scsi
tmpfs            16G     0   16G   0% /sys/firmware

root@server:/# ls -alh /var/mail/domain.com/user/
total 5.7M
drwxrwxrwx 11 docker docker 4.0K May 12 06:32 .
drwxrwxrwx 14 docker docker 4.0K May  4 17:14 ..
drwxrwxrwx  5 docker docker 4.0K May  4 17:44 .Archive
drwxrwxrwx  5 docker docker 4.0K May  6 16:06 .Drafts
drwxrwxrwx  5 docker docker 4.0K May  4 17:44 .Junk
drwxrwxrwx  5 docker docker 4.0K May  8 08:32 .Sent
drwxrwxrwx  5 docker docker 4.0K May 12 06:33 .Trash
drwxrwxrwx  5 docker docker 4.0K May  4 17:44 .spam
drwxrwxrwx  2 docker docker 448K May 12 06:31 cur
-rwxrwxrwx  1 docker docker    0 Apr 25  2016 dovecot-acl-list
-rwxrwxrwx  1 docker docker   60 May  6  2019 dovecot-keywords
-rwxrwxrwx  1 docker docker   54 May  3 16:50 dovecot-quota
-rw-rw-rw-  1 docker docker 295K May 12 06:31 dovecot-uidlist
-rwxrwxrwx  1 docker docker    8 Apr 24 09:03 dovecot-uidvalidity
-rwxrwxrwx  1 docker docker    0 Apr 25  2016 dovecot-uidvalidity.571e90b2
-rw-rw-rw-  1 docker docker  96K May 12 06:31 dovecot.index
-rwxrwxrwx  1 docker docker 4.7M May 13 10:54 dovecot.index.cache
-rw-rw-rw-  1 docker docker  372 May 12 06:32 dovecot.index.log
-rwxrwxrwx  1 docker docker  33K May 12 06:31 dovecot.index.log.2
-rwxrwxrwx  1 docker docker 1.1K May  6 16:05 dovecot.list.index
-rwxrwxrwx  1 docker docker 3.0K May 12 06:33 dovecot.list.index.log
-rwxrwxrwx  1 docker docker 8.3K May  6 15:54 dovecot.list.index.log.2
-rwxrwxrwx  1 docker docker  360 Apr 24 09:03 dovecot.mailbox.log
-rwxrwxrwx  1 docker docker 1.4K May  3 16:50 maildirsize
drwxrwxrwx  2 docker docker 4.0K May 12 06:31 new
-rwxrwxrwx  1 docker docker   36 Apr 24 09:03 subscriptions
drwxrwxrwx  2 docker docker 4.0K May 12 06:31 tmp

root@server:/#

```

**Comment by youtous** [comment] 2020-05-13 12:03
> That's not very nice of Dovecot, is it?? Worst case scenario it should just deliver to Inbox and possibly an extra email explaining that the Junk folder could not be created...

Indeed, but since we are not able to reproduce the bug I cannot tell you if it's something related to your filesystem/configuration or a bug that could affect anyone. I see no reason for dovecot not being able to create the Junk folder (if the fs is not full and permissions are correct), perhaps the internal error is due to your migration, dovecot index in the Junk folder containing incompatible file index (different version) but it's just supposition.

Thanks for the details, dovecot should be able to write, what's the output of `ls -alh /var/mail/domain.com/user/.Junk/`?

> The default Sieve script sends to "Junk" and maybe should be "INBOX.Junk", if the "INBOX" prefix is enabled.

It seems namespace `inbox` is already enabled in `10-mail.conf`;
```conf
namespace inbox {
  # Prefix required to access this namespace. This needs to be different for
  # all namespaces. For example "Public/".
  #prefix = 

  # There can be only one INBOX, and this setting defines which namespace
  # has it.
  inbox = yes
 }
```
Do you have any custom parameters for `dovecot`?

I'll test with `prefix = INBOX`

One more thought; you have deleted `/usr/lib/dovecot/sieve-global/before/60-spam.sieve` without deleting `/usr/lib/dovecot/sieve-global/before/60-spam.svbin`, I don't know the behavior of this situation, it could result in an invalid dovecot configuration : "**Internal error occurred.**" but I haven't tested that.

---

Is the bug still present? Could you try to send the following message to your inbox and see if it's moved to the Junk folder or if something wrong is logged:
```
This is a test mail.
XJS*C4JDBQADN1.NSBN3*2IDNEN*GTUBE-STANDARD-ANTI-UBE-TEST-EMAIL*C.34X

.
```

Thank you :)

**Comment by ghnp5** [comment] 2020-05-14 04:12
```
root@server:/# ls -alh /var/mail/domain.com/user/.Junk/
total 76K
drwxrwxrwx  5 docker docker 4.0K May  4 17:44 .
drwxrwxrwx 11 docker docker 4.0K May 12 06:32 ..
drwxrwxrwx  2 docker docker 4.0K Sep 26  2016 cur
-rwxrwxrwx  1 docker docker   17 May  2  2016 dovecot-keywords
-rwxrwxrwx  1 docker docker   52 Aug 20  2017 dovecot-uidlist
-rwxrwxrwx  1 docker docker  448 May  2  2016 dovecot.index
-rwxrwxrwx  1 docker docker  21K Sep 26  2016 dovecot.index.cache
-rwxrwxrwx  1 docker docker  19K May  4 17:44 dovecot.index.log
-rwxrwxrwx  1 docker docker    0 Jul  2  2019 maildirfolder
drwxrwxrwx  2 docker docker 4.0K Apr 15  2016 new
drwxrwxrwx  2 docker docker 4.0K May 17  2016 tmp
root@server:/#
```

--

> without deleting /usr/lib/dovecot/sieve-global/before/60-spam.svbin

oh... I wasn't aware of these "svbin" files. Doesn't seem to be causing problems, though, but I'll delete this one just in case!

I haven't got any crashes since, which is good!!
Been monitoring the system and it's doing well so far.

--

> Do you have any custom parameters for dovecot?

I have a file "50-before.dovecot.sieve" that has some rules with:

    fileinto "INBOX.Trash";

(notice the prefix "INBOX.", that's why it works)

--

```
root@server:/etc/dovecot# cat local.conf
# File for additional dovecot configurations.
# For more informations read http://wiki.dovecot.org/BasicConfiguration

ssl = yes
default_vsz_limit = 2048 M
mail_max_userip_connections = 50
disable_plaintext_auth=yes

namespace inbox {
  inbox = yes
  location =
  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }
  mailbox Junk {
    auto = subscribe
    special_use = \Junk
  }
  mailbox Sent {
    auto = subscribe
    special_use = \Sent
  }
  mailbox Trash {
    auto = subscribe
    special_use = \Trash
  }
  prefix = INBOX.
  separator = .
  type = private
}
root@server:/etc/dovecot#
```

--

I haven't got any errors in "mail.err" since, so hopefully all is good now.

I still don't know exactly why **suddenly** everything got broken, after several days of working fine, but I'm hoping this will not happen anymore,
or at least to be able to understand better what happened, by having the answer in the logs :)

Thank you very much for your time.

**Comment by youtous** [comment] 2020-05-14 08:58
> (notice the prefix "INBOX.", that's why it works)

I don't think this prefix is required, I've tried the Junk filter without the prefix and it was working or maybe I'm missing something.

>  or at least to be able to understand better what happened, by having the answer in the logs :)

Logs :heart: 

> I haven't got any errors in "mail.err" since, so hopefully all is good now.

Good, thank your feedback!
I think we can close this issue, feel free to reopen if anything new happens ;)

**Comment by erik-wramner** [comment] 2020-05-14 12:08
Closing, again feel free to reopen if it happens again.

**Closed by erik-wramner** 2020-05-14 12:08 UTC
Labels: bug, needs triage
