### ISSUE TITLE
openDKIM key length

### ISSUE THREAD

**Issue by pn2** [tomav/docker-mailserver#855] opened 2018-02-20 08:41 UTC
This is a wish for a feature:

Some DNS servers restrict the length of TXT fields. 
The opendkim default key length seems to have been increased from 1024 to 2048 bits. In my case, the DKIM entry now does not fit the TXT field anymore.

I now would like to have an option to shorten the key length back to 1024 bits to make it fit. I understand that it of course would be better to keep the longer keys and fix the problem on the DNS side, but my provider seems unable to do so.
 
What about a corresponding environment variable, like DKIM_KEY_LENGTH ?

**Comment by leokun** [comment] 2018-02-23 08:43
I have the same problem, I cannot past all the key (about 16 digit missing)

**Comment by johansmitsnl** [comment] 2018-02-26 07:22
Can you provide a PR?

**Comment by mwlczk** [comment] 2018-02-27 19:21
This is a duplicate of #786 .
In fact debian uses key size length of 2048 as default since January 2017(!) Those bloody debians living on the edge ;)

> opendkim (2.11.0~alpha-9) unstable; urgency=medium
  * Set umask to 0007 in opendkim.service so opendkim socket is group readable
    (Closes: #851141)
  * Set opendkim-genkey to default to 2048 bit sha-256 only keys based on
    current best practices
  * Add debian/patches/nsupdate_output.patch to fix opendkim-genzone output to
    be usable for nsupdate (Closes: #849540)
 -- Scott Kitterman <scott@kitterman.com>  Wed, 25 Jan 2017 09:58:07 -0500

can anyone (@cruisemaniac, @youaresofunny, @leokun) provide a PR accompanied by a small test for the size generated once as 1024 and once as 2048 Bit key?

**Comment by johansmitsnl** [comment] 2018-03-02 21:29
#868 is merged. You can now generate with any key size

**Closed by johansmitsnl** 2018-03-02 21:29 UTC
