### ISSUE TITLE
Daily error-mail

### ISSUE THREAD

**Issue by Starbix** [tomav/docker-mailserver#792] opened 2018-01-15 13:56 UTC
I daily get emails which look either like this 
```
/etc/cron.daily/logrotate: 
invoke-rc.d: WARNING: No init system and policy-rc.d missing! Defaulting to block.
```

or this:
```
/etc/cron.daily/logrotate: 
pkill: pidfile not valid 
Try `pkill --help' for more information. 
invoke-rc.d: WARNING: No init system and policy-rc.d missing! Defaulting to block. 
invoke-rc.d: WARNING: No init system and policy-rc.d missing! Defaulting to block.
```  
My config: 
<img width="871" alt="bildschirmfoto 2018-01-15 um 14 55 02" src="https://user-images.githubusercontent.com/12443257/34945602-2f058d24-fa04-11e7-83c3-6850c4b689e0.png">
<img width="862" alt="bildschirmfoto 2018-01-15 um 14 55 13" src="https://user-images.githubusercontent.com/12443257/34945603-2f1cf630-fa04-11e7-94d9-81f68098860f.png">
<img width="873" alt="bildschirmfoto 2018-01-15 um 14 55 20" src="https://user-images.githubusercontent.com/12443257/34945604-2f385614-fa04-11e7-9328-8b6924b65363.png">

**Comment by 17Halbe** [comment] 2018-01-19 23:23
That‘s a problem with logrotate on your host server and has nothing to do with this docker image or docker itself..

**Comment by danielpanteleit** [comment] 2018-02-14 20:47
I also receive daily messages with this kind of content and I'm pretty sure that the problem lies within the docker image. Some time ago I fixed a similar bug in #715. I don't think that we need logrotate for rsyslog anyway so maybe we should just delete /etc/logrotate.d/rsyslog or even stop logrotating completely by deleting /etc/cron.daily/logrotate.

@johansmitsnl: please reopen

**Comment by acch** [comment] 2018-02-15 08:27
I'm also receiving fore mentioned daily messages. My host runs Arch Linux with `logrotate 3.13.0-1`, but docker-mailserver is the only container producing such messages...

**Comment by johansmitsnl** [comment] 2018-02-15 18:08
Where does this message arrive? By email our just in the log?

**Comment by Starbix** [comment] 2018-02-15 19:24
@johansmitsnl by email

**Comment by acch** [comment] 2018-02-16 09:35
Here's a copy of my email:

```
From: root@mydomain.tld (Cron Daemon)
To: root@mydomain.tld
Subject: Cron <root@mail> test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
MIME-Version: 1.0
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 8bit
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <LOGNAME=root>
Message-Id: <20180215053132.D77D380027@mydomain.tld>
Date: Thu, 15 Feb 2018 06:31:32 +0100 (CET)

/etc/cron.daily/logrotate:
invoke-rc.d: WARNING: No init system and policy-rc.d missing! Defaulting to block.
```

**Comment by johansmitsnl** [comment] 2018-03-02 21:37
Did the error got tracked down? Can someone provide a PR?

**Comment by kiliant** [comment] 2018-03-06 13:15
This seems indeed to be an arch-related issue (_/sbin/init_ being not existent). As I am also experiencing this, I have tracked it down and fixed it.
Give me one more day to test whether the actual mail does not arrive any more, then I will submit a PR.

**Comment by Starbix** [comment] 2018-03-06 14:18
I use unRAID where /sbin/init exists. Also how would that affect the container?

**Comment by kiliant** [comment] 2018-03-06 14:29
Well, on both my host and my ws (running arch) _/sbin/init _ is indeed existing, but NOT inside the container, which might likely be the problem leading to the above error message. idk if it is existing when using another host os.

**Comment by akmet** [comment] 2018-03-06 21:29
I'm also getting this messages and I am using Debian Jessie. /sbin/init exists on my host but not inside the container

**Comment by kiliant** [comment] 2018-03-07 09:32
issue is indeed fixed on my end in #879

**Comment by mlatorre31** [comment] 2018-08-06 07:45
I am still having the pkill error and seems to be related to the Dockerfile and Freshclam cron being /etc/cron.d/freshclam instead of /etc/cron.d/clamav-freshclam (as per init.d script).

https://github.com/tomav/docker-mailserver/blob/358160acf9db3fc5a31713eeccdefa0f8d33bb00/Dockerfile#L99

Thus, logrotate invokes clamav-freshclam reload-log which tries to kill a deamon not running instead of running the first if part:
```
reload-log)
# If user wants it run from cron, we only accept no-daemon and stop
if [ -f /etc/cron.d/clamav-freshclam ]; then
log_warning_msg "Not reloading log for $NAME - cron option selected"
# log-reloading is not needed, because freshclam is not run as daemon
exit 0
fi
log_daemon_msg "Reloading $DESC" "$NAME"
pkill -HUP -F $PidFile $NAME
log_end_msg $?
```
Renaming the cron job to clamav-freshclam fixes the issue

**Comment by rs-development** [comment] 2019-07-29 12:01
I recently updated to 6.1.0 and i am getting the mails aswell. Any fix for this?


Subject: 

Cron <root@mail> test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )

Content:

/etc/cron.daily/logrotate:
pkill: pidfile not valid
Try `pkill --help' for more information.

**Comment by 132ikl** [comment] 2020-04-08 21:14
After updating to v6.2.2 I get the logrotate emails again.

**Comment by cybermcm** [comment] 2020-04-10 05:32
I'm still facing this issue, I'm on Debian 10.3, please reopen this issue

**Comment by erik-wramner** [comment] 2020-04-10 06:00
@cybermcm what build are you using? Can you reproduce with latest?

**Comment by cybermcm** [comment] 2020-04-10 06:39
@erik-wramner: Just saw that there is a brand new version 7.0.0, I'll test and report back...

**Comment by mcastillof** [comment] 2020-04-10 16:29
I have been receiving this daily mail since I upgraded to "latest" tag.


```
Return-Path: <root@zeus.coders.cl>
Delivered-To: mcastillof@coders.cl
Received: from zeus.coders.cl
	by zeus.coders.cl with LMTP
	id bRKXDT0bkF4bAgAA5hgraA
	(envelope-from <root@zeus.coders.cl>)
	for <mcastillof@coders.cl>; Fri, 10 Apr 2020 07:07:41 +0000
Received: by zeus.coders.cl (Postfix)
	id 30E0324001D; Fri, 10 Apr 2020 07:07:41 +0000 (UTC)
Delivered-To: root@zeus.coders.cl
Received: by zeus.coders.cl (Postfix, from userid 0)
	id 2846424599D; Fri, 10 Apr 2020 07:07:41 +0000 (UTC)
From: root@zeus.coders.cl (Cron Daemon)
To: root@zeus.coders.cl
Subject: Cron <root@zeus> test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
MIME-Version: 1.0
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 8bit
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <LOGNAME=root>
Message-Id: <20200410070741.2846424599D@zeus.coders.cl>
Date: Fri, 10 Apr 2020 07:07:41 +0000 (UTC)

/etc/cron.daily/logrotate:
invoke-rc.d: WARNING: No init system and policy-rc.d missing! Defaulting to block.

```

**Comment by cybermcm** [comment] 2020-04-10 19:25
@mcastillof: Currently I'm trying the docker-mailserver:release-v7.0.0 tag and forced the daily logrotate -> no error. I'll wait until tomorrow but I think it solves this issue

**Comment by mcastillof** [comment] 2020-04-10 19:46
@cybermcm: Can you share the command to force the daily logrotate to test that too?

**Comment by cybermcm** [comment] 2020-04-10 19:54
I took this one:
`test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )`
created a report but no error mail

**Comment by mcastillof** [comment] 2020-04-10 20:00
Ok, I have executed the same command and I have an email with a good report, not the error. 
The day that I updated to "latest" tag, I also updated the host from Debian stretch to buster. If I run the same command in the host, I also have a good report. :/

**Comment by cybermcm** [comment] 2020-04-11 05:24
It seems solved, no error message over night! Currently I'm using release-v7.0.0 image tag, latest still points to the old version....

**Comment by erik-wramner** [comment] 2020-04-11 05:58
Unfortunately not. I think it is the clamav scripts in `/etc/logrotate.d`:
```
     if [ -d /run/systemd/system ]; then
         systemctl -q is-active clamav-freshclam && systemctl kill --signal=SIGHUP clamav-freshclam || true
     else
         invoke-rc.d clamav-freshclam reload-log > /dev/null || true
     fi

```
They try to restart the clamav daemons with systemctl and invoke-rc.d, but we are using supervisorctl. I'll see how it was done in the old version.

**Comment by erik-wramner** [comment] 2020-04-11 06:16
The old code looks like this:
```
     if [ -d /run/systemd/system ]; then
         systemctl -q is-active clamav-freshclam && systemctl kill --signal=SIGHUP clamav-freshclam || true
     else
         /etc/init.d/clamav-freshclam reload-log > /dev/null || true
     fi

```

**Comment by erik-wramner** [comment] 2020-04-11 06:38
The correct way seems to be `supervisorctl signal hup clamav`. I'll fix it.

**Comment by erik-wramner** [comment] 2020-04-11 07:34
See #1451

**Closed by erik-wramner** 2020-04-11 07:34 UTC
Labels: bug
